### ISSUE TITLE
Why is the "template for Thing Descriptions" called a Thing Model?

### ISSUE THREAD

**Issue by farshidtz** [w3c/wot-thing-description#1088]
We need to define some TD types in the discovery spec and would like to keep them consistent with the conventions used in TD spec.

It seems that the TD 1.0 spec uses `@type` to refer to the actual entities, rather than their descriptions. For example:
- `Thing` 
- `saref:LightSwitch`
- `saref:TemperatureSensor`

But there is a new addition in TD 1.1 which makes the use of `Thing` above less justified:
- `ThingModel`: "A Thing Model is a template for Thing Descriptions". Previously called: Thing Description Template.

Is `ThingModel` the model of a TD or the model of a `Thing`? Or `Thing` type is an alias for Thing Description which makes ThingModel an alias for Thing Description Model?

Terminology from [wot-architecture](https://www.w3.org/TR/wot-architecture/#terminology) and [wot-thing-description11](https://www.w3.org/TR/wot-thing-description11/#terminology) for reference:
> **Thing or Web Thing:** An abstraction of a physical or a virtual entity whose metadata and interfaces are described by a WoT Thing Description, whereas a virtual entity is the composition of one or more Things.
> **WoT Thing Description or Thing Description:** Structured data describing a Thing. A WoT Thing Description comprises general metadata, domain-specific metadata, Interaction Affordances (which include the supported Protocol Bindings), and links to related Things. The WoT Thing Description format is the central building block of W3C WoT.
> **Thing Model:** A Thing Model is a description for a class of Things that have the same capabilities. It describes the Properties, Actions, and Events and common metadata that are shared for an entire group of Things. Compared to a Thing Description, a Thing Model does not contain enough information to identify or interact with a Thing instance.

Sorry for being a nuisance. We have a similar issue in https://github.com/w3c/wot-discovery/issues/43#issuecomment-808249406.

**Comment by benfrancis** [comment]
The way that I think about this is that as far as the Web of Things is concerned, the Thing Description _is_ the thing, or at least a JSON representation of its top level resource on the web.

I think of a web thing as a digital twin of a physical thing in our built environment. It is also a web resource like any other web resource, which can be referred to by its URI. A Thing Description is one representation of that web thing resource, described in JSON. A web thing could also have another representation served from the same URI (e.g. described in XML or HTML) depending on what a client asks for (in HTTP we call this content negotiation).

It therefore makes perfect sense to give a Thing Description a `@type` of `Thing`, or `LightSwitch`, since as far as the Web of Things is concerned, it _is_ the light switch.

As far as I can tell, this is consistent with the definitions pasted above from wot-architecture.

To respond to your concern about `ThingModel` being inconsistent, A Thing Model can arguably be thought of as both a model for a Thing (as an abstract data model), and a template for a Thing Description (as a concrete JSON resource).

This is why I also think that a Thing Description of a Directory should have a `@type` of `Directory` or `ThingDirectory` rather than `DirectoryDescription`.

**Comment by sebastiankb** [comment]
@farshidtz 

>ThingModel: "A Thing Model is a template for Thing Descriptions". Previously called: Thing Description Template.

May I ask where this definition come from? I'm not able to find it in the TD 1.0 nor 1.1 version.

The latest definition of the Thing Model should be so far (also see the Terminology Section): "A Thing Model is a description for a class of Things that have the same capabilities. It describes the Properties, Actions, and Events and common metadata that are shared for an entire group of Things. Compared to a Thing Description, a Thing Model does not contain enough information to identify or interact with a Thing instance. "

>Is ThingModel the model of a TD or the model of a Thing? Or Thing type is an alias for Thing Description which makes ThingModel an alias for Thing Description Model?

First of all, it is only a model of a Thing. However, it can be used to [generate Thing Descriptions](https://w3c.github.io/wot-thing-description/#thing-model-td-generation). In this process, it acts as a kind of a template, which needs to be extended with instance-specific details (e.g. communication metadata) to have a valid TD of a Thing.

**Comment by farshidtz** [comment]
It is from W3C First Public Working Draft 24 November 2020, Section 10:
https://www.w3.org/TR/wot-thing-description11/#thing-model
> **A Thing Model is a template for Thing Descriptions** that have less restriction as driven in § 5. TD Information Model and § 6. TD Representation Format. 

It has now changed to:
> A Thing Model enables the oppertunity to define the basic information model of a Thing. **It can be seen as a template for Thing Descriptions**, however, that have less restriction as driven in § 5. TD Information Model and § 6. TD Representation Format. 

Thanks for the explanation.

**Comment by sebastiankb** [comment]
If solved please close this issue
