### ISSUE TITLE
Fix default op values for Example 44 (used to be 42)

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#1089]
see https://github.com/w3c/wot-thing-description/pull/1086#discussion_r610509150

**Comment by danielpeintner** [comment]
@egekorkan I am planning to provide a PR but I am a bit unsure now while doing the changes.

The [example 44](https://w3c.github.io/wot-thing-description/#example-44) with default values looks as follows currently.

```
    "properties": {
        "status": {
            "type": "string",
            "forms": [
                {
                    "op": "readproperty",
                    "href": "https://mylamp.example.com/status",
                    "htv:methodName": "GET"
                },
                {
                    "op": "writeproperty",
                    "href": "https://mylamp.example.com/status",
                    "htv:methodName": "PUT"
                }
            ]
        }
    }
```

and you are [proposing](https://github.com/w3c/wot-thing-description/pull/1086#discussion_r610509150) to change it to 

```
    "properties": {
        "status": {
            "type": "string",
            "forms": [
                {
                    "op": ["readproperty", "writeproperty"],
                    "href": "https://mylamp.example.com/status",
                    "htv:methodName": "GET"
                },
                {
                    "op": ["readproperty", "writeproperty"],
                    "href": "https://mylamp.example.com/status",
                    "htv:methodName": "PUT"
                }
            ]
        }
    }
```

I agree, this looks ok w.r.t. `op` values but the `"htv:methodName"` does not fit. This looks a bit awkward to me !?
- GET in combination with writeproperty
- PUT in combination with readproperty

**Comment by egekorkan** [comment]
Ah, I think there was a miscommunication. What I wanted to say is that this specific example does not contain default values that can be simply removed. What I meant by 

> an op's default value, in this case, would be ["readproperty","writeproperty"] .

was that since this property does not have any readOnly or writeOnly set to true, op default values (when an op does not exist) has to be ` ["readproperty","writeproperty"]`. Since op exists and is not the default values, it cannot be removed.

**Comment by danielpeintner** [comment]
I see.

I am still a bit puzzled what to do with  [example 44](https://w3c.github.io/wot-thing-description/#example-44).
Should it be like the following "without" default values?

```
    "properties": {
        "status": {
            "type": "string",
            "forms": [
                {
                    "op": "readproperty",
                    "href": "https://mylamp.example.com/status"
                },
                {
                    "op": "writeproperty",
                    "href": "https://mylamp.example.com/status"
                }
            ]
        }
    }
```

**Comment by egekorkan** [comment]
Sorry for the confusion. What I mean is that a readable and writeable property is not a good way to demonstrate the default values of the HTTP binding. We can simply have the following:

- With default assumptions:
```js
{
	"type": "string",
	"readOnly": true,
	"forms": [{
		"op": "readproperty",
		"href": "https://mylamp.example.com/status"
	}]
}
```

- Without default assumptions:
```js
{
	"type": "string",
	"readOnly": true,
	"forms": [{
		"op": "readproperty",
		"href": "https://mylamp.example.com/status",
		"htv:methodName": "GET"
	}]
}
```

**Comment by danielpeintner** [comment]
fyi: please have a look at https://github.com/w3c/wot-thing-description/pull/1099

**Comment by sebastiankb** [comment]
@egekorkan  
>What I mean is that a readable and writeable property is not a good way to demonstrate the default values of the HTTP binding.

I'm agree with you. A more simple version would be enough. However, I need still a good explaination why the example is wrong?  This example simply applies both standard assumptions from Section [5.4](https://w3c.github.io/wot-thing-description/#sec-default-values) as first step and then Section [8.3.1](https://w3c.github.io/wot-thing-description/#http-binding-assertions).

**Comment by egekorkan** [comment]
So the problem is when default values are assumed twice in this readable and writable property. Below are three cases:
1. The way it currently is. No assumption:
```js
    "properties": {
        "status": {
            "type": "string",
            "forms": [
                {
                    "op": "readproperty",
                    "href": "https://mylamp.example.com/status",
                    "htv:methodName": "GET"
                },
                {
                    "op": "writeproperty",
                    "href": "https://mylamp.example.com/status",
                    "htv:methodName": "PUT"
                }
            ]
        }
    },
```
becoming with assumptions
```js
    "properties": {
        "status": {
            "type": "string",
            "forms": [
                {
                    "href": "https://mylamp.example.com/status"
                }
            ]
        }
    },
```
So when I want to recreate the non assumption version, I first add `readOnly` and `writeOnly` false. Then, the default value of `op` becomes `["readproperty","writeproperty"]`, no matter the protocol or form element. At this stage, it is not possible to apply HTTP defaults since they are defined for single operation values. Thus, I need to now create two form elements and not simply generate a default value.
Thus, in this case, it is not correct to remove the values of `op` by default assumptions since they actually do not have the default values to start with, i.e. for a readable and writable property `op` has default of `["readproperty","writeproperty"]`.

2. Only HTTP assumptions in a readable and writeable property: 
```js
    "properties": {
        "status": {
            "type": "string",
            "forms": [
                {
                    "op": "readproperty",
                    "href": "https://mylamp.example.com/status",
                    "htv:methodName": "GET"
                },
                {
                    "op": "writeproperty",
                    "href": "https://mylamp.example.com/status",
                    "htv:methodName": "PUT"
                }
            ]
        }
    },
```
becoming with assumptions
```js
    "properties": {
        "status": {
            "type": "string",
            "forms": [
                {
                    "op": "readproperty",
                    "href": "https://mylamp.example.com/status"
                },
                {
                    "op": "writeproperty",
                    "href": "https://mylamp.example.com/status"
                }
            ]
        }
    },
```

This is totally fine.

3. The case in https://github.com/w3c/wot-thing-description/issues/1089#issuecomment-822799664 which is also fine

**Comment by sebastiankb** [comment]
Ok, I understand the point. The problem is that we have not specified that ["readproperty", "writeproperty"] must be split into two form entries for the full explicit representation.

**Comment by danielpeintner** [comment]
The proposed fix https://github.com/w3c/wot-thing-description/pull/1099 gets rid of this problem by adding `"readOnly": true` to the property
