### ISSUE TITLE
Simplified TD: links

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#109]
Moderated focused discussion on the [Simplified TD proposal](https://w3c.github.io/wot-thing-description/proposals/simplified-td/) and `links`. Please stay on topic and use https://github.com/w3c/wot/issues/393 for any general remarks.

In https://github.com/w3c/wot/issues/393 @benfrancis wrote:

> * I think we could probably live with this. It's a bit different to the syntax proposed in JSON-TD in that it doesn't have keys which indicate the type of link, but maybe this is a more conventional way of describing links. We could explore using rel instead of an object key to indicate the type of link, e.g. "rel":"alternate" to point to a WebSocket endpoint for a Thing. It could potentially also be used to provide a link to a custom web-based user interface for a Thing.
```
"links": [
  {
    "rel": "alternate",
    "wss://things.com/things/lamp"
  },
  {
    "rel": "alternate",
    "mediaType": "text/html",
    "href": "https://things.com/things/lamp/index.html"
  }
]
```

**Comment by mkovatsc** [comment]
Good, agreement.

**Comment by mkovatsc** [comment]
@handrews The example above is also in line with JSON Schema. I would take this as our target. I hope this is pretty stable in JSON Schema.

@cabo It would be awesome if we could also align this with https://tools.ietf.org/html/draft-ietf-core-links-json-10

**Comment by handrews** [comment]
@mkovatsc do you mean the `rel`/`mediaType`/`href` format matching Hyper-Schema?  It's almost compatible, we have `targetMediaType` for this because there are at least three different media type fields in Hyper-Schema.  It started to get confusing saying things like "plain mediaType mediaType" so we gave them all distinct names.

This is not set in stone, and if there's a compelling reason that we need to support the exact words `mediaType` for some sort of compatibility we can reconsider it.  Right now the keywords pair up:

`targetSchema`, `targetMediaType`, `targetHints`

`submissionSchema`, `submissionMediaType`

`contentEncoding`, `contentMediaType`

As for `href`, for us it is a level 4 URI Template, and there is a `base` keyword (outside of the Link Description Object) against which it is resolved.  The base may also be templatized, although that's rather rare as far as I can tell.

Given that there is exactly one draft-07 implementation under way so far (with mumblings of another getting started), there's a good bit of leeway for tweaking things based on feedback right now.

**Comment by benfrancis** [comment]
Mozilla's API has been [changed](https://iot.mozilla.org/wot/#links-member) to reflect this and we are in the process of updating our various implementations accordingly.

Note that we are experimenting with link relation types like "properties", "actions" and "events" and "alternate" to point to various resources rather than using those as object keys as we were before.

**Comment by mkovatsc** [comment]
The `links` member was well received and has become part of TD even before the switch to Simplified TD. Closing.
