### ISSUE TITLE
max length payload metdata information

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#1153]
Please consider if the TD could add an additional field to tell the maximum size before sending the actual payload (like the W3C API - https://w3c.github.io/w3c-api/)

HTTP error code 413 - Payload too large is returned when the payload size is exceeded. To prevent that a metadata field in the TD might be useful.

https://datatracker.ietf.org/doc/html/rfc7231#section-6.5

The same question also applies to the 414 error code, (URI too long)

**Comment by egekorkan** [comment]
Do you mean something in the form level or in data schema level? If you mean in Data Schema level, we already have that for numbers, strings etc. We of course do not have it for an object/array since JSON Schema does not have such a thing and it should be calculated from the structure I would say. What we do not have is a very good way to say how big an image should be when sending a JPEG (or other binary formats). If the image is encoded into base64, then we are maybe fine if we specify the max string length. I am not sure if the string length correlates well with the actual size of the image but I would guess it does. For binary images, we can use the word format with a string type and put binary in there. Then, I would again guess that it correlates to the size.

Regarding URIs, we are already communicating what the URI should be, so if a URI is too long, the TD is wrong or the Thing simply cannot process a request it claims to support. If you mean URI variables, we accept only simple JSON types that all have a way to communicate maximum size.

From reading on the 413 text at MDN, this is a constraint that the Consumer should follow, thus it makes sense to communicate it in a TD. The W3C API linked above supports only GET requests, thus I do not understand how it relates here.

**Comment by egekorkan** [comment]
In the call of 21.07, we have clarified the questions regarding how to impose payload lengths:

- For a normal payload, the data schema terms can be used to limit consumers on what is the maximum payload size:
```
"type": "string",
"maximumLength": 12
```

- For URI length: URIs are mostly static but dynamic ones via the use of `uriVariables` can be limited
