### ISSUE TITLE
Type of `enum`, `const`, and `default`

### ISSUE THREAD

**Issue by JKRhb** [w3c/wot-thing-description#1194]
At the moment the type for `enum`, `const`, and `default` is "any type" which makes it possible to define a `DataSchema` like the following which also passes JSON Schema validation:

```json
{
    "type": "string",
    "const": 5,
    "enum": [2.3, "foo", true, ["hi"]],
    "default": {}
}
```

While I think that this can be useful when no `type` is given, I was wondering if there should be a constraint added that binds the type of these tree fields to the `type` of the `DataSchema` if one is present.

**Comment by egekorkan** [comment]
This is actually due to JSON Schema specification. What you have is indeed a valid JSON Schema (it validates on online JSON Schema validators) and there are rules on what precedes what that I couldn't find now. The specification also does not specify something specific.
In TD playground, I do some additional checks and the co-presence of enum and const is one of them. If you validate the TD named enumConstContradiction, it will display a warning

**Comment by egekorkan** [comment]
So the official answer is more or less what I wrote above. They compared it to an unreachable branch in your code like `if(false){something}`. Apparently, there is an official linter coming up

**Comment by JKRhb** [comment]
Thank you for investigating this! :) So I suppose an implementation must support modelling a `DataSchema` like this although it is discouraged? Or would it be acceptable if this was ruled out?

> They compared it to an unreachable branch in your code like `if(false){something}`. Apparently, there is an official linter coming up

I not entirely convinced by this comparison but the linter is very good news :) (The TD validator is very awesome as well by the way!)

**Comment by egekorkan** [comment]
My opinion on this would be split on what an implementation is:
- TD Parser: I would say that it should not give an error saying that it is an invalid data schema or TD. Some warnings or recommendations (like a linter) should be possible (and encouraged) though. 
- Exposed Thing: If the Thing uses an automatic JSON Schema validation for the inputs it gets, all inputs will fail.
- Consumer1: A UI generation use case: The UI will be based on one of the terms or the behavior will not be defined.
- Consumer2: Payload generation use case: https://json-schema-faker.js.org/ generates the constant value of 5 for the schema above. Another generator can behave differently.

After this, maybe we should have a set of recommendations on how to write better TDs :)

**Comment by egekorkan** [comment]
To go deeper in the rabbit hole: https://github.com/json-schema-org/json-schema-spec/issues/1079 

Pretty good list to be honest :)

**Comment by egekorkan** [comment]
Should we close this and continue discussion in #1195?

**Comment by JKRhb** [comment]
> Should we close this and continue discussion in #1195?

Sure :) I think the original issue is also a subset of https://github.com/w3c/wot-thing-description/issues/1390, where this aspect of the discussion can continue.

**Comment by gregsdennis** [comment]
Revisiting this, I'd like to offer the following:

>  I was wondering if there should be a constraint added that binds the type of these tree fields to the `type`...

I think the problem is misdiagnosed.

The problem isn't that the values of `const`/`enum` don't match the rest of the schema.  The problem is that the rest of the schema exists at all.

`const` means "only exactly this value is allowed."  Thus, any other keywords the schema contains are superfluous.  They don't add anything to the validation.  To illustrate this, what does the `type` keyword add in the following schema?

```json
{
  "type": "string",
  "const": "alpha"
}
```

Nothing!  The value is already completely constrained to being exactly a string containing the text "alpha".  Further constraining the type does nothing.

`enum` is just shorthand for an `anyOf` with a bunch of `const` schemas, so the same logic applies.

```json
{
  "anyOf": [
    {"const": 2.3},
    {"const": "foo"},
    {"const": true},
    {"const": ["hi"]}
  ]
}
```

The linting rule for these shouldn't be "Do the values match the rest of the schema?" because the rest of the schema doesn't do anything.  The linting rule should be "Are these keywords defined in isolation?"

---

`default` is a different animal because it's just an annotation.  Linting should definitely check this against the schema that contains it.
