### ISSUE TITLE
unit for human-redable / display purposes or as semantic annotation?

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#1202]
data schema comes with the `unit` term, however, it is quite open if this used for human-readable / display purposes like "unit" : "°C" or based on a semantic reference like `"unit": "om:degree_Celsius"`.

The question is which kind of option should be preferred or how the TD processor should handle this two different approaches. 

Another idea is that we should make clear that, e.g., "unit" is only used for human-readable / display purposes and we introduce a new term like "unitRef" for doing semantic references.

What do you think?

**Comment by Fady222** [comment]
If there should be only one "unit"-keyword, I would prefer for it to be a semantic reference because it would be better automated semantic reasoning. But I do like the approach of introducing two separate keywords better.

**Comment by egekorkan** [comment]
I would say that two separate terms would be needed for TD 1.1. Ideally, these can be encapsulated into a single, unnamed for now, container. The human-readable display use case gets a bit tricky since we need to think of internationalization. I think that if we want to use the SI acronyms (like °C, °F for temperature and Pa for pressure), they are the same in every language, even in Chinese (in Arabic it is inverted, i.e. C°, but I hope that it is handled somehow). However, if someone wants to display more something like `Pressure: 3 Pascals` on a display, the unit part at the end becomes `Паскаль` in Russian.

**Comment by Digital-Water** [comment]
The keyword 'units'is normally used for the semantic use case.

**Comment by sebastiankb** [comment]
from today's TD call:
- group also prefer to have the unit value mainly semantic based
- this kind of information should be provided in the TD spec

**Comment by sebastiankb** [comment]
we should also think about introducing a term `symbol` that is used for the symbol value like `%`. However, it should also take into account the conflict as described in https://github.com/w3c/wot-thing-description/issues/1210

**Comment by benfrancis** [comment]
As a data point, in WebThings we [use](https://webthings.io/schemas/) the long written form of SI units [1][2][2] as values of the unit member (e.g. "hectopascal", "percent", "kelvin", "ampere", "micrograms per cubic metre", "hertz", "watt", "degree celsius", "volt", "second" etc.).

This string is then parsed by WebThings Gateway along with the value and turned into a string like "21°C" at the user interface layer. Unit conversion is also applied at this stage, so that if the user has expressed a preference for Fahrenheit in Settings for example then the unit would be displayed as "69.8°F" instead.

So we always use SI metric units on the back end (i.e. in Thing Descriptions), and localisation is handled on the front end.

My ideal solution would be that by default unit values are parsed as an SI string, but that this can be extended with semantic markup with a prefix where specialist units are needed. This maintains the idea that by default a Thing Description is plain JSON, but can be extended with semantic annotations.

--- 

1.  https://en.wikipedia.org/wiki/International_System_of_Units
2. https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf/2d2b50bf-f2b4-9661-f402-5f9d66e4b507?version=1.10&download=true
3. https://www.nist.gov/pml/special-publication-330/sp-330-section-2#2.3
