### ISSUE TITLE
Use of Additional Response in non-error cases

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1211]
The additional responses mechanism was added to be used mainly for reporting errors and their error-specific payloads. However, I do not see how one can use them in other cases. The specification text says _"additional expected responses are possible, e.g. for error reporting."_ so it means that it can be used for non-error cases as well. 

It also says _"Each additional response needs to be distinguished from others in some way (for example, by specifying a protocol-specific error code), and may also have its own data schema."_ . I find it really concerning its use in non-error cases, i.e. when `success` is set to true. If one differentiates the responses only by using a different data schema, only some JSON Schema validation can tell whether the response is an `additionalResponse`. Even worse, what if both schemas are only `"type":"string"`, which is plausible given that better specifying a data schema with additional validation words is extra work and people can be lazy. 

What I do not understand is, what are the use cases of non-error additional responses? I think we should name this simply `errorResponses` and make everything much more clear. If there is a use case I do not know about, it should be still called `alternativeResponses` since the current wording is understood as if the Consumer will get the normal response plus some additional ones on top of it.

I remember that this was added to describe errors in the directory API TD but I do not see that TD using it for non-error cases. Any opinion on this @mmccool , @farshidtz ?

**Comment by farshidtz** [comment]
Here is an example for multiple success responses: https://github.com/w3c/wot-thing-description/issues/617#issuecomment-665105127
This maps well to OpenAPI specs.

But I now understand that a better way to model that particular example is to define different interaction affordances, each with one success and multiple error responses. That's what we did with the [Directory API](https://github.com/w3c/wot-discovery/blob/main/directory.td.json). Though I still think there could be an API using some protocol serving distinct success responses depending on the internal state.

**Comment by egekorkan** [comment]
> Though I still think there could be an API using some protocol serving distinct success responses depending on the internal state.

I understand this use case now but still couldn't we model it with an `anyOf` in the data schema level? That would not work if we want to also link a response to 200 to a particular one and 204 to another one.

Regarding modeling as different affordance, in the API I don't see many Data Schema usage, mostly the contentType is enough right?

**Comment by benfrancis** [comment]
Another example of this is the [`invokeaction`](https://pr-preview.s3.amazonaws.com/benfrancis/wot-profile/pull/89.html#invokeaction) operation in the proposed action protocol binding for the Core Profile, which has two possible success responses.

Request:
```http
POST /things/lamp/actions/fade HTTP/1.1
Host: mythingserver.com
Content-Type: application/json
Accept: application/json
{
  "level": 100,
  "duration": 5
}
```
200 OK response (the reaction has already completed):
```http
HTTP/1.1 200 OK
Content-Type: application/json
{
  "status": "completed"
}
```

201 CREATED response (the action is ongoing, tracked by a new resource):
```http
HTTP/1.1 201 CREATED
Content-Type: application/json
Location: /things/lamp/actions/fade/123e4567-e89b-12d3-a456-426655
{
  "status": "pending",
  "href": "/things/lamp/actions/fade/123e4567-e89b-12d3-a456-426655"
}
```

Note that the data schema is different in each case, because there is no href member in the synchronous response but it is mandatory in the asynchronous response.

**Comment by egekorkan** [comment]
For the case above of @benfrancis , how does the Consumer choose one way or the other? From the linked PR it seems that the Consumer needs to adapt and the difference is somehow not on the TD. I would expect that a Thing behaves async or sync and not both depending on some internal decision. If the way it behaves is the same for all Consumers, it can be described in the TD?

In any case, I see the need for this since sadly there are already such cases out there that we need to be able to describe.

**Comment by benfrancis** [comment]
@egekorkan wrote:
> For the case above of @benfrancis , how does the Consumer choose one way or the other?

It doesn't, the Consumer just invokes an action and the Web Thing can respond with either type of response.

> From the linked PR it seems that the Consumer needs to adapt and the difference is somehow not on the TD.

That's correct, a Consumer is expected to recognise both the 200 and 201 responses, though supporting follow-up operations based on the href member of the 201 response is optional.

> I would expect that a Thing behaves async or sync and not both depending on some internal decision.

That is the most likely scenario yes, though it may respond differently for different action affordances of the same Thing (depending on whether they are long-running actions or short-lived ones).

There's technically nothing in the current proposal which prevents a Web Thing from responding differently to different invocations of the same action affordance (e.g. depending on whether the action completes before an HTTP timeout period), in which case both possible success responses would need to be provided in a (canonical) Thing Description.

A Web Thing which always responds one way or the other to a given action affordance could have a simpler (canonical) Thing Description which only defines a single success response.

> If the way it behaves is the same for all Consumers, it can be described in the TD?

It's the same for all Consumers, but not necessarily for all actions or even all invocations of the same action.

> In any case, I see the need for this since sadly there are already such cases out there that we need to be able to describe.

Exactly.

**Comment by egekorkan** [comment]
Alright thank you for clarifications. If only some actions are sync or async, this issue https://github.com/w3c/wot-thing-description/issues/890 finally has another use case that @ashimura was asking for.

**Comment by mmccool** [comment]
So it seems that:
1. We have use cases where multiple successful responses on a single interaction makes sense
2. Ege raises a valid point that depending only on the payload (e.g. different data schemas) is troublesome.  Using a different success code (e.g. 200 vs 201 as in Ben's example) makes more sense but may not be possible in other protocols.  The example in the linked issue used different contentTypes (e.g. jpeg vs png image), and headers could also be used to distinguish them (again, not possible in all protocols).

I do think 2 is valid but *describing* that something is done a certain way is not *prescribing* that it be done this way.  And since OpenAPI allows this, and since I think it would be useful to be able to map web APIs into Thing Descriptions, I think we should keep it as is... but maybe add some guidance on appropriate/desirable usage patterns (and discourage, for instance, ONLY distinguishing responses by data schemas, and suggest use of alternative response codes in protocols that support them, i.e. HTTP).

So... I think to resolve this issue, we can leave the normative part alone, but perhaps add some additional explanatory text, and perhaps an example (such as Ben's, above).

**Comment by mmccool** [comment]
BTW OpenAPI allows this but I suspect only with different response codes (it is, of course, HTTP-centric).

**Comment by mmccool** [comment]
Regarding "Alternative" vs. "Additional" I think that in fact "alternatives" was the original proposal but what changed to "additional" for some reason that I hope is documented in the original (linked) issue.  All other things being equal I'd leave it alone since otherwise we need to track down and update test cases, implementations, etc. and IMO "Additional" is OK.

**Comment by egekorkan** [comment]
I am "satisfied" with all the answers and moving to close this issue. Thank you all!
