### ISSUE TITLE
Restructuring of top level term 'name'

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#122]
Based on the discussion of the Prague f2f, the term _name_ should be able to assign multiple languages:
`
"name": {"en": "My Thing", "de": "Mein Ding"}
`

**Comment by benfrancis** [comment]
The need for localisation is likely to be broader than just this one member.

The Web App Manifest specification had the same requirement and the [conclusion](https://w3c.github.io/manifest/#internationalization) was to have language-specific Thing Descriptions and use HTTP content negotiation (using the Accept-Language header) or URL query strings to specify the desired language.

I would suggest this approach rather than try to include a potentially very large number of strings for different languages in the same Thing Description.

**Comment by zolkis** [comment]
I agree with Ben, it is better to do content negotiation/generating TD's on request.

In addition, IIUR the `name` attribute is user-settable, i.e. implementations should accept local strings to set it. It is opaque from the implementation view (other than basic string validation).

**Comment by sebastiankb** [comment]
Thank you for this pointer and I also like this idea. I will take this to next TD web meeting and ask if the group would be also agree on that.

**Comment by sebastiankb** [comment]
I will close this issue and point to latest discussion about i18n in TD: https://github.com/w3c/wot-thing-description/issues/161
