### ISSUE TITLE
Red square around W3C Logo?

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1267]
In all WoT specifications, I am seeing a red border around the W3C logo. Is it only me? I have checked with multiple browsers and private modes and smartphone, still the same behavior. The title is also black instead of blue.
![image](https://user-images.githubusercontent.com/20195407/140395473-62f864fe-2a0a-4fa9-a9b0-5f51b126fc0f.png)

**Comment by JKRhb** [comment]
It seems to be a style specific to Editor's Drafts if I am not mistaken. The TD recommendation and the latest Working Draft don't have the red border, at least in my case.

**Comment by relu91** [comment]
Same here, tested with the current draft

**Comment by egekorkan** [comment]
@ashimura can you investigate this?

**Comment by ashimura** [comment]
If you add "&specStatus=WD" after the [GitHub IO URL](https://w3c.github.io/wot-thing-description/?specStatus=WD), the logo doesn't have red background.

On the other hand, if you click the "ReSpec" button on the right above of the [ED draft](https://w3c.github.io/wot-architecture/?specStatus=ED) and save the resulted HTML by clickking "Export" (and then "HTML"),  you can tell:
1. The resulted HTML includes:
```<link rel="stylesheet" href="https://www.w3.org/StyleSheets/TR/2021/W3C-ED">```
and:
```<a class="logo" href="https://www.w3.org/"><img crossorigin="" alt="W3C" height="48" src="https://www.w3.org/StyleSheets/TR/2021/logos/W3C" width="72"></a>```
2. The [CSS file above](https://www.w3.org/StyleSheets/TR/2021/W3C-ED.css) says  "--logo-bg: red;".

I think that's why the Editors Drafts have red background for the W3C logo (=red square around the logo).

**Comment by egekorkan** [comment]
Thanks for the explanations @ashimura ! Is this the desired behavior or have we misconfigured something? Some specs I find do not have this but all our specs got it without any code change from our side. Some that look like before:
- https://w3c.github.io/sensors/
- https://gpuweb.github.io/gpuweb/wgsl/

Some that look like ours:
- https://w3c.github.io/epub-specs/epub33/ssv/
- https://w3c.github.io/geolocation-api/
- https://w3c.github.io/manifest/
- https://w3c.github.io/webtransport/

Some specs do not even use the W3C logo:
- https://w3c.github.io/device-posture/

**Comment by ashimura** [comment]
If you look at the Web pages of:
* https://w3c.github.io/sensors/
* https://gpuweb.github.io/gpuweb/wgsl/

there no "ReSpec" button at the right top.

Also if you look into the source HTML files of those pages, there is no reference for ReSpec.

So those two drafts above don't use ReSpec and are static HTML files.

I'd suggest you quickly skim the source HTML files of the specs before raising an Issue on GitHub :)

**Comment by k-toumura** [comment]
A similar issue has also been raised in w3c/tr-design#268 .

**Comment by egekorkan** [comment]
Call of 30.11: As decided before, this does not appear on WDs but only on Editor's Drafts. We can ignore and simply close the issue.
