### ISSUE TITLE
New TD 1.1 namespace IRI

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#1276]
Based on the last TPAC meeting with an expert from the JSON-LD group, we should agree on a new namespace. 

To follow the pattern from TD 1.0 we should simple update the year in the IRI for 1.1:

`https://www.w3.org/2021/wot/td/v1`

Based on the discussion, some members are also interested to have the version in the namespace such as 

`https://www.w3.org/2021/wot/td/11/v1`

or 

`https://www.w3.org/2021/wot/td/1/1/v1`

or

`https://www.w3.org/2021/wot/td11/v1` (we have this also for https://www.w3.org/TR/wot-thing-description11/)

In my opinion, we should just go for the simple year update to associate the TD version. 

I would like to collect what others think about it.

**Comment by relu91** [comment]
What about `https://www.w3.org/2021/wot/td/v11`? 

`https://www.w3.org/2021/wot/td/11/v1`: I read this as having a sub-resource called 11 with version 1
`https://www.w3.org/2021/wot/td/1/1/v1`: same as above but even weirder
`https://www.w3.org/2021/wot/td11/v1`: might be ok but still confusing cause it seems that td 1.1 might have different versions.

**Comment by lmy441900** [comment]
Both `http://www.w3.org/2021/wot/td/v1` and `http://www.w3.org/2021/wot/td/v11` look better to me.

**Comment by sebastiankb** [comment]
Please note that the "/v{x}" character is used to refer to a specific context file.

E.g.: So far we have for TD 1.0 only one context file version. However, if an error occurs in the context file after the release of REC 1.0, we can provide an errata for the specification with a new URI such as `https://www.w3.org/2019/wot/td/v2`.

**Comment by danielpeintner** [comment]
I don't wanna propose yet another IRI and confuse more people 🙈
Having said that, in the spirit that v1.1. is meant to be backwards compatible I would argue that

`https://www.w3.org/2019/wot/td/v11`

makes even more sense (Note: keep the year 2019 from the 1.0 context and increase the version field only).

**Comment by sebastiankb** [comment]
>https://www.w3.org/2019/wot/td/v11

As I mentioned above the last URI part is used to identify the context file version and not the TD version.

**Comment by sebastiankb** [comment]
Please find the thread here that we used for the TD 1.0 namespace discussion https://github.com/w3c/wot-thing-description/issues/442

**Comment by benfrancis** [comment]
@sebastiankb wrote:
> Please note that the "/v{x}" character is used to refer to a specific context file.
> 
> E.g.: So far we have for TD 1.0 only one context file version. However, if an error occurs in the context file after the release of REC 1.0, we can provide an errata for the specification with a new URI such as `https://www.w3.org/2019/wot/td/v2` to point to an updated/fixed context file.

Interesting, I would not have guessed that. Especially not from the point of view of a Consumer which parses a Thing Description as plain JSON.

I understand if this is considered a JSON-LD best practice, but in reading and implementing the specification over many years my assumption so far has definitely been that v1 refers to the Thing Description specification version, and therefore a new namespace IRI for WoT Thing Description 1.1 would be: 

`https://www.w3.org/2022/wot/td/v1.1`

- 2022, because that's when publication of WoT Thing Description 1.1, and its corresponding JSON-LD context, is expected (at least I hope it's not 2023!)
- v1.1 (or v1-1) to indicate WoT Thing Description 1.1 (not v11, which looks like version eleven!)

Under semantic versioning conventions I would have expected a bugfix release of the context to be versioned like:

`https://www.w3.org/2022/wot/td/v1.1.1`

I guess it depends to what extent we care about (one perspective on) JSON-LD best practices vs. more general developer usability.

**Comment by egekorkan** [comment]
In my order of preference:
- `https://www.w3.org/2022/wot/td/v1.1`
- `https://www.w3.org/2022/wot/td/v11`

I don't like keeping the old year, do we want to say 1.1 of the context released in 2019? If so, for TD 2.0 one can argument that we should have 2019 as well since it is the 2.0 of the context released in 2019.

> we can provide an errata for the specification with a new URI such as https://www.w3.org/2019/wot/td/v2 to point to an updated/fixed context file.

I also find this confusing, I like v1.1.1 more

**Comment by sebastiankb** [comment]
just to be sure: Dots at the end of a URL don't lead to file interpretation, do they? 

If this works, my favorite would be also `https://www.w3.org/2022/wot/td/v1.1`

**Comment by benfrancis** [comment]
@sebastiankb wrote:
> Dots at the end of a URL don't lead to file interpretation, do they?

I wondered this too, but GitHub seems to think it's fine! E.g. 
- https://github.com/w3c/wot-thing-description/releases/tag/REC1.0
- https://github.com/WebThingsIO/gateway/releases/tag/1.0.0

**Comment by sebastiankb** [comment]
@knimura @swickr it would be great to hear your opinion on this as well: 

would such a namespace `https://www.w3.org/2022/wot/td/v1.1` ok for the new TD 1.1 context file?

**Comment by relu91** [comment]
For the record I would love to see this URL too:
```https://www.w3.org/2022/wot/td/v1.1```

I don't like v11 either, but I remember that there were some people advocating against having dots in context URLs (or W3C Documents (?)).

**Comment by sebastiankb** [comment]
Since there is no final decision on the new namespace yet, I just want to share that DID uses an URL without a year.  E.g., [here](https://www.w3.org/TR/did-core/#example-1-a-simple-did-document).

Theoretically, this may also be an option that would result in a more compact length: 

`https://www.w3.org/wot/td/v1.1`

Do you have any thoughts on this?

**Comment by benfrancis** [comment]
> `https://www.w3.org/wot/td/v1.1`

Looks fine to me, though obviously not consistent with the 1.0 namespace.

**Comment by sebastiankb** [comment]
> Looks fine to me, though obviously not consistent with the 1.0 namespace.

Thats right. Lets keep `https://www.w3.org/2022/wot/td/v1.1`. In the meantime I already got the ok from @plehegar

An PR is already available #1318

**Comment by egekorkan** [comment]
Call of 02.03: Done already, closing.
