### ISSUE TITLE
Canonicalization - array vs. single value

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#1296]
Step 6 in [Canonicalization](https://w3c.github.io/wot-thing-description/#canonicalization-serialization-json) reads as follows 

> 6. In the Canonical TD, all values that can be expressed as either an array or as a single value MUST be written as a single value if there is only one element. In other words, square brackets around arrays of single elements must be removed. 

I wonder "what" should happen in case of an empty array (see `@type` below).
Should it be removed? Is this transformable from RDF/JSON-LD?

```
{
	"@context": "https://www.w3.org/2019/wot/td/v1",
	"@type": [],
	...
}
```

**Comment by sebastiankb** [comment]
also see #1304

**Comment by danielpeintner** [comment]
Question: I wonder whether we "close" such issues or simply defer them until Canonicalization gets re-introduced. I think we should not loose them...

**Comment by sebastiankb** [comment]
at the moment it is quite uncertain how relevant it will be when we will rely on a standardized JSON-LD signing

**Comment by mmccool** [comment]
I think we should close the issue to avoid confusion.    We can always find such issues again and reopen them when and if we need them.  I have applied the "canonicalization" label to make issues related to canonicalization easy to find.  What we probably should do though is gather our experience and requirements and discuss them with the JSON-LD group so that our requirements are met.  In particular, things like default values, names, and values like dates and times need to be handled correctly, perhaps as an extension of framing.

**Comment by egekorkan** [comment]
Closing this as part of canonicalization issues. They will be reconsidered in 2.0 by searching for the label
