### ISSUE TITLE
Please address comments in https://github.com/w3c/wot-thing-description/pull/1301#pullrequestreview-826651669

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#1321]
This language in this PR contains a reference to the binding template spec in a RFC assertion.
The sentence needs to be split and move the binding templates out of the normative part.

See comment here:
https://github.com/w3c/wot-thing-description/pull/1301#pullrequestreview-826651669

**Comment by relu91** [comment]
> This language contains a reference to the binding template spec in a RFC assertion.
The sentence needs to be split and move the binding templates out of the normative part.

I was wondering the same, what happens if a normative assertion refers to not normative documents? I guess is not a valid assertion. However, if we split the assertion the end result would be that people can use any syntactic valid URI in `href`, This is not ideal cause there's not really a consensus for certain IoT protocols about URIs (see MQTT). I think the real issue here is that we need to have the referred protocol binding template section to be **normative**. 

To be clear, this section https://w3c.github.io/wot-binding-templates/#creating-a-new-protocol-binding **and** all the sections within the specific binding template document like this: https://w3c.github.io/wot-binding-templates/bindings/protocols/modbus/index.html#url should be **normative** IMHO.

**Comment by mlagally** [comment]
> To be clear, this section https://w3c.github.io/wot-binding-templates/#creating-a-new-protocol-binding **and** all the sections within the specific binding template document like this: https://w3c.github.io/wot-binding-templates/bindings/protocols/modbus/index.html#url should be **normative** IMHO.

As I already commented in the last main call, this is outside of the current WG charter.

**Comment by egekorkan** [comment]
@mlagally please see #1342
