### ISSUE TITLE
title must be mandatory for properties, actions and events

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#1338]
To build a basic URI for a thing that can be used by humans, it is important to render human readable labels for these interaction affordances.
These should be made mandatory, to avoid quirky workarounds, like using the internal ids (aka. names) of these affordances.

**Comment by sebastiankb** [comment]
I think this is a useful requirement when TD is mainly used for UI purposes. However, TD is also used for T2T interaction which such requirement is not needed. Maybe this would also conflict with constrained devices that have less memory.

As also mention in the past many times. Having title mandatory will not automatically solve your problem. What are you going to do when you have `"title" :""` or `"title": "t"` etc in the TD...

**Comment by relu91** [comment]
---> #1195  😃

**Comment by egekorkan** [comment]
I agree with @relu91 that this is more about recommendations/linting rather than making something mandatory. If something is mandatory, it means that a consumer should reject using an invalid TD. I don't think that title is such a case. As mentioned by @benfrancis in issues and PRs in profile, there can be simply fallbacks if there is no title and this should not stop a consumer from consuming a TD.

Technically, for user interfaces a title in the TD will not be enough when someone thinks about multi language support. Using proper semantic annotations is the way to go forward for having such support. 

There is also the RFC assertion style called RECOMMENDED that might be used here? https://datatracker.ietf.org/doc/html/rfc2119

**Comment by mlagally** [comment]
I think requiring to parse semantic annotations t odisplay a basic user interface is way to complex to implement in every consumer. This will introduce unnecessary complexity in many use cases.
Relying on some fallbacks is a quirky design. 
If the title is mandatory and a TD choses not to use it, it can provide an empty string.

**Comment by sebastiankb** [comment]
>  If the title is mandatory and a TD choses not to use it, it can provide an empty string.

I think we can agree that it's not really helpful to use that information to create human-readable labels. Why can't a UI application handle this the same way it handles an empty string when the title is not present. This costs me 3 lines of code.

**Comment by egekorkan** [comment]
Call of 20.04:
- There doesn't seem to more demand to make this mandatory
- Even in profiles, there is pushback
- This does not solve the problem of people putting empty strings 
- For UI applications, when there is no title, affordance name should be used as a fallback
