### ISSUE TITLE
Define few sibling classes or sub-classes in TD Ontology?

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#135]
Due to the new TD version there was also a redesign of the TD ontology. 

Currently the input/output vocabulary in Actions refer to the Property class. However, in Property class there are also vocabularies **observable**, **writable**, and **forms** that would not make sense for Actions. Is there a way to define a vocabulary restrictions from which context a class is used? Or should we define a separate ActionProperty class?

The same is also true for Event that should rely on the definition of the Property class. However, the **writable** and **observable** vocabulary does not make sense. Is there maybe a EventProperty needed?

**Comment by mkovatsc** [comment]
For some JSON-LD 1.0 compatibility of the TD, we probably should keep the `InteractionPattern` class as superclass of `ThingProperty`, `ThingAction`, and `ThingEvent`.

**Comment by mkovatsc** [comment]
@vcharpenay Can you please update the figure, so that ThingDescription is not mixed up with DataSchema? It is causing great confusion. It should just depict how DataSchema works.

A notion from the Binding call: For simplicity, the nested ThingProperty feature might be worth dropping.

Other issues:
* ThingProperty also has `forms`
* Superclass InteractionPattern missing

**Comment by sebastiankb** [comment]
An updated TD model can be found in the new TD version.
