### ISSUE TITLE
Removing MD5 from chapter 5.3.3.7

### ISSUE THREAD

**Issue by j1y3p4rk** [w3c/wot-thing-description#1362]
[MD5](https://en.wikipedia.org/wiki/MD5#:~:text=The%20MD5%20message%2Ddigest%20algorithm,a%20128%2Dbit%20hash%20value.&text=On%2031%20December%202008%2C%20the,and%20unsuitable%20for%20further%20use%22.) is broken long time ago and concluded as not suitable cryptographic algorithm. 
It would need to be removed from chapter 5.3.3.7 BearerSecurityScheme

**Comment by mmccool** [comment]
That is fine.  If it is already in TD 1.0 however it may create a backward compatibility issue.  To avoid that we could mark it as deprecated for TD 1.1 (and suggest it not be used for any future devices) and then remove it in TD 2.0.

**Comment by mmccool** [comment]
Although... one of the reasons we have this is to describe older APIs, without necessarily recommending its use for newer devices.  Taking it out would mean we would lose the ability to describe older things, at least not without adding an extension.  In general the "Security Best Practices" document is supposed to describe what should be used for new Things, and MD5 is not on that list.

**Comment by mmccool** [comment]
I'll add this issue to the agenda for the Security call.  The main point though it that it's not strictly a security issue, it's a question about how we handle "obsolete" features and backward compatibility.  We probably need some general way, within the TD spec itself, to indicate which options are not recommended for new work.

**Comment by mmccool** [comment]
Anyhow, I agree that we *at least* need a note stating that it is obsolete and is not recommended for new development.  This also however probably applies to a lot of other features currently in the spec.

**Comment by ashimura** [comment]
also, as I mentioned during the TD call on Jan-26:
* I agree we discuss this issue during the security call.
* We should discuss how to deal with this issue during the Wide Review as well.

**Comment by mmccool** [comment]
Certainly it should not be used in an example, since that implies it is a good practice.  Other than that we'll have to discuss further.

**Comment by mmccool** [comment]
I think I misunderstood something: by "example list" you meant the "e.g." list in the table in section 5.3.3.7 as opposed to a full example.  I don't believe it appears in a full example.  Taking it out of the "e.g." list is technically OK since this field is only a string and we don't *currently* mandate what values can be in there.  If we take it out, people can still put "MD5" in there if we want.  What we *probably* want to do (it was on my todo list somewhere but there is no time for it any more) is have a *specific* enumerated type listing a finite set of allowed vocabulary for this field, much as we have for other fields such as OAuth flows.  Then "deprecated" items could be supporting using extension vocabularies.  I would like to suggest we however table that for TD 2.0; doing it now would be troublesome.

Anyway, given the "e.g." not providing a normative complete list, I am personally ok with taking MD5 out, but to be on the safe side will confirm this proposal with the Security TF.

**Comment by mmccool** [comment]
Discussed in security call, and agreed to remove from e.g. list.  We also discussed that validators should probably issue a warning when deprecated standards such as this are used (actually, there are a whole list of insecure configurations that should be flagged, such as non-TLS HTTP with "password", but for now we can at least remove MD5 from the examples: I will make a PR).
