### ISSUE TITLE
ThingModel Placeholder limited to simple types

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#1399]
From the aspect of a ThingModel implementation I was wondering whether [placeholders](https://w3c.github.io/wot-thing-description/#thing-model-td-placeholder) can be of composed types also like `object` and/or `array`?

See example below

ThingModel

```
{
	"@context": ["https://www.w3.org/2022/wot/td/v1.1"], 
	"@type" : "tm:ThingModel",
	"version": "{{VERSION_INFO}}"
	...
}
```

Placeholder Map

```
{
	"VERSION_INFO": {"instance": "xyz", "model": "ABC"}
}
```

IF it is allowed shall we add such a simple example and make it clear in the spec.

**Comment by sebastiankb** [comment]
simple answer: yes :-)

**Comment by thjaeckle** [comment]
In my opinion it is a not so good idea to put "non-string" values (even numbers, integers, booleans) "temporarily" via the placeholder in a JSON string and later change the type again.
Because for the generator of the TD (resolving the placeholders) it gets very hard to decide in which JSON type the resolved placeholder should finally be added.

E.g. take the following property description - a property being either of type "string" or "boolean" with a "default" value defined by a placeholder "{{MY-FOO}}":
```json
{
  "foo": {
    "tile": "Some string or object",
    "oneOf": [
      {
        "type": "string"
      },
      {
        "type": "object",
        "properties": {
          "some": {
            "type": "boolean"
          }
        }
      }
    ],
   "default": "{{MY-FOO}}"
  }
}
```

Now assume the Placeholder Map:
```json
{
  "MY-FOO": "{\"some\": true}"
}
```

This would resolve to:
```json
{
  "foo": {
    "tile": "Some string or object",
    "oneOf": [
      {
        "type": "string"
      },
      {
        "type": "object",
        "properties": {
          "some": {
            "type": "boolean"
          }
        }
      }
    ],
   "default": "{\"some\": true}"
  }
}
```

Now - how shall the generator decide with which JSON type to apply this default value?
Json object or Json string?

The same problem also applies for numbers, integers, booleans, etc.

**Comment by sebastiankb** [comment]
from today's TD call:
- @thjaeckle you defined your map with a string. This will then also result as a string. When you use  a simple object definition that it will use the object definition in the TD
- there is a tool that follows the same procedure: https://www.npmjs.com/package/json-placeholder-replacer
- the text should be updated to make this more clear that the map value can be also an object

**Comment by thjaeckle** [comment]
@sebastiankb ok, thanks for the clarification - I really did not expect that the provider of the placeholder map should define the Json type to use.
But that should solve the typing issues I saw.

**Comment by sebastiankb** [comment]
merged
