### ISSUE TITLE
Simplify to no forms field on sub-properties?

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#140]
The Simplified TD allows for a recursive definition of Interaction Properties. The example shows a Property `status`, whose sub-property `battery` is also an Interaction Property that can be accessed directly:

```
  "properties": {
    "status": {
      "readOnly": true,
      "type": "object",
      "properties": {
        "battery": {
          "type": "number",
          "minimum": 0.0,
          "maximum": 100.0,
          "forms": [{
            "href": "/things/lamp/properties/status/batt",
            "mediaType": "application/json"
          }] 
        },
        "rssi": {
          "type": "number",
          "minimum": 0.0,
          "maximum": 1.0
        },
        "level": {
          "type": "integer",
          "minimum": 0,
          "maximum": 100
        }
      },
      "forms": [{
        "href": "/things/lamp/properties/status",
        "mediaType": "application/json"
      }]
    }
  }
```
While this allows for an efficient description of such structure, for instance found in OMA LWM2M and other existing platforms, it may not be intuitive enough -- as raised in Scripting and Binding call.

We could simplify and do not allow the `forms` field on sub-properties such as `battery` here. The functionality can still be described in a more verbose way:

```
  "properties": {
    "status": {
      "readOnly": true,
      "type": "object",
      "properties": {
        "battery": {
          "type": "number",
          "minimum": 0.0,
          "maximum": 100.0
        },
        "rssi": {
          "type": "number",
          "minimum": 0.0,
          "maximum": 1.0
        },
        "level": {
          "type": "integer",
          "minimum": 0,
          "maximum": 100
        }
      },
      "forms": [{
        "href": "/things/lamp/properties/status",
        "mediaType": "application/json"
      }]
    },
    "battery": {
      "type": "number",
      "minimum": 0.0,
      "maximum": 100.0,
      "forms": [{
        "href": "/things/lamp/properties/status/batt",
        "mediaType": "application/json"
      }]
    }
  }
```
Any comments?

**Comment by ToruKawaguchi** [comment]
I agree to make it simple as possible. 

By the way, my understanding to this two-level "properties" was that both level has different meaning, i.e.) first-level "properties" is used to describe an "interaction pattern" and  second-level "properties" is used  to describe "members of an object" (formally named as "fields" in FPWD; changed to "properties" to align with JSON Schema vocabulary) , thus not "recursive". 

If this is "recursive", does three or more level "properties" are allowed ? I'm afraid that it makes practical implementation and testing difficult....

Please correct me if I am missing something.

**Comment by mkovatsc** [comment]
@ToruKawaguchi Multiple levels are allowed, as exchanged JSON data can be arbitrarily complex. A LWM2M Object, for instance, has up to three sub-levels that are received when reading at the Object level (Object Instance, Resource, Resource Instance). Practically, such recursive structures are quite easy to validate and with the changes, you can also use existing JSON Schema validators (or soon to exist in the targeted RFC version...)

Thing properties (the exposed data) and JSON Schema properties have the same meaning in the sense that they describe data schemas. Once such a property has a `forms` field, it becomes interactable (an Interaction Property). The simplification would be to only allow the `forms` field at the first level. We then duplicate some data schema properties, but we have a flat list of Interaction Properties, which is easy to process.

**Comment by zolkis** [comment]
Or we should make separate definitions for interaction related and schema related structures.

Do we have this problem only with properties?
We could define ObjectProperty (used recursively) and Property as interaction that extends ObjectProperty with `forms`.
Where interactions need to be used recursively then there we could (re)use a Thing definition.

Unrelated, but do we use `forms` for bindings information? If so, it would be so much more clear to use `bindings` as a name instead of the too generic `forms`.

**Comment by mkovatsc** [comment]
We do have separate definitions. It just turned out that Properties are properties and instances can implement both RDF types. We could add a technically unnecessary indirection step, which would need to either rename the Property Interaction Pattern to something else and confuse a lot of people or break JSON Schema compatibility.

I actually do not understand what problem we have. What is the problem with Properties?

`bindings` was one of the options when we were discussing the renaming. There was no support back then and `forms` was agreed on without any objections. Please open a separate issue or re-open https://github.com/w3c/wot-binding-templates/issues/29#issuecomment-366661075.

**Comment by sebastiankb** [comment]
I think, in IoT it make sense to avoid such verbosity and provide mechanism to allow the retrieving of data values that match quite well to client's needs. 

Lets assume there is WoT servient that offers sampled weather data of a location by a single WoT Property. This property contains temperature value, humidity value, time stamp, etc as a complex structure.  A client, however, is interested only in the temperature value. This it would be great when the client can directly subscribe the temperature value without parsing all not needed data (e.g., humidity value) to reduce processing overhead and network bandwidth.

What we can also think about is the implicit assumption of this approach: We have only form on the top level of the property. Nested defined data values will be addressed by the property name such as /things/lamp/properties/status/battery. What do you think?

**Comment by mkovatsc** [comment]
What you are describing with the weather data is not a limitation of the TD. It is up to the Thing to implement this fine-grained access.

The question for the TD is if we want an optimized representation of fine-grained access to nested properties. The optimization of having `forms` at any level decreases verbosity in the description (not runtime data!), but increases complexity. I hope the main concern here is this complexity.

I strongly advice against implicit URI construction, as this is a specific case and not suitable for a generic description mechanism.

**Comment by mkovatsc** [comment]
An example to think about a separation of Interaction Property (now renamed) and data schema property:
```
  "datapoints": {
    "status": {
      "writable": false,
      "observable": true,
      "schema": {
        "type": "object",
        "properties": {
          "battery": {
            "type": "number",
            "minimum": 0.0,
            "maximum": 100.0
          },
          "rssi": {
            "type": "number",
            "minimum": 0.0,
            "maximum": 1.0
          },
          "level": {
            "type": "integer",
            "minimum": 0,
            "maximum": 100
          }
        }
      },
      "forms": [{
        "href": "/things/lamp/properties/status",
        "mediaType": "application/json"
      }]
    },
    "battery": {
      "writable": false,
      "observable": true,
      "schema": {
        "type": "number",
        "minimum": 0.0,
        "maximum": 100.0
      },
      "forms": [{
        "href": "/things/lamp/properties/status/batt",
        "mediaType": "application/json"
      }]
    }
  }
```

Bonus point: we are one step closer to oneM2M.

**Big drawback**: giving semantic meaning becomes cumbersome and confusing. A datapoint, for instance of `@type` `"iot:BatteryLevel"`, could not be equivalent to a sub-property that having the same data, same schema, same semantic meaning, just because we made them artificially different.

For above example, this means, I cannot put `@type` `"iot:BatteryLevel"` for the Datapoint `battery` and the sub-property `battery` in `status`, although they expose the very same state. I would have to put `@type` `"iot:BatteryLevel"` into the `schema` of Datapoint `battery` and invent something else for Datapoint `battery` itself...

**Comment by ToruKawaguchi** [comment]
@mkovatsc , so following understanding is correct ? if so I do not have strong objection:  
-  (interaction) property and (object) property has different definitions  
 (maybe description of "properties" in 5.2.2 "properties" of current editors draft need to be modified, as @mlagally already pointed out in #133 ..)
- only (object) property may be recursive to represent complex object structure as in JSON schema

Of course It would be ideal if two entities with different definitions has two distinct names, but looking at your example above with the name "datapoints" instead of (interaction) properties, I have to say that I would agree with you that removing the term "property/ies" from here would cause confusion (or is it too verbose to change interaction terms to thingProperties, thingActions and thingEvents ?) 

> For above example, this means, I cannot put @type "iot:BatteryLevel" for the Datapoint battery and the sub-property battery in status, although they expose the very same state. I would have to put @type "iot:BatteryLevel" into the schema of Datapoint battery and invent something else for Datapoint battery itself...

Maybe I should be missing something, but I could not catch why this can not be made. Do you mean we can not put multiple @type in different level of the structure, or we can not put the same "iot:BatteryLevel" into @type in different level ?  I would be appreciated if you could explain what makes this difficult.

**Comment by mkovatsc** [comment]
> * only (object) property may be recursive to represent complex object structure as in JSON schema

Yes, this is the original proposal here -- no `forms` field on sub-properties means they are "object properties", not "Interaction Properties".

> * (interaction) property and (object) property has different definitions (maybe description of "properties" in 5.2.2 "properties" of current editors draft need to be modified, as @mlagally already pointed out in #133 ..)

In RDF, instances (like an entry in the `properties` object of a TD) can implement multiple classes (here `ThingProperty` and `DataSchema`). The `ThingProperty` class defines an "Interaction Property". The `DataSchema` class defines an "object property" (actually can also be an array or one of the simple data types). So there are two different definitions. The fact that an instance or Linked Data node can have two definitions at the same time helps with the last issue:

> Maybe I should be missing something, but I could not catch why this can not be made. Do you mean we can not put multiple @type in different level of the structure, or we can not put the same "iot:BatteryLevel" into @type in different level ? I would be appreciated if you could explain what makes this difficult.

If we use `datapoints` with a `ThingDatapoint` class as definition, which has the field `schema` with the `DataSchema` class as its definition (see example above), then we cannot give it the same `@type` as a sub-property that is directly of type `DataSchema`. In the exmaple, `iot:BatteryLevel` would be a sub-class of `DataSchema`. It would be a conflict to also make it a sub-class of `ThingDatapoint`, as that has `DataSchema` as field ("RDF property").

@vcharpenay, @mariapoveda Options, corrections?

**Comment by vcharpenay** [comment]
> If we use datapoints with a ThingDatapoint class as definition, which has the field schema with the DataSchema class as its definition (see example above), then we cannot give it the same @type as a sub-property that is directly of type DataSchema.

In the case of `iotschema.org`, it would indeed not be possible because the terms this vocabulary defines (`iot:BatteryLevel`) directly specialize TD terms (`DataSchema`). However, there also was the idea of defining domain-specific terms in an abstract fashion so that they could be reused as different levels in a TD, as a sort of semantic tagging. I guess this is the view @ToruKawaguchi is expressing here. But it is not the modeling choice that has been made in `iotschema.org` (as far as I know).

**Comment by mkovatsc** [comment]
Having this tagging approach then leaves you at the level where you just know there is something that you are interested in, but leaves it open how to get it.

We could also define matching classes, one for ThingDatapoint and one for DataSchema. Yet this is redundand and makes modeling more complex. And I still don't understand what problem it would be solving.

**Comment by ToruKawaguchi** [comment]
@mkovatsc @vcharpenay , thank you very much for your explanation. I understood that each iotschema.org term is bound to particular TD term, and this is the reason to re-use the same TD term at different level.

**Comment by mariapoveda** [comment]
In general I'm not sure about using (object) properties and (interaction) property for recursive definitions. This patterns are usually defined using the same type of concept. Using different concepts would not be recursive as @ToruKawaguchi mentioned.

Regarding:

> If we use datapoints with a ThingDatapoint class as definition, which has the field schema with the DataSchema class as its definition (see example above), then we cannot give it the same @type as a sub-property that is directly of type DataSchema. In the exmaple, iot:BatteryLevel would be a sub-class of DataSchema. It would be a conflict to also make it a sub-class of ThingDatapoint, as that has DataSchema as field ("RDF property").

I can't find the datapoints and thingDatapoint definition. In which branch it is being defined?

**Comment by mkovatsc** [comment]
The `datapoints` term is so far only a made-up term to make it clear to people that the top-level Property node would have a different class with different semantics IF we revert to having the `schema` field.

About recursiveness when NOT having the different structure with `schema` term: all nodes starting from the top level would implement the DataSchema class. Because the top-level node is the entry point, it would ALSO implement the ThingProperty class, adding the `forms` and other terms. My expectation would have been that this can also express that the node pointing with `properties` to a node with class ThingProperty (a Thing node) is not a DataSchema itself.

**Comment by sebastiankb** [comment]
Just for information: I just updated the TD core model figure and added the new data schema model as figure in [section 5.1](https://w3c.github.io/wot-thing-description/#overview). 

Any feedback is welcome.

**Comment by mjkoster** [comment]
Based on the discussion we had in the protocol binding meeting of June 12th, I believe one goal is to make the TD Property interaction directly interact-able as data. Essentially this means to define a TD Property as both an interaction and as data. 

This is a bit different from recursion, is more like multiple inheritance.

This means that an instance of a property in TD might have iotschema annotations for both interaction and data. This is perfectly OK for the way things are defined and meant to be used in iotschema, and is similar to the pattern we will need to use for direct iotschema annotation of LWM2M objects.

This can inform a sensible conclusion to the TD ontology debate, which I will make references to from here.

**Comment by mjkoster** [comment]
I will comment on my previous comment rather than editing it.

It seems like we don't prohibit an Interaction Property from having more than one data item (schema property) as in the example above. In this case, the Interaction Property has the semantics of a Schema Object rather than a Schema Property. Both of these are JSON Schema instances so it seems like we want Property to somehow be interact-able as a Schema Instance.

I don't think we need to define Interaction Property as a subclass of dataschema to achieve this; I think a dotted line relation as is the case with Action and Event will allow for direct interaction with the resource.

**Comment by mariapoveda** [comment]
> In the current ontology, there is no direct relation between Property and DataSchema. The only way readers can understand there is one is by reading Section 6, which uses schema definition terms for an instance of Property. Making this relation explicit in terms of ontology axioms is probably better in the long term.

Which property should be better having? An ad-hoc one or subclassOf? I don't see the subclassOf in the owl code but it is in the model picture. My point of view about this:

Not having a subclassOf between Property and DataFragment/Schema does not prevent anyone from having an instance that is both type Property and type DataFragment, so that your case is covered (unless such classes are disjoint which are not). Making the subclasOf explicit in the model seems wrong in two ways:
1) it is conceptually questionable
2) it makes the model too restrictive and might prevent other people to use it

I think the best way it not to put that subclassOf as what you need to model is still possible (and should be explained with examples), will not incur in modelling mistakes and it would be more general  by no imposing such strong assumptions.

**Comment by vcharpenay** [comment]
> 1. it is conceptually questionable

If the model were questionable, so would be a TD instance that mixes the two class definitions. The W3C document is defined in a way that all instances of `Property` will also be instances of `DataFragment`(*). It is important, precisely because there is a conceptual difference, not to mix individuals (data fragments) with reusable definitions that apply to several individuals (data schema). Thing properties are individual properties, while action input/output are schema definitions that must apply to any action invocation. They should therefore be of a different RDF type. Having a union class (`DataFragmentOrSchema`) is merely for the sake of convenience, to avoid duplicating axioms shared between individuals and schema.

> 2. it makes the model too restrictive and might prevent other people to use it

Having two modules ('core' and 'schema') would solve this problem, as I explain in my comment above. Users who would like to use the TD vocabulary outside of the scope of what W3C recommendations specify could simply extend the 'core' and discard 'schema'. It is compatible with your work on [Vicinity](http://vicinity.iot.linkeddata.es/vicinity/index.html), where you define your own schema module on top of the TD core.

(*) the terminology is not fixed, 'fragment' is a proposed term but probably not the definitive one.

**Comment by mariapoveda** [comment]
> If the model were questionable, so would be a TD instance that mixes the two class definitions.

I don't see why, that is perfectly valid as long as they are not disjoint. It is more questionable to force a hierarchy.

Regarding the second point, it still prevent people to reuse the schema module. And for the records, I'm not just thinking about vicinity project, where we can actually make our own model and link the common points, but others that might not be involved in the discussion and might want to reuse the model in the future.

**Comment by mkovatsc** [comment]
The original issue was addressed (sub-properties will not have forms). Since this issue has been silent for a while, I will close it.

@mariapoveda , @vcharpenay We also sorted out the issues about the ontology. My understanding is that Maria advocates to make the relation of Property instances (as well as input/output instances) to the DataSchema optional, so that there is no conflict when the instances implement a different data schema class. Is this correct?

Since there have been several changes, I suggest to re-evaluate the current situation (new Working Draft should be out soon) and open a new Issue more concretely on this. (Also see https://github.com/w3c/wot-thing-description/issues/223)

**Comment by mariapoveda** [comment]
>  My understanding is that Maria advocates to make the relation of Property instances (as well as input/output instances) to the DataSchema optional, so that there is no conflict when the instances implement a different data schema class. Is this correct?

If that means that a property might be a DataSchema but not imposed by the model, it is.
