### ISSUE TITLE
Default values of `readOnly` and `writeOnly` for non-property affordances

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1417]
Should `readOnly` and `writeOnly` have default values when they are used in any data schema or only in Property affordances? Currently we have the following:
![image](https://user-images.githubusercontent.com/20195407/156340131-32ab6566-ea11-45aa-8f48-9ef8be962af9.png)

This means that actually an action input also has `readOnly` and `writeOnly` when the TD is expanded to include defaults. I find this really strange and think that the defaults should be limited to only property affordances

**Comment by JKRhb** [comment]
Would it also make sense (for TD 2.0) to only define `readOnly`/`writeOnly`[^1] for properties in general? An action output that is `writeOnly`, for example, is probably also a bit counterintuitive.

[^1]: Or `readable`/`writable`...

**Comment by danielpeintner** [comment]
I don't like the terms either but I guess we need to remember why we have them in the first place.

We tried to be aligned as much as we wan with JSON schema. JSON Schema has ["readOnly" and "writeOnly"](https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.9.4).

Having said that, IF we remove it from DataSchema it is somehow deviating from the original idea... even though I understand it might sound silly to have `readOnly` for an action output.

**Comment by egekorkan** [comment]
I think having the term or not is a separate discussion but defining the default values is something we have done anyway

**Comment by JKRhb** [comment]
> I think having the term or not is a separate discussion but defining the default values is something we have done anyway

Sorry for going a bit off track here 😅

There is a similar problem with default values in the `SecuritySchemes` (related to #1394) and there it seems as if the default cannot be changed if backwards compatibility is desired. I think it is a general question if default values can be changed in TD 1.1 if they do not make sense or are probably not used anyway. Otherwise I think this whole issue would need to be deferred to TD 2.0.

**Comment by benfrancis** [comment]
Given it's not really clear what a `readOnly`/`writeOnly` action or event actually is, I think it makes sense for this member to only apply to `PropertyAffordance`. You could argue that all events are read-only and all actions are writeable by their nature, in which case these terms and defaults already don't make sense. Also we use the terms subscribe/unsubscribe and invoke/query rather than read/write for action and event operations.

It seems unlikely that this change would cause backwards compatibility problems in practice, but it is technically possible.
