### ISSUE TITLE
Metadata fields in Thing (mandatory and optional)

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#142]
(updated after some terms found consensus)

https://w3c.github.io/wot-thing-description/#thing currently says all fields are optional, probably due to work in progress. However, we should still finish the discussion which fields must be mandatory.

Mandatory:
* `id`
* `security` -- to make a no-security choice explicit (`nosec` scheme) and warn if no security considerations were taken (warn, not fully reject)

Possibly mandatory
* `name` -- UIs could fall back to the `id`, though
* `description` -- @mlagally argued for proper documentation and data quality it should be mandatory
* `support` -- @mlagally argued for proper documentation and data quality it should be mandatory

Optional
* `@context` -- semantic annoations are optional, so there might be no domain-specific vocabularies
* `@type` -- semantic annoations are optional
* `base` -- is just an optimization
* `properties` -- there might be no Properties
* `actions` -- there might be no Actions
* `events` -- there might be no Events
* `links` -- there might be no Web links

BTW: `@context` and `@type` are missing completely in the draft.

**Comment by mlagally** [comment]
Suggest to also introduce the following properties to further improve the documentation:

 -     version : string
 -	created : number  /* time in milliseconds since 01 January, 1970 UTC */
 -  	createdAsString : js_date
 -  	lastModified : number  /* time in milliseconds since 01 January, 1970 UTC */
 -   	lastModifiedAsString : js_date 
 -   	userLastModified : string
        
js_date is  a valid ECMAScript date as defined in chapter '20.3.1.16 Date Time String Format' of http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf

**Comment by mkovatsc** [comment]
I would prefer the string datetime(stamp) as default representation. As I understand it, ISO 8601 is also used in Linked Data representation: https://www.w3.org/TR/xmlschema11-2/#dateTimeStamp from https://www.w3.org/TR/rdf11-concepts/

**Comment by mlagally** [comment]
@mkovatsc ISO 8601 permits *a lot* of format variants, e.g. basic format, extended format, which might be an overkill for our purpose and would require all TD consumers to implement the full parsing.
(See http://www.loc.gov/standards/datetime/iso-tc154-wg5_n0038_iso_wd_8601-1_2016-02-16.pdf)

The Javascript date defines only a subset, which I believe is more appropriate here:

(Excerpt from: https://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf)

20.3.1.15 Date Time String Format
ECMAScript defines a string interchange format for date-times based upon a simplification of the ISO 8601 Extended Format. The format is as follows: YYYY-MM-DDTHH:mm:ss.sssZ
Where the fields are as follows:
YYYY is the decimal digits of the year 0000 to 9999 in the proleptic Gregorian calendar. - "-" (hyphen) appears literally twice in the string.
MM is the month of the year from 01 (January) to 12 (December).
DD is the day of the month from 01 to 31.
T "T" appears literally in the string, to indicate the beginning of the time element.
HH is the number of complete hours that have passed since midnight as two decimal digits from 00 to 24. : ":" (colon) appears literally twice in the string.
mm is the number of complete minutes since the start of the hour as two decimal digits from 00 to 59.
ss is the number of complete seconds since the start of the minute as two decimal digits from 00 to 59.
. "." (dot) appears literally in the string.
sss is the number of complete milliseconds since the start of the second as three decimal digits.
Z is the time zone offset specified as "Z" (for UTC) or either "+" or "-" followed by a time expression
HH:mm

**Comment by mkovatsc** [comment]
@sebastiankb Can you post a summary of the `version` field you worked on? ("semantic versioning")

**Comment by mkovatsc** [comment]
* `serial` -- a serial number as standalone field might be useful, even when it is part of `id` (e.g., in a [dev URN](https://tools.ietf.org/html/draft-ietf-core-dev-urn))

**Comment by sebastiankb** [comment]
the new TD term `version ` is compiled in the TD Lyon version: https://htmlpreview.github.io/?https://github.com/w3c/wot-thing-description/blob/td4lyon/index.html

During f2f we should discuss if this version container can be used for the mentioned new terms and if the name "version" have to be renamed to a more generic word that represents td version, created, etc.

**Comment by sebastiankb** [comment]
terms `created `and `lastModified ` are compilied in the TD core model. 
Usage in requirement definition still missing in Section 6

**Comment by takuki** [comment]
W3C also has a Note called [W3CDTF](https://www.w3.org/TR/NOTE-datetime) describing a profile that "defines a few date/time formats, likely to satisfy most requirements." LastModified and edition numbers are closely related, and both can be used for retrieving a version of resources, so it may be worthwhile to put them in proximity in TD.

**Comment by takuki** [comment]
As for serial numbers, GS1 uses GTIN plus serial number to uniquely identify a specific instance of a product. See the below slides from [here](https://www.gs1.org/sites/default/files/docs/addisababa/PresentationDay2/20180501_Addis_Day%202_Panel%202__The%20Basics%20of%20Identification%20and%20Barcoding%20for%20Traceability%20_FINAL.pdf).
![20180501_addis_day 2_panel 2__the basics of identification and barcoding for traceability _final_25](https://user-images.githubusercontent.com/12631135/47621217-e6bcce80-dab1-11e8-9a89-72301e2c555b.jpg)
![20180501_addis_day 2_panel 2__the basics of identification and barcoding for traceability _final_18](https://user-images.githubusercontent.com/12631135/47621219-ecb2af80-dab1-11e8-99bc-24d3f5d68046.jpg)

**Comment by takuki** [comment]
schema.org and GS1 are [collaborating](http://blog.schema.org/2016/02/gs1-milestone-first-schemaorg-external.html) on an external extension, and initial release of their vocabulary is published [here](https://www.gs1.org/voc/).
