### ISSUE TITLE
ComboSecurityScheme: oneOf and allOf can be strings according to vocab table

### ISSUE THREAD

**Issue by FadySalama** [w3c/wot-thing-description#1438]
The vocab table under [ComboSecurityScheme](https://w3c.github.io/wot-thing-description/#combosecurityscheme) states that `"oneOf"` and `"allOf"` can be either of type `string` or `Array of string` but their descriptions state specifically that both should be arrays containing at least 2 strings. This might cause confusion

**Comment by egekorkan** [comment]
This specific one should say that it must be an array

**Comment by egekorkan** [comment]
The td-validation.ttl is correct (at least we think so) since it has `minCount 2` at https://github.com/w3c/wot-thing-description/blob/5080f00af839c6dae1c567b6a6f8a4599db4b248/validation/td-validation.ttl#L2171.

We need to understand how `oneOf` and `enum` in DataSchema is done, since they have the correct type:
![image](https://user-images.githubusercontent.com/20195407/173872084-d219be5a-96d9-4bc6-94a9-e30fbe9c88ec.png)

**Comment by mmccool** [comment]
Agree with closing issue if the problem has been resolved.

**Comment by egekorkan** [comment]
Can be closed as indicated.
