### ISSUE TITLE
Identifiers don't seem to rotate enough

### ISSUE THREAD

**Issue by jyasskin** [w3c/wot-thing-description#1497]
I was listening to the PING review of this spec today, and apologies if I haven't understood the space deeply enough to make a good contribution. I noticed that https://www.w3.org/TR/wot-thing-description11/#sec-privacy-consideration-id describes even the mutable IDs as rotating rarely:

> In many circumstances it will be acceptable to only allow updates to identifiers if a [Thing](https://www.w3.org/TR/wot-thing-description11/#dfn-thing) is reinitialized.

Since things are reinitialized rarely, that's not really enough to prevent tracking. I was reminded of a change modern operating systems made to MAC addresses, where for most networks they rotate the MAC address fairly often. Of course, this makes it impossible for a user to recognize a device when they come back to it. Bluetooth has ["Resolvable Private Addresses"](http://lpccs-docs.dialog-semiconductor.com/Tutorial-DA145x-BLE-Security/privacy.html) to handle this, and something like that might be a good thing to explore for Things. This would require only exposing the long-term ID to devices that are paired in some way, rather than including it in the [`id` field](https://www.w3.org/TR/wot-thing-description11/#td-vocab-id--Thing) of the Thing description.

**Comment by mmccool** [comment]
WIP: Still thinking about this, please give me a bit more time to clean up my comments before taking them too seriously :)

We discussed this today in the WoT Security TF and also reviewed the existing S&P considerations.  Some thoughts for improving the TD S&P considerations follow (more specific actionable 
- Explicitly mentioning and citing UUIDv4 when "random UUIDs" are mentioned (note: some of the examples do not follow this advice and I would personally like to see them updated)
- Adding an assertion that IDs MUST be changed when a device is offboarded and onboarded on a new system (e.g. for change of ownership). 
- Add some discussion that "If possible and allowed by law, required immutable IDs SHOULD be made available through a property rather than used as the id for the TD itself"

Here are some use cases that can lead to tracking:
- I have a keyfob that has various buttons on it to control IoT devices (I do actually; Fibaro makes one)
- This is usually going to be on my person, so the network it connects to gives a hint to my location
- In particular, if it is NOT available on the network, I'm probably not home

In general we were thinking about portable devices that can give away actual geophysical location.   

That's location tracking.  The other meaning of "tracking" on the web though is one website harvesting information about me without my knowledge, e.g. my shopping habits on other websites.  So one issue here might be the cross-over between websites and IoT devices, i.e. a website able to gather information about my IoT usage and vice-versa.  So IoT devices, if they are sharing the same protocol space, browsers, etc. as web sites, should have similar protections against tracking.  However, note that ids here relate to Things, which are analogs to *web sites*, not browsers.  An ID on a Thing does not allow the browser to be tracked, if "reasonable practices" (the same ones you would want to use to avoid tracking between web sites) are followed.

**Comment by benfrancis** [comment]
@mmccool wrote:
> I have a keyfob that has various buttons on it to control IoT devices (I do actually; Fibaro makes one)
> This is usually going to be on my person
> It can only connect to my home network but...
> If it is NOT available on the network, I'm probably not home

The Fibaro key fob is a great example of where the mutable identifier mitigation won't make any difference. As I understand it Fibaro key fobs use either Z-Wave or Homekit/Bluetooth to connect to a network (we support similar devices on the WebThings platform using Zigbee, Z-Wave and HomeKit). That means they require a gateway to bridge them to the Web of Things and assign an identifier used in a Thing Description.

If you take that device outside of the range of one of those PAN networks in your home, it won't be able to connect to another network, let alone the Internet. The only users who can access information about whether a physical device associated with a particular web thing ID is present on the PAN network in your home are users who are authorised to access the Thing Description for that device (hosted on a home gateway) and an API endpoint which exposes that information.

Web thing IDs are not like MAC addresses on Wi-Fi devices which are broadcast to every other device on every public Wi-Fi network it connects to and can therefore be sniffed by anyone else on that network, or cookies which are sent to every website you visit. They are only available to WoT Consumers which are authorised to access the Thing Description, which is usually transferred via an encrypted connection over the internet. At least, that's the case for our implementation in WebThings. As I say, maybe there are other use cases I haven't thought of, but this isn't one of them.

I can imagine a scenario where a device which is broadcasting the URL of its Thing Description using a [Bluetooth beacon](https://w3c.github.io/wot-discovery/#introduction-direct) or [DNS-SD](https://w3c.github.io/wot-discovery/#introduction-dns-sd) moves between physical spaces or Wi-Fi networks and other users in its proximity would know that a web thing with a certain URL is nearby. But in that case it's the URL of the Thing Description, not its ID member, which is identifiable. Plus if it's a portable personal device it probably wouldn't be using one of those broadcast mechanisms in the first place unless its owner wanted it to be found.

> if the keyfob is smart enough to log onto a 4G network and access my house remotely, then it could be used to track my location even away from home

Possibly, but not via its web thing ID. If you're worried about your mobile carrier triangulating the location of your device and sharing that information with others then that's an entirely separate problem which has nothing to do with the Web of Things.

> IDs here relate to Things, which are analogs to web sites, not browsers. An ID on a Thing does not allow the browser to be tracked, if "reasonable practices" (the same ones you would want to use to avoid tracking between web sites) are followed.

I think this is the key point, and possibly a source of confusion in privacy & security reviews. WoT is not like many other W3C specifications which describe client-side JavaScript APIs running in the context of a web browser, it's more analogous to websites hosted on a web server. Nobody is suggesting that web pages should regularly rotate their URIs in order to improve the privacy of the users who access them, even for web pages which relate to an individual user.

I understand you're still refining these examples, but I think this risk needs further analysis before any useful mitigations (if any are necessary) can be recommended.

**Comment by mlagally** [comment]
IMHO there are different aspects in this discussion of traceability that should be distinguished:

1. Tracking of users
From my understanding this is the biggest privacy problem in the browser world, where significant business interests lead to attempts to track anonymous users (e.g. cookies) 
There are good reasons to prevent that. 

2. Tracking of devices 
For many monitoring use cases it is absolutely required to identify a device to make the use case work. How would a smart heating system of a building work, if the temperature sensors could not be individually identified and mapped to a room.

3. Tracking of personal devices
This is an in between scenario, with significant privacy requirements.  In this case all PII needs to be protected from unauthorized access.

**Comment by sebastiankb** [comment]
from today's TD call:
- @mmccool will discuss issue in the next WoT S&P call
-  @mmccool will provide PR about some strategies how to handle the IDs for specific scenarios

**Comment by mmccool** [comment]
Notes from Security call on May 23:
- Definitions of tracking: Two major definitions: (1) determining location; (2) observing behavior (e.g. browsing history)
- Consensus that we should add a MUST assertion to delete IDs when offboarded and assign a new one when onboarding.
- Offboarding should *ideally* should also result in reinitialization and deletion of configuration information from the previous owner, for instance, WiFi passwords, etc.  However, this is beyond the scope of the TD specification.  We can mention but can't make an assertion.  Dealing with onboarding/offboarding more normatively is a possibility for our next charter.
- Any *required* immutable IDs SHOULD only be made available via properties (which can be secured using authentication mechanisms) and MUST not be used for TD ids.

**Comment by benfrancis** [comment]
> * Definitions of tracking: Two major definitions: (1) determining location; (2) observing behavior (e.g. browsing history)

It would be great to include an explanation of _how_ immutable IDs inside a Thing Description could lead to either of these types of tracking, because neither is currently clear to me.

> * Consensus that we should add a MUST assertion to delete IDs when offboarded and assign a new one when onboarding.

What is the definition of "onboarding"/"offboarding" in this context? There are three conflicting non-normative definitions of onboarding I can find:
1. In section [6.3.4.5 API key usage](https://w3c.github.io/wot-thing-description/#security-apikey) of WoT Thing Description 1.1, in reference to requesting API keys "_A Thing can require an onboarding process that results in the Consumer requiring an API key to interact with the Thing._" Would the ID therefore have to be changed every time a Consumer requests an API key? How would other Consumers be notified of the change in ID?
2. In section [8.4.1 Simple System Lifecycle](https://w3c.github.io/wot-architecture/#simple-system-lifecycle) of WoT Architecture 1.1 _"In the onboarding operation the consumer and the device get to know each other - this may either be performed by a discovery process, or via a registration operation, where the consumer is registered with the device or vice-versa."_ Would the ID have to be changed every time a new Consumer discovers the Thing?
3. In section [8.4.3 Thing Lifecycle](https://w3c.github.io/wot-architecture/#thing-lifecycle) of WoT Architecture 1.1 "_the device is provisioned with an identity, the chain of trust is established, e.g. secure storage, keys, certificates. This may involve various solutions, such as manufacturer certificates, out-of-band key provisioning, connecting to a provisioning server (a quite common scenario). When provisioning directly to WoT, the device may be registered with a [Thing Description Directory](https://w3c.github.io/wot-architecture/#dfn-wot-thing-description-directory) in this stage._" Would a new ID have to be assigned every time a Thing is added to a Directory? What happens if it is added to multiple Directories? How would existing Consumers be notified of the change?

I can't find a definition of "offboarding".

Presumably the proposed assertion would require a normative definition of these terms.

> Any required immutable IDs SHOULD only be made available via properties (which can be secured using authentication mechanisms) and MUST not be used for TD ids.

Would it be sufficient to secure the TD instead?

Implementing ID rotation in WebThings Gateway would be very tricky because IDs are currently generated by individual add-on adapters, of which there are many created by many different authors. I'd therefore like to better understand the risk that is being mitigated which justifies this change from Thing Description 1.0. The obvious solution would be to just remove IDs from Thing Descriptions altogether given `id` is currently an optional member, but there is [discussion](https://github.com/w3c/wot-profile/issues/139) about making `id` mandatory for HTTP profiles.

**Comment by mmccool** [comment]
We unfortunately had to end the Security call before we could fully discuss this but we will pick up the discussion next week.

**Comment by mmccool** [comment]
OK, working on a PR attempting to address this point, see https://github.com/w3c/wot-thing-description/pull/1547
See also [Discovery PR #353](https://github.com/w3c/wot-discovery/pull/353), which is addressing some related points.

The content of this and the PR in discovery is based on some discussions we had in the Security TF to address this issue and [Issue 303 in Discovery](https://github.com/w3c/wot-discovery/issues/303).

**Comment by mmccool** [comment]
The Security TF feels this issue has been resolved by the above PRs so I have marked this as Proposed Closing.  If we don't hear otherwise I suggest it can be closed in the Aug 3 TD call.

**Comment by egekorkan** [comment]
Call of 30.11: We will close this issue since it is resolved. It can be reopened if needed. The label privacy-needs-resolution can be removed.
