### ISSUE TITLE
Update JSON Schema validation reference

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#1513]
The JSON-Schema validation reference in the TD spec is rather outdated,
suggest to use the most recent:
https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00

**Comment by egekorkan** [comment]
We cannot use the most recent as of now, we stick to draft v7 in TD since it is the most implemented one and there are breaking changes in the upcoming versions. However, we are not referencing to v7 but to v1, which is wrong. The screenshot below needs fixing:
![image](https://user-images.githubusercontent.com/20195407/170249716-cf913bb6-4875-4373-88af-7b3f92ffc059.png)

**Comment by JKRhb** [comment]
The naming conventions for JSON schema specifications are a bit confusing in my opinion, if I am not mistaken, the cited [draft-handrews-json-schema-01](https://tools.ietf.org/html/draft-handrews-json-schema-01) is actually Draft 7 (c.f. https://json-schema.org/specification-links.html#draft-7).

**Comment by sebastiankb** [comment]
from today's TD call:
- it turned out that TD uses the most common JSON Schema Version (https://json-schema.org/specification-links.html#draft-7) which many tools support
- also the references in the TD spec are correct
- group decided to stick with this version for now
