### ISSUE TITLE
Distinguish "JSON Schema" and "JSON Schema Validation" references

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#1514]
The TD spec currently references _JSON Schema Validation_ only. 
The current link is outdated, see also #1513, however there's no 
_JSON Schema_ reference at all.

Is this intentional?

**Comment by mlagally** [comment]
See also: https://github.com/w3c/wot-profile/issues/179

**Comment by egekorkan** [comment]
I think validation is enough. If you look at https://json-schema.org/specification.html you can see that there are 3 specifications. The core specification is about defining what a json schema is and some "generic" keywords like `$ref` etc. The validation spec is actually what defines the meaning of the keywords that they are using.

**Comment by mlagally** [comment]
@egekorkan The core specification has *a lot* of normative constraints.
The validation specification builds on top of the core, it references it in a few places.
The core specification is defining the actual JSON notation format and should be normatively referenced.

**Comment by egekorkan** [comment]
We cannot normatively reference JSON Schema though, it is not a standard by an SDO. TD spec has nothing to do with JSON Schema core, only uses the words in the JSON Schema validation and TD does not build on top of JSON Schema since it is not a standard. We are only informatively hinting that the DataSchema is inspired by JSON Schema.
