### ISSUE TITLE
OneM2M request to set a attribute 

### ISSUE THREAD

**Issue by fabriceblache** [w3c/wot-thing-description#154]
Hi everybody 

We use OneM2M with Eclipse oM2M implementation.
We have a simple SDT (Smart Device Template) module "binarySwitch" with "powSe" attribute who indicate the state "on" or "off"

To set this attribute we do this request with payload json and a response in json.

To do "set" and "get" we suppose than we need 2 "form" with different "rel" dataproperties ("set" and "get"). But we don't know how to do this simple example correctly ?

Could you help us ?

Requête :
PUT /~/in-cse/in-name/SDT_IPE/DEVICE_org.onem2m.home.device.deviceLight__001788fffe16af9e.SH.L3/org.onem2m.home.moduleclass.binarySwitch__MzkxNSoxMTI4MypodWU6TENUMDAxQDAwMTc4OGZmZmUxNmFmOWUjTDM.EQ. HTTP/1.1
Host: iotdockreg.orange-labs.fr
X-M2M-Origin: 
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache
Postman-Token: e25cffa4-f9fd-4df5-a76c-51a931187369

{
    "hd:binSh": {
        "powSe": "true"
    }
}
 Best regards
Réponse :
{
    "hd:binSh": {
        "lt": "20180619T065251",
       "cnd": "org.onem2m.home.moduleclass.binarySwitch",
        "powSe": "true"
    }
}

**Comment by benfrancis** [comment]
I agree this isn't entirely clear from the latest [Editor's Draft](https://w3c.github.io/wot-thing-description).

[Section 5.2.5](https://w3c.github.io/wot-thing-description/#form) says:
> The protocol binding may contain a form for the get operation and a different form for the set operation. The value of the "rel" attribute of the form indicates which form is which and allows the client to select the correct form for the oeration required.

Example 11 from [section 6.1.5](https://w3c.github.io/wot-thing-description/#form-serialization-json) says:

```
...
"forms": [
  {
    "href" : "http://mytemp.example.com:5683/temp",
    "mediaType": "application/json",
    "http:methodName": "POST",
    "rel": "writeProperty",
    "security": "basicConfig"
  }
]
...
```

I'm guessing that if you wanted to support reading the value from the same URL you would need a separate "form" definition.

It would make a lot more sense to me for a property to have a single link that you can both GET to read and PUT to write.

```
...
"links": [
  {
    "href": "/properties/powSe",
    "mediaType": "application/json"
  }
]
...
```

Full Thing Description:

```
{
  "name": "Binary Switch".
  "properties": {
    "powSe": {
      "type": "boolean",
      "links": [
        {
          "href": "/properties/powSe",
          "mediaType": "application/json"
        }
      ]
    }
  }
}
```

**Comment by fabriceblache** [comment]
Thanks for your reply
Why don’t we have an InteractionPattern object? It seems that InteractionPattern’s fields are directly defined in all InteractionPattern’s subclasses (e.g Property, Action & Event)
"forms": [
  {
    "href" : "http://mytemp.example.com:5683/temp",
    "mediaType": "application/json",
    "http:methodName": "POST",
    "rel": "writeProperty",
    "security": "basicConfig"
  }
]

Rel parameter : we think that is important to define well-known values for the rel parameter. For example:
•	Get  retrieve a value
•	Set -> Configure a value
•	Create -> new value
•	Delete -> delete value
•	Subscribe ?
Basically, such values should indicate the operation the Form describes.
http:methodName parameter is not a Data property of Form. It seems to be related to http namespace ontology (http://www.w3.org/2011/http#). Is it possible to mix within a Form instance data property defined by Thing Descriptor & data properties from another ontology?

{
  "name": "Binary Switch".
  "properties": {
    "powSe": {
      "type": "boolean",
      "links": [
        {
          "href": "/properties/powSe",
          "mediaType": "application/json"
        }
      ]
    }
  }
}
Here we don’t understand why “links” parameter is hosted into a Property. It should be defined in Thing isn’t it?

best regards,
Fabrice

**Comment by mkovatsc** [comment]
> Why don’t we have an InteractionPattern object?

When switching to the "Simplified TD", we reverted to having separate entry points for the specific Interaction Patterns (i.e., "properties", "actions", "events") instead of a single entry point "interactions". This makes it easier for implementations and enabled us to make semantic annotations and JSON-LD keywords (`@...`).

> To do "set" and "get" we suppose than we need 2 "form" with different "rel" dataproperties ("set" and "get"). But we don't know how to do this simple example correctly ?

If your Thing uses the default methods, one form is enough (it serves both relations). Separate forms are used to override the default request rules (which for HTTP are GET to get, PUT to set) and express specific requires such as header fields for that relation.

TD uses the HTTP ontology to specify HTTP-related metadata. For now, assume that all HTTP terms are `http:` prefixed and included in the TD context file, as we have not concluded yet on how exactly to modularize core vocabulary.

I assume, you use HTTPS. I am not sure if `Postman-Token` is your API key because above you declare "basicConfig" -- if it is an API key, you would need a corresponding `"security": [{ "scheme": "apikey", "pname": "Postman-Token" }]` field in the TD. Your example would look like this without any semantic annotations -- please provide the SDT for your device to see where they would go:

```javascript
...
{
  "id": <yourId>,
  "security": [{ "scheme": "basic" }],
  "name": <yourThingName>,
  "properties": {
    <yourPropertyKey>: {
      "type": "object",
      "properties": {
        "hd:binSh": {
          "type": "object",
          "properties": {
            "lt": { "type": "string" },
            "cnd": { "type": "string" },
            "powSe": { "type": "boolean" }
          }
          "required": [ "powSe" ]
        }
      },
      "forms": [{
        "href": "https://iotdockreg.orange-labs.fr/~/in-cse/in-name/SDT_IPE/DEVICE_org.onem2m.home.device.deviceLight__001788fffe16af9e.SH.L3/org.onem2m.home.moduleclass.binarySwitch__MzkxNSoxMTI4MypodWU6TENUMDAxQDAwMTc4OGZmZmUxNmFmOWUjTDM.EQ.",
        "mediaType": "application/json",
        "http:headers": [
          {
            "http:fieldName": "X-M2M-Origin",
            "http:fieldValue": "",
          }, {
            "http:fieldName": "Cache-Control",
            "http:fieldValue": "no-cache"
          }, {
            "http:fieldName": "Postman-Token",
            "http:fieldValue": "e25cffa4-f9fd-4df5-a76c-51a931187369"
          }
        ]
      }
    }
...
```
If one of `X-M2M-Origin`, `Cache-Control`, or `Postman-Token` is not required to successfully get a response, you can omit its `fieldName`/`fieldValue` entries.

If either `lt` or `cnd` must not be included in the PUT payload, you must set the JSON Schema term `readOnly` to `true` in the respective schema.

I am not sure why you receive a response with a representation. Usually a PUT would elicit a 204 response, but maybe oneM2M defines an action result that shall give back the resulting state?

**Comment by sebastiankb** [comment]
non active issue anymore. @mkovatsc explained the guideline about read/write in Properties. In addition, the latest TD draft also provides concrete "rel" definitions when the default approach cannot be used.
