### ISSUE TITLE
Using `tm:required` for non-affordance members

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1594]
Currently, the use of `tm:required` is limited to affordances with the following assertion in the spec:

> The JSON Pointers of tm:required MUST resolve to an entire interaction affordance Map definition. 

This means that it is not possible to indicate that some members like top level forms, version, securityDefinitions etc. cannot be made mandatory. Should we relax this assertion?

**Comment by sebastiankb** [comment]
from today's TD call:
- default assumptions of TM, everything is mandatory and should be followed by TD instances
- it turns out, that we would more need a TD "tm:optional" then "tm:required" (this would also solve the issue #1581)
- we should ask developer about this idea (e.g., @thjaeckle, @mjkoster )

**Comment by thjaeckle** [comment]
As I already suggested in #1400 I absolutely support that as it feels more "natural" for me as developer to explicitly declare optional affordances in the "interface" (as I understand the ThingModel).

**Comment by egekorkan** [comment]
That is good news (in a way). @thjaeckle do you think you can provide implementation examples until next week's testfest?

**Comment by thjaeckle** [comment]
@egekorkan "implementation" as in TM examples with a suggested "tm:optional" section?

**Comment by egekorkan** [comment]
Yes :)

**Comment by thjaeckle** [comment]
Then sure - I can prepare something.. just point me to the place where to put those ;)

**Comment by egekorkan** [comment]
I have spoken with two implementors of TM features, namely @thjaeckle (contributor to Ditto) and @fexpal (contributor to Editdor) and they would be ok with this change. For them, most (or nearly all) use cases use TMs like an interface where every affordance is implemented anyways. 

TMs with `tm:optional` should go to https://github.com/w3c/wot-testing/tree/main/data/input_2022/TD under the corresponding implementation

**Comment by thjaeckle** [comment]
There is one problem I just noticed with `tm:optional`:
When using with TM extension, a TM B (e.g. being a "lamp" TM) extending a TM A (being a "switchable" TM with an `tm:optional` action `"switch-on-for-duration"`) can't define that for the TM B this action is mandatory and not optional

So to make the example clear:

TM A ("switchable") defines that action "switch-on-for-duration" is optional:
```json
{
  "@context": [
    "https://www.w3.org/2022/wot/td/v1.1",
    {
      "time": "http://www.w3.org/2006/time#"
    }
  ],
  "@type": "tm:ThingModel",
  "title": "Switchable",
  "version": {
    "model": "1.0.0"
  },
  "tm:optional": [
    "/actions/switch-on-for-duration"
  ],
  "properties": {
    "on": {
      "title": "On",
      "description": "Whether the switch is on or off.",
      "type": "boolean"
    }
  },
  "actions": {
    "switch-on-for-duration": {
      "title": "Switch on for duration",
      "description": "Switches the switchable on for a given duration, then switches back to the previous state.",
      "input": {
        "@type": "time:Duration",
        "title": "Duration in seconds",
        "type": "integer",
        "unit": "time:seconds"
      }
    }
  }
}
```

TM B ("lamp") extending TM A:
```json
{
  "@context": [
    "https://www.w3.org/2022/wot/td/v1.1"
  ],
  "@type": "tm:ThingModel",
  "title": "Colored Lamp",
  "version": {
    "model": "1.0.0"
  },
  "links": [
    {
      "rel": "tm:extends",
      "href": "./switchable-1.0.0.tm.jsonld",
      "type": "application/tm+json"
    }
  ],
  "tm:optional": [],
  "properties": {
    "color": {
      "title": "Color",
      "description": "The current color.",
      "type": "object",
      "properties": {
        ...
      }
  }
}

```

The TM B ("lamp") can now not specify that the "extended" action from TM A ("switchable") named `"switch-on-for-duration"` is mandatory for TDs fulfilling the TM's contract..

I think in order to be still able to, we would need both: `"tm:required"` and `"tm:optional"`.
One could of course also argue that this is not a valid use-case and that the TM B could still reference to the `"switch-on-for-duration"` via `"tm:ref"` and mark is as non-optional in its own `"tm:optional"`.

@egekorkan @sebastiankb what do you think? 
When using `"tm:required"` this is not a problem, as all extending TMs implicitly also "inherit" the "required" affordances from the TM and can't be allowed to make some of them not-required.

**Comment by sebastiankb** [comment]
@thjaeckle thanks for this example. 

Question: When keeping "tm:required" it can be used to overwrite "tm:optional" definition from parents TM definitions, right?

**Comment by relu91** [comment]
> When keeping "tm:required" it can be used only to overwrite "tm:optional" declarations from parents TM definitions, right?

I am not against this but it feels a little bit complex to verify and also understand(?). `tm:ref` mechanism sounds more explicit. I can do something like this, isn't it?: 
```js
{
   "@context":[
      "https://www.w3.org/2022/wot/td/v1.1"
   ],
   "@type":"tm:ThingModel",
   "title":"Colored Lamp",
   "version":{
      "model":"1.0.0"
   },
   "links":[
      {
         "rel":"tm:extends",
         "href":"./switchable-1.0.0.tm.jsonld",
         "type":"application/tm+json"
      }
   ],
   "properties":{
      "color":{
         "title":"Color",
         "description":"The current color.",
         "type":"object",
         "properties":{
            "..."
         }
      }
   },
  "actions": {
     "switch-on-for-duration" : {
         "tm:ref" :"./switchable-1.0.0.tm.jsonld#/actions/switch-on-for-duration
     }
  }
}
``` 

I would say a little bit verbose but at least we should not care to explain the complex situations when you mix `tm:required` with `tm:optional`.

**Comment by thjaeckle** [comment]
> @thjaeckle thanks for this example.
> 
> Question: When keeping "tm:required" it can be used only to overwrite "tm:optional" declarations from parents TM definitions, right?

Yes, but having 2 keywords here might really be confusing like also @relu91 pointed out.
Then you would also need to specify that it e.g. is not allowed to have one affordance contained in both, etc. ..

**Comment by thjaeckle** [comment]
I would like to start a discussion in even another direction:
Do we need to define required or optional affordances at all?

Why not make everything required by default and therefore also remove tm:required from the spec. 

You can still use extension to define TMs with less affordances and move "optional" affordances to a more specific TM extending the more generic one..

I did not have the need to define optional affordances at all.
I even intuitively used extension to build a hierarchy in our examples, eg:
* https://github.com/eclipse/ditto-examples/blob/master/wot/models/switchable-1.0.0.tm.jsonld
* https://github.com/eclipse/ditto-examples/blob/master/wot/models/colored-lamp-1.0.0.tm.jsonld
* https://github.com/eclipse/ditto-examples/blob/master/wot/models/dimmable-colored-lamp-1.0.0.tm.jsonld

In this examples:
* switchable defines property "on" 
* colorable lamp extends switchable and defines a "color" property
* dimmable colored lamp extends colored lamp and defines a "dimmer-level" property 

So a TD can be an instance of either "colored lamp" or, more specifically, an instance of "dimmable colored lamp". 
The property "dimmer-level" therefore is optional and must only be provided if the TD claims to be an instance of the "dimmable colored lamp" TM

I think that this is sufficient for modeling optionals and it is simple (at least for developers knowing about extension and inheritance). 

What do you think?

**Comment by sebastiankb** [comment]
You solve the "optional" aspect by defining different "small" variation of TMs. I'm not sure if this result to a huge set of TMs that makes hard to decide which to follow and you may loss the overview quickly.

**Comment by egekorkan** [comment]
I think this is a discussion worth having. I see that there are two ways to achieve a similar outcome:
1. Have one TM per TD generation where the only flexibility happens through omitted/empty terms and placeholders
2. Have one TM per different TD possibilities where the flexibility happens through omitted/empty terms, placeholders and `tm:required`.

If we remove `tm:required`, the second case would need to split the TMs for each possible TD generation which might be too much in some cases

**Comment by thjaeckle** [comment]
I recently saw that e.g. "Discovery" makes use of `"tm:required"` e.g. to state that a Thing Directory at least has to be able to list all available TDs:
https://github.com/w3c/wot-discovery/blob/9d0581a9ed3467fc99ce2d2587ed666c8ad86154/directory.tm.json#L15-L17

So thinking about what I wrote earlier that this could also be achieved via `"tm:extends"` (which it could), I see and have to admit that this would lead into really many TMs instead, because:
> Please note that a TD can only be an instance of one TM at a time. That means for Thing Descriptions: The links array MUST use the entry with "rel" : "type" a maximum of once.

That means that each "combination" of different possible (and reasonable) affordances would have to be a separate TM and a Thing Directory would e.g. decide to implement "retrieving TDs, creating TDs, deleting TDs" by referencing a TM including exactly those 3 features (e.g. using extension).

That really seems not feasible - so with the above restriction ("a TD can only be an instance of one TM at a time") I think you are right: using a `"tm:optional"` simplifies a lot.

However: It would provide a lot of more "semantics" if a TD could e.g. declare that it "is of type": "retrieving TDs, creating TDs and deleting TDs" where:
* the TM for "retrieving TDs" would include "/properties/things" and "/actions/retrieveThing"
* the TM for "creating TDs" would include "/actions/createThing", "/actions/createAnonymousThing", "/actions/createAnonymousThing", "/events/thingCreated"
* the TM for "deleting TDs" would include "/actions/deleteThing" and "/events/thingDeleted"

Looking just at the directory TM https://github.com/w3c/wot-discovery/blob/main/directory.tm.json it is not clear which affordances a directory implementation would support.
You would only know by inspecting the TD (which the directory would provide).
Which somehow is not fulfilling the goal of using Thing Models as abstraction for TDs, as only the TD - the instance at runtime - in the end "knows" which parts of the contract of the TM it implements.

**Comment by sebastiankb** [comment]
> Looking just at the directory TM https://github.com/w3c/wot-discovery/blob/main/directory.tm.json it is not clear which affordances a directory implementation would support.

This is a general definition that shows what the minimum requirements of the WoT Directory are. I principle, this is a kind of design decision what you like to serve to the "outside" at the end with your specific implementation. If you want to be very clear what should be definitely be implemented and used by an Servient this should be reflected by the TM (=no optional definitions should be used).

I think, required / optional definitions is very useful to manage your TMs of a (device) ecosystems, e.g., to increase reusage of existing basic definitions. This is maybe something what happen only "internally". Proposing information to the "outside" there can be two options: having a specific TM without any margin or, my preferred solution, to use TD which gives all the information what is really implemented.

**Comment by egekorkan** [comment]
This is not relevant anymore after #1640
