### ISSUE TITLE
[OracleReview] 11.3.1 Versioning

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1619]
normative assertion: "Over time, Thing Model definitions may change and must be made identifiable through versioning."

**Comment by egekorkan** [comment]
This seems to be already fixed at https://w3c.github.io/wot-thing-description/#thing-model-versioning

**Comment by mlagally** [comment]
Why do we permit different TM versions without clearly mandating a distinct version?
TMs are a new concept in the TD spec, so we can enforce versions.
These "SHOULD" assertions are not binding and can be ignored by anyone.

**Comment by sebastiankb** [comment]
Similar to TD, `version` is optional since TD 1.0.  
It heavily depends on the use case. Usage of a small TM just as a simple template for TD instances and forcing a version number would be overkill in my view, especially if you don't know which number you should provide and what meaning should it be (1, 0.1., 1.0, 1.0.0, ...). Version information is only useful if there is also a convention behind it, as is typically the case in an ecosystem.

**Comment by sebastiankb** [comment]
from today's TD call, we decided to close this issue
