### ISSUE TITLE
Section: 5.3.4.2.1:  Mapping of op values to data schemas for meta operations is incomplete

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#1703]
5.3.4.2.1 Mapping op Values to Data Schemas

The table in that section only contains a subset of some valid operations. However it does not contain a mapping of meta operations such as  readallproperties, writemultipleproperties, etc.

The specification only contains the following note:

> EDITOR'S NOTE: Data Schemas of meta operations
The data schemas for meta operations such as readallproperties is currently under discussion.

This should be fixed before CR publication: a clear mapping for all meta operations should be added to the table.

**Comment by benfrancis** [comment]
See also: #1665

**Comment by mlagally** [comment]
After reviewing #1665, I believe this is a bit more than just an editorial change. 
Just removing the editors note is an editorial change, but it is not resolving the underlying problem: the table is incomplete and does not provide the necessary guidance on the nontrivial cases.

**Comment by sebastiankb** [comment]
I think here are two options here:
1) we remove this non-normative section. This section was also not available in TD1.0. However, I think this is not a good idea since it is a big win for readers to easy understand the basic op mappings.
2) we keep this section as is: There is no requirement to describe the data schema of all operations. These meta operations are left like this in order to adapt to different protocols.

I would prefer option 2. For Proposed REC we just simple update the editorial note (or simply remove it).
