### ISSUE TITLE
Modeling string or array of string in the TTL files

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1884]
As mentioned at https://github.com/w3c/wot-thing-description/pull/1881#issuecomment-1737568086, we need the correct modeling for anyURI or Array of anyURI.

**Comment by mahdanoura** [comment]
For the `followsProfile` since the order of the URIs isn't important, it would be simpler to leave the data property with a range `xsd:anyURI` and make multiple property assertions.
```
:followsProfile rdf:type owl:DatatypeProperty ;
    rdfs:label "followsProfile" ;
    rdfs:comment "Indicates the WoT Profile mechanisms followed by this Thing Description and the corresponding Thing implementation."@en ;
    schema:domainIncludes :Thing ;
    rdfs:range xsd:anyURI ;
    rdfs:isDefinedBy <https://www.w3.org/2019/wot/td> .
```
With this, the following would be valid when creating an instance of a Thing with multiple profiles: 

```
:myThing rdf:type :Thing ;
    :followsProfile <https://example.com/profile1> ,
                    <https://example.com/profile2> ,
                    <https://example.com/profile3> .
```

But, if we want to add order to these URI's then we need to use more structure and use rdf:list or collections (rdf:Seq or rdf:Bag ). But, I think we don't really need this, as rdf:list can't be used especially with OWL-DL or many RDF tools don't provide full support for it.
