### ISSUE TITLE
Security Figure is missing proxy term

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1907]
Our figure at https://w3c.github.io/wot-thing-description/#td-security-model is missing the proxy term that is defined in https://w3c.github.io/wot-thing-description/#table-vocabulary-terms-in-securityscheme-level

**Comment by mahdanoura** [comment]
The term `proxy `is not provided in this visualization, since the class `SecurityScheme` is shown. Proxy is defined as an `objectProperty` with the domain `SecurityScheme` and that's why it's shown in the table and not in the visualization. There is no range defined for Proxy, so there is no way of showing it with a graph, because you would have an edge but no node to connect to.

**Comment by egekorkan** [comment]
Call of 25.10: `dataProperty` should be used instead
