### ISSUE TITLE
subProtocol missing for form field

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#193]
The vocabulary is missing the `subProtocol` term for forms.
It is already required for the Event in Example 1, since it is now HTTP instead of CoAP.

**Comment by sebastiankb** [comment]
Hmm, this has a big impact: text, ontology + figure update

**Comment by vcharpenay** [comment]
Does it have to be included in the `td` namespace? Other form-sepcific fields are in their respective protocol namespaces (`http`, `coap`, `mqtt`). How about having a `ws` namespace, intstead?

**Comment by sebastiankb** [comment]
Good questions.

Maybe @mjkoster can comment that? Many thanks.

**Comment by mjkoster** [comment]
Random thoughts:

This IANA registry is for websocket sub protocols 
https://github.com/larseggert/iana-assignments/blob/master/websocket/websocket.txt
perhaps there should be a ws vocabulary with its subprotocols and any other options
Are we able to use one of the IANA registered ws sub protocols? There doesn't seem to be an event multiplexing sub protocol defined. 

We would like to define EventSource and LongPoll as sub protocols of http
we don't control the http vocabulary so can't easily add subprotocols there

The EventSource (SSE) sub protocol has the feature of multiplexing different events in the same stream using predefined tags. This could be useful for MQTT as well. However, this approach seems to be better described as a mediatype.

We might describe CoAP Pub/Sub as a sub-protocol, but it seems unnecessary since it can just use option control.

We could consider creating:
- namespace for binding template extensions that could include EventSource, LongPoll
- content formats for multiplexed event and bulk property payloads, which may include the ws and EventSource tag formats

**Comment by benfrancis** [comment]
> Are we able to use one of the IANA registered ws sub protocols?

See https://www.iana.org/assignments/websocket/websocket.xml#subprotocol-name

I spent some time investigating [WAMP](https://wamp-proto.org/), with which you can kind of use pub/sub for events and RPC for actions, but I found it wasn't quite a good enough fit for mapping the Web of Things data model (properties, actions and events). That's why Mozilla is still working on a "webthing" sub-protocol, specifically for this purpose.

We started out thinking of WebSockets as a way for subscribing to changes on an individual resource by its URL (e.g. a property via its property URL). A WebSocket is just an upgraded HTTP GET request in the same way that Observe is just an upgraded CoAP GET request, which keeps listening for changes. But we soon found out that isn't a very efficient way to use WebSockets (TCP vs. UDP). If you want to listen to multiple properties, or multiple properties of multiple things (e.g. all the smart devices in your home), you end up with a lot of open TCP sockets per client.

In practice we found it was better to have a single WebSocket open per client to [thing](https://iot.mozilla.org/wot/#thing-resource) connection, or even a single WebSocket per client to [things](https://iot.mozilla.org/wot/#things-resource) connection, with the gateway exposing multiple things over a single socket. That's why our current approach is to have a single WebSocket URL in the links section of a Thing Description, and a webthing WebSocket sub-protocol which defines message types for dealing with properties, actions and events all over the one socket. We're also considering extending this out to multiple things per socket, with the thing id used to differentiate between messages from different devices.

Would that mean that subProtocol should be added to the top level links member as well? It's not strictly necessary as negotiating a sub-protocol is part of the WebSocket handshake process when upgrading a GET request with an Upgrade header.

Incidentally, I'd be interested to know how other people have used WebSockets for non-trivial use cases.

**Comment by benfrancis** [comment]
P.S. I know EVRYTHNG have also used MQTT as a WebSocket sub-protocol to benefit from its QoS and multiplexing features.

**Comment by draggett** [comment]
@benfrancis wrote: "Incidentally, I'd be interested to know how other people have used WebSockets for non-trivial use cases."

For my NodeJS implementation of an application gateway for the Web of Things, I integrated support for HTTP, Server-Sent events and WebSockets.  In brief, I use HTTP for retrieving thing descriptions and for serving Web pages for applications installed on the application gateway. I then use WebSockets for messaging between exposed and consumed things. I chose to share the WebSocket connection for multiple things whose end points are the same devices. The messages thus include identifiers for things and for properties on things, etc.  I considered this to be more efficient than using a separate WebSocket connection for each pair of exposed and consumed things.  Path expressions allow messages to refer to sub-properties.

The messaging scheme defines a sub-protocol that includes property updates, event notifications, action invocations and responses, and other messages relating to the thing life cycle, including registration. When an application asks the application platform to create a consumed thing, the response to the registration message includes the current state of all properties. Thereafter property updates are signalled as notifications. For security, HTTP is used to obtain a time limited security token for use within the WebSocket sub-protocol. 

I've also experimented with Server-Sent events as a long polling mechanism for asynchronous notifications based upon the chunked encoding and JSON messages. In principle, this could be used together with regular HTTP requests in place of the WebSocket sub-protocol.  I note however, that WebSockets may be marginally more efficient due to better reuse of existing connections.  For both HTTP and WebSockets robust operation involves the means to automatically reconnect and resynchronise  state upon the loss of a connection. Both protocols are adequate for telemetry use cases involving hundreds or thousands of property updates per second. I found it appropriate to support messages that contain a batched sequence of updates rather than requiring each update to be sent as a separate message.

**Comment by mkovatsc** [comment]
`subProtocol` in itself is protocol independent, as it applies to multiple protocols (HTTP and WebSockets for what we have seen so far).

It takes a string literal that depends on the base protocol used, e.g., "LongPoll" or "EventSource" for HTTP, "mqtt", "coap", etc. from [IANA](https://www.iana.org/assignments/websocket/websocket.xml#subprotocol-name) for WebSockets.

@vcharpenay Is there a benefit having `subProtocol` in each of the protocol vocabularies (`http:subProtocol`, `ws:subProtocol`, etc.)? Note that the HTTP in RDF vocabulary we want do use does not have the concept of subProtocol. I see it as important as `href`, and hence would have put `subProtocol` in the TD core vocabulary.

It is meaning-wise as important as `href` and should be part of the TD core vocabulary. As this is done in the latest TD spec, I close the issue.
