### ISSUE TITLE
Clarify relationship of security schemes between WoT and OpenAPI

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#201]
The Editor's note in section 5.4 contains ambiguous language and does not clarify the relationship of
the security schemes used in WoT and OpenAPI. 
If the schemes in WoT are not fully compatible, the note should highlight the differences, i.e. clarify the normative requirements of the TD spec. 
What does "partly based" mean here- Is only a subset of OpenAPI used?

**Comment by takuki** [comment]
Can @mmccool comment on this? Thank you.

**Comment by mmccool** [comment]
Going over all the differences in detail would be very complex and not really all that useful.   I personally would leave this as an exercise for the reader.   I mention a few points of difference, namely that we have to include schemes for CoAP and MQTT.   However this brings another point to mind... do editor's notes go away in the final REC?   If so we may need to replace this Ed Note with something else in the document, OR just drop the reference to OpenAPI.  However, I would like to cite them to be fair to the source of "inspiration", but perhaps with a slightly less ambiguous statement.   If someone can suggest something better I would be happy to include it.

Note that the Security TF decided to make strict compatibility with OpenAPI a non-goal since otherwise it would drag in a lot of extra stuff we don't really need (much as we see with our challenges with JSON Schema compatibility).

**Comment by sebastiankb** [comment]
@mmccool will make a PR about this

**Comment by mmccool** [comment]
I just changed the working from "not fully compatible" to "not compatible".
