### ISSUE TITLE
Inconsistent `rel` description in 5.2.6 Form and 5.2.7 Link

### ISSUE THREAD

**Issue by verymuch** [w3c/wot-thing-description#235]
As I understand it, the description of `rel` in 5.2.6 Form and 5.2.7 Link should be the same content. But now they are inconsistent. Is it a bug or is it intentional?

**Comment by sebastiankb** [comment]
It is intentional. The Link is mainly used, e.g., to describe a relation to another Thing and rel is used to describe the kind of relation. Also see [Example 12](https://w3c.github.io/wot-thing-description/#ex-12-example-12-links-href-https-servient-example-com-things-lampcontroller-rel-controlledby-mediatype-application-td-json) in the spec.

The rel in Form is used to describe which kind of operations are allowed with the interaction model (get, set, observe,...). [Example 11](https://w3c.github.io/wot-thing-description/#ex-11-example-11-forms-href-http-mytemp-example-com-5683-temp-mediatype-application-json-http-methodname-post-rel-writeproperty-security-scheme-basic-in-header) provides an example.

**Comment by handrews** [comment]
See #179 for extensive ongoing debate on the nature of "form relations".

**Comment by verymuch** [comment]
Thank you (@sebastiankb and @handrews)  for explaining it to me. Now I get it.
