### ISSUE TITLE
On Links, RFC 8288, and the RDF representation of Links

### ISSUE THREAD

**Issue by maximelefrancois86** [w3c/wot-thing-description#262]
If I understand well RFC 8288 obsoletes RFC 5988 and there is no more registry for target attributes. See https://tools.ietf.org/html/rfc8288#section-2.2 
Therefore: I think the set of fields for Links should be left open, as users may define any new target attribute (e.g., `if`, `rt`, `sz`, ...). 

Consider for example:

``` 
</sensors/light>;rel="hosts";type="application/json";rt="light-lux core.sen-light";name="the name"
``` 

# JSON representation

Maybe this would be an equivalent in the TD-JSON?

``` 
{ "href": "/sensors/light" ,
  "type": "application/json",
  "title": "the title" ,
  "rel": "hosts",
  "rt": "light-lux core.sen-light",
  "name": "the name"
}
``` 

Some remarks/questions.

- isn't target attribute `type` in RFC 5988 clashing with `mediaType` (or `contentType`) in TD?
- If we know the semantics of `rt`, one could want to make the object of the `rt` key an array. How can we be sure every TD author will represent the value of a `rt` key the same way?
- on the other hand, the value of `name` should not be an array. how can we anticipate the representation of any target attribute in TD?

RFC8288 says: 

> The names of target attributes SHOULD conform to the token rule, but SHOULD NOT include any of the characters "%", "'", or "*"

where 

```
token          = 1*tchar

tchar          = "!" / "#" / "$" / "%" / "&" / "'" / "*"
              / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~"
              / DIGIT / ALPHA
              ; any VCHAR, except delimiters
```

Are these always valid JSON keys ?

# RDF representation

- The default value for `anchor` needs to be computed before transforming this element to RDF. 
- `name` is a target attribute that I invented to show that *someone* may define a new target attribute that clashes with the name of a key defined in TD. 

These will create bugs if using a global JSON-LD context. I don't see an easy workaround, and I militate instead to use custom algorithm to generate RDF from the Link objects.

Below are a few options that I think a simple algorithm could output: 

## Option 1

Always use TD namespace for target attributes

``` 
<anchor defined in Thing> td:href </sensors/light> ;
  td:type "application/json" ;
  td:rel "hosts" ;
  td:rt "light-lux core.sen-light" ;
  td:name "the name" .
``` 

Con: 

- we cannot anticipate and create td: terms for all the possible target attributes people will invent. 

## Option 2

Define some URN namespace for td and sub-namespace for target attributes (e.g., <urn:td:ta:type>)

``` 
<anchor is defined in Thing>  td:href </sensors/light> ;
  td:rel "hosts" ;
 <urn:td:ta:type> "application/json" ;
  <urn:td:ta:name> "the name" ;
  <urn:td:ta:rt> "light-lux core.sen-light",
``` 

Open question: are target attribute names always valid for the URN syntax defined in [rfc8141](https://tools.ietf.org/html/rfc8141#section-2)? 

## Option 3

Use more complex RDF structrue and just strings

``` 
<anchor defined in Thing> td:href </sensors/light> ;
  td:rel "hosts" ;
  td:attribute [ 
    td:name "type" ;
    td:value "application/json"
  ] ,
  [ 
    td:name "rt" ;
    td:value "light-lux core.sen-light"
  ] .
```

**Comment by mkovatsc** [comment]
> isn't target attribute type in RFC 5988 clashing with mediaType (or contentType) in TD?

What do you mean by "clashing"? The `type` attribute is a hint what media type to expect from the target resource. For `links`, it is now aligned, so that there is no more `mediaType`. For `forms`, we are now using the term `contentType`. This attribute is not a hint, but an instruction what media type AND possible parameter to submit -- a media type cannot take parameters, hence `contentType`.

For Properties or Forms with a GET in general, see https://github.com/w3c/wot-thing-description/issues/250 about the response content type.

> If we know the semantics of rt, one could want to make the object of the rt key an array. How can we be sure every TD author will represent the value of a rt key the same way? on the other hand, the value of name should not be an array. how can we anticipate the representation of any target attribute in TD?

I think you are talking about the round-tripping problem of Link Format when going via JSON. In the CoRE WG, we got rough consensus that a newer, more powerful format should not suffer from the limitations of (buggy) RFC6690 and the Link header format. A JSON representation of links would use an array and it can be downgraded to Link Format by converting it to a whitespace separated list. The other way is only possible when the semantics of the attribute are known.

Unfortunately, the authors of https://tools.ietf.org/html/draft-ietf-core-links-json-10 want to drop the work after running into several practical issues such as case sensitivity. CoRAL was mentioned as possible future replacement. This, TD is probably the first spec to define a JSON representation of Links. We plan to put the definitions into a separate namespace (i.e., not td:). We will apply camel-casing rules for the terms. We will follow the consensus of (not) round-tripping.

> RDF representation

Custom attributes would need their respective namespace prefix. Your example with `name` would not make a problem, as we use local `@context`s and only terms defined for Links have meaning; if they clash, it's an error by the author not using the proper prefix.

**Comment by maximelefrancois86** [comment]
> Custom attributes would need their respective namespace prefix. Your example with `name` would not make a problem, as we use local `@context`s and only terms defined for Links have meaning; if they clash, it's an error by the author not using the proper prefix.

From this I understand a *local* `@context` MUST be added in the representation of every link? 
This would work,  But it probably adds a lot of verbosity. Also, the default value for anchor still needs to be computed right? I assume it would be easier to write a simple algorithm to compute the anchor and the transformation to RDF.

Also, Option 1, 2, 3, as listed above, are all three possible RDF representations of Links we have to discuss

**Comment by vcharpenay** [comment]
A discussion has started to align TD with [CoRAL](https://tools.ietf.org/html/draft-hartke-t2trg-coral), an IETF draft. Among others, your points were discussed and it was decided to further axiomatize the [Web linking module](https://w3c.github.io/wot-thing-description/ontology/lnk.html) (to be renamed "Hypermedia controls"). This goes beyond the scope of the current WoT WG charter, though. I'll close the issue, the discussion can be resumed somewhere else.
