### ISSUE TITLE
Semantic Annotation in the Thing Description 

### ISSUE THREAD

**Issue by maximelefrancois86** [w3c/wot-thing-description#263]
See also issue #259 and #262

It is now clear to me that trying to use JSON-LD globally to map an arbitrary JSON to an arbitrary ontology is really challenging. I believe we should define a custom algorithm to generate RDF directly from the TD , and potentially rely on JSON-LD for specific sub-parts of the TD.
In the TD JSON-Schema of Thing we forbid the use of keys that are not defined in TD, but we add one special key `annotations` whose value is a JSON-LD object.

```
{
  "id": "urn:dev:wot:com:example:servient:lamp",
  "name": "MyLampThing",
  "base" : "coap://192.168.0.1/",
  "annotations": { 
      "@context" : { some custom context } ,
      "abstractionOf": "http://mybuildingmodel.com/room1/lamp" ,
      ...
   }
```

the annotation `{ ...  }` would be preprocessed. For example the `@id` annotation needs to be added, and another generic context for TD may be added  (see https://json-ld.org/spec/latest/json-ld/#ex-35-combining-external-and-local-contexts ):

```
{ "@context":  [  
     "http://w3.org/ns/td/contextForInteractionPatterns.jsonld",
     { some custom context }
  ] ,
"@id": "urn:dev:wot:com:example:servient:lamp" , 
"abstractionOf": "http://mybuildingmodel.com/room1/lamp" ,
...
}
```

And the RDF graph encoded in this JSON-LD document would be added to the overall RDF equivalent of the TD. 

```
<urn:dev:wot:com:example:servient:lamp> a td:Thing ;
  rdfs:label "MyLampThing" ;
  <http://example.org/abstractionOf> <http://mybuildingmodel.com/room1/lamp> .

...
```

This adds additional flexibility:

- simple TD implementations could just ignore these annotations
- anyone can provide a custom context there

**Comment by mkovatsc** [comment]
As mentioned in #259, I cannot clearly see the limitations nor benefits of any direction. In particular the sudden break with JSON-LD in the last minute causes a headache.

The original goal of the Thing Description is to provide a uniform, intuitive format to describe IoT devices and services as "Things", thereby improving interoperability and usability of IoT. While JSON and human-readability for developers is a central focus, we also recognize the benefits, nay, necessity of machine-readability to allow for scalable management and orchestration of IoT systems. For the latter, it came natural to use the powerful Semantic Web tooling.

Given this, there is already huge improvement when we interpret TDs with a JSON-LD ("1.1 to be") processor and store the Thing metadata in a knowledge base. We can use powerful (SPARQL) queries to find the Things we are interested in and can also use very helpful inference. The semantic model behind that might be rather simple, but this brings us back to the original goal.

I personally see SSN alignment as an advanced feature, as the ontology is more complex and there is a growing threat of importing a conflicting statement from some related Linked Data vocabulary that breaks the Knowledge Graph. Hence, I always expected such alignment to happen through adding additional statements in the TD that come from additional contexts. The discussion in https://github.com/w3c/wot-thing-description/issues/259 left the impression, that there are even multiple ways how to align TD with SSN, which depends on what people want to do.

Hence, I would like to see a remedy somewhat like this:

* We continue to use JSON-LD to derive a default RDF representation of Things. (I am aware that we still miss one 1.1 feature to use this directly, but the meeting with the JSON-LD WG sounded promising; for now we define a polyfill algorithm to have a correct normative reference, which unfortunately has to be JSON-LD 1.0; later we can update the TD spec to reference 1.1 without polyfill.)
* We provide a document that explains how to add SSN alignment statements. Ideally these could be applied automatically.
* Talking with @mjkoster, this also aligns with the original idea of iot.schema.org, which would not provide annotations that directly align with QUDT or OM or SSN, but rather provide simplified usage of semantics (have something to agree on and work bottom-up) and bridge to the established ontologies in the background.

In addition, I would like to see what actually has to be changed in our TD format, so that default JSON-LD processing produces correct triples where `td:Property owl:sameAs ssn:Property`, `td:Thing owl:sameAs ssn:System`, or whatever is the actual alignment holds.

**Comment by maximelefrancois86** [comment]
> I would like to see what actually has to be changed in our TD format, so that default JSON-LD processing produces correct triples [...] 

That's one the point, it's very cumbersome, and most of the time impossible, to find the right `@context` to map a pre-defined JSON structure to an pre-defined ontology structure. 

The quite straightforward remedy I see is:

- In an external document (a group note) we define the TD ontology, and define a simple transformation algorithm to generate the RDF we want from a TD.
- The "variable and extensible parts" are isolated in the TD (e.g., value of keys `annotations` in some places), and are expressed using JSON-LD (and so we don't *need* to even specify the version there).
- In that external document, we specify how TD and SSN, and how TD and iot.schema.org, should work together.

**Comment by maximelefrancois86** [comment]
## pre-processing step or not? What the spec says

**A TD-JSON doc is also a JSON-LD doc:** The following sentences in the TD spec imply that a TD-JSON document is also a valid JSON-LD document (and that the RDF can be obtained directly using the standard JSON-LD processor):

Abstract: 

> Thing Descriptions, by default, are encoded in a JSON format that also allows JSON-LD processing

Section 4 (strange sentence btw, what does it mean to _validate based on JSON-LD_):

> A JSON Schema [JSON-SCHEMA-VALIDATION] is provided in Annex A. JSON Schema for TD Instance Validation to validate Thing Description instances based on JSON-LD 1.1.

First sentence in section 6.1:

> The JSON serialization of TDs follows the syntax of JSON-LD 1.1 in order to streamline semantic evaluation. Hence, serializations can be parsed either as raw JSON or with a JSON-LD 1.1 processor.

**A TD-JSON doc is not a JSON-LD doc:** The following sentences imply a TD-JSON must first be pre-processed to obtain a valid JSON-LD document.

Introduction: 

> The TD can be also processed as an RDF-based model. In that case, the Thing Description instance needs to be transformed into valid JSON-LD first. 

Sentence in Section 6.3.2:

> To interpret the semantic meaning of a Thing Description in terms of RDF triples, a Thing Description instance first requires a valid JSON-LD 1.1 representation based on this Thing Description specification. Then this representation can be passed to a JSON-LD 1.1 processor.
 
**JSON-LD keywords may be added A TD-JSON doc is not a JSON-LD doc:** 

## Why a pre-processing step is important

There are three main points in favor of having a pre-processing step TD-JSON -> JSON-LD:

- we may want default values to be added automatically
- we may want identifiers for Prop/Action/Events to be computed automatically
- using keys with boolean value like `observable` is good practice in JSON. However in RDF it is a lot better to use classes like `td:ObservableProperty` and `td:NotObservableProperty`. One of the reasons is this would make querying observable properties in a TD repo a lot more efficient.

## Pros of having a pre-processing step 

* the development of the TD JSON model and the TD ontology is decoupled
  * best practices may be adopted in both worlds, without conflicting.
  * proper distinction between the syntax and the semantics
* default values may be inserted
* some identifiers may be computed automatically

## Risk if a pre-processing step is required

* a JSON TD that contains keys like `@context` and `@type` will **look like** it is a JSON-LD document. people that receive such JSON TD document MIGHT try to directly apply the JSON-LD processing, leading to erroneous RDF representations.

## One possible counter-measure

* apart from a few selected additional keys (e.g., `@type`) , all the additional annotations could be **isolated** in a  separate object, which could be a valid JSON-LD object

**Comment by takuki** [comment]
How can one distinguish JSON-based TD from JSON-LD-based TD when one receives a TD?

**Comment by vcharpenay** [comment]
The latest version of the TD must be interpreted as JSON-LD (`@context` is mandatory), annotations must therefore be embedded in the document.
