### ISSUE TITLE
Do vocabulary terms have a JSON key representation?

### ISSUE THREAD

**Issue by maximelefrancois86** [w3c/wot-thing-description#293]
https://github.com/w3c/wot-thing-description/blob/807ca425dbce8868dbfd7f7d675d9ae99684512a/index.html#L528-L531

False assertion? (e.g., Action is a vocabulary term defined in Section 4, it does not have a JSON key representation)

**Comment by mkovatsc** [comment]
To my understanding it is a terminology issue:

Section 5 lists "Field Name"s, but means the mentioned vocabulary terms. I suggest defining a proper term (e.g., _**vocabulary term**_) and use that in the table header instead of "Field Name" and the assertion.

BTW: There is also still the related "field" vs proper JSON terms issue #194

**Comment by mkovatsc** [comment]
This is not only an RDF topic. It is quite central to have clean relation between model (Sec 4) and serialization (Sec 5).

**Comment by sebastiankb** [comment]
The mention part is not a TD assertion. However, I will rewrite the sentence and I will rename the table header.
