### ISSUE TITLE
Improve abstract

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#30]
I think the abstract is a bit too short and vague.  It should at least mention the major components of the TD, the interaction model, and the basic idea of what a "Thing" is (using the agreed-upon definition)

**Comment by takuki** [comment]
Based on @mmccool 's suggestion, I updated the Abstract as follows.

This document describes a common data model and representation for Web of Things (WoT) Thing Description. Thing Description describes metadata and interfaces of Things, where a Thing is an abstraction of a physical entity that provides interactions to and participates in Web of Things. Thing Description provides a narrow-waist set of small vocabulary that makes it possible both to integrate diverse devices and to make diverse applications interoperable. Thing Description, by default, is encoded in JSON-LD. JSON-LD provides both powerful foundation to represent knowledges about Things and simplicity to process itself as a JSON document. In addition to physical entity, Things can also represent virtual entities. A Thing Description instance can be hosted by the Thing itself or hosted externally due to Thing's resource restrictions (e.g. limited memory space) or when a Web of Thing-compatible legacy device is retrofitted with a Thing Description.

**Comment by mmccool** [comment]
This is good, and hits the main points.  There are some grammar issues however (missing articles, mostly) so I can do a grammar-correction pass if you would like.

**Comment by takuki** [comment]
Thank you, @mmccool, that would help a lot!

**Comment by mkovatsc** [comment]
According to @mmccool this was merged -> closing
