### ISSUE TITLE
Extensible metadata fields

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#311]
The TD spec defines a fixed set of (mostly optional) metadata fields.
However it does not define if additional metadata fields are permitted.

Since it is an important requirement for device manufacturers to include
vendor-specific additional information in a TD, it should be made explicit
that additional fields are permitted.

**Comment by mkovatsc** [comment]
As discussed in the call on 30 Nov 2018, we need to clarify the extension mechanism in the TD spec. Consensus was, that TD borrows mechanisms from JSON-LD here and that we can reuse the `@context` keyword either by pointing to an external context file or inlining the definitions (mapping from term to namespace URI).

Proposal is roughly: "semantic annotations SHOULD be inserted using additional keys and values whose semantics is specified in a JSON-LD Context that is exposed on the web, whose URL is added to the general `@context` of the TD document".

TD authors SHOULD re-use definitions from schema.org and similar.

I think there also needs to be wording that all undefined terms MUST be ignored by a TD parsers (including raw JSON parsers, as RDF-based processors will anyway), because there can be conflicts if special parsers have terms built-in and assume meaning. Such cases should probably use a vendor-specific TD media type (`application/vnd.vendor-td+json`).

**Comment by mlagally** [comment]
> As discussed in the call on 30 Nov 2018, we need to clarify the extension mechanism in the TD spec. Consensus was, that TD borrows mechanisms from JSON-LD here and that we can reuse the `@context` keyword either by pointing to an external context file or inlining the definitions (mapping from term to namespace URI).
> 
> Proposal is roughly: "semantic annotations SHOULD be inserted using additional keys and values whose semantics is specified in a JSON-LD Context that is exposed on the web, whose URL is added to the general `@context` of the TD document".
> 
> TD authors SHOULD re-use definitions from schema.org and similar.

What happens if two context files have contradicting definitions for the same keyword? Who wins?
> 
> I think there also needs to be wording that all undefined terms MUST be ignored by a TD parsers (including raw JSON parsers, as RDF-based processors will anyway), because there can be conflicts if special parsers have terms built-in and assume meaning. Such cases should probably use a vendor-specific TD media type (`application/vnd.vendor-td+json`).

I agree that we should not permit undefined keywords in a TD, however I'm not sure we can enforce that all external @context definitions can be read and interpreted during the parsing process on a resource constrained or disconnected device. 
Vendor-specific media types are the least desirable way to approach this.
On resource constrained devices, where reading the context file is not possible, a prefix based check to verify that all "unknown" keywords have a namespace prefix, which is defined in the @context section gives additional guarantees.

**Comment by sebastiankb** [comment]
please see #212
