### ISSUE TITLE
Mandatory fields vs default value

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#337]
The vocabulary term tables in the TD spec have columns/information for "mandatory" and "default value".

My understanding is that if a term has a *default value* there is no need for the mandatory == yes flag because if there is no value set the *default value* kicks in.

In the current TD spec there are terms marked with _mandatory == yes_ which do also have  a default value.
* [DataSchema](https://w3c.github.io/wot-thing-description/#sec-data-schema-vocabulary-definition) `writeOnly` and `readOnly`. Having mandatory for these fields requires any TD property explicitly contain these to values. Hence almost any example in the spec is not valid
* similarly I think that `contentType` in [Forms](https://w3c.github.io/wot-thing-description/#form) should also not be mandatory
* in [Action](https://w3c.github.io/wot-thing-description/#action) there is `safe` and `idempotent`

**Comment by sebastiankb** [comment]
there was a similar discussion here https://github.com/w3c/wot-thing-description/issues/322

**Comment by sebastiankb** [comment]
default value definition are now moved to section 6. The model section 5 keeps all mentioned vocabulary as mandatory since they are important for the interpretation of TD instances.

Please review.

**Comment by egekorkan** [comment]
I still find this extremely confusing from a beginners perspective. At the end of section 5.1, we have 

> All vocabulary restrictions noted in tables in Section 5.2 Core Vocabulary Definition, 5.3 Data Schema Vocabulary Definition, and 5.4 Security Vocabulary Definition MUST be followed, including mandatory items. 

With this, one can assume that if it says mandatory, it must be in the Thing Description. Only at section 6.1, with the following we understand SOME of the mandatory items can be actually omitted:

>  A Thing Description instance serialization MAY omit one ore more vocabulary terms that are mandatory (5.2 Core Vocabulary Definition) AND have default values based on the table above. 

Firstly, I think that there is a contradiction since we first say MUST and then say MAY on the same requirement.
Secondly, we cannot assume that a beginner will read all the way to section 6.1 and then cross-check with the vocabulary definitions in section 5 in order to write a simple TD. It is actually easier to write a full TD then a simple one since there is less work involved for a human. 

For a person to write a simple TD, he/she has to read the vocabulary definitions, write a TD with all the mandatory fields and then go to section 6.1 and remove the ones that will be converted to default values. 

As a solution, I would imagine that in section 5 tables' mandatory column, we put YES, NO and DEFAULT-GENERATED (can find a better word). This would imply that omitting a YES item would make an invalid simple and full TD whereas omitting a DEFAULT-GENERATED item would make an invalid full TD.

**Comment by vcharpenay** [comment]
I like the idea.

If 'mandatory' means 'does the field require user input?' as if a TD was a form, then `readOnly`, `writeOnly` and others should not be mandatory (because of default values). Now, if 'mandatory' means 'is the field necessary to correctly interpret instances of the information model?', these terms _should be_ mandatory. We have used the latter definition in the spec so far but it seems more intuitive indeed to think the former, especially for new readers.

Because of this ambiguity, what about putting 'assignment' or 'definition' instead of 'mandatory' in the tables? Each row would then have as a value 'mandatory', 'optional' or 'default'.

**Comment by egekorkan** [comment]
> Because of this ambiguity, what about putting 'assignment' or 'definition' instead of 'mandatory' in the tables? Each row would then have as a value 'mandatory', 'optional' or 'default'.

I would vote for this option.

**Comment by takuki** [comment]
Some serialization format can define a "mandatory" item at the information-model level as optional at the serialization level, and other serialization format can define the same "mandatory" item at the information-model level as required at the serialization level. So I think the current way descriptions are separated between section 5 and 6 is the right approach,

**Comment by egekorkan** [comment]
Princeton:
it is agreed to use these three options

**Comment by sebastiankb** [comment]
It was decided to move default values back to Section 5 and spend a separate subsection.

**Comment by vcharpenay** [comment]
> Because of this ambiguity, what about putting 'assignment' or 'definition' instead of 'mandatory' in the tables? Each row would then have as a value 'mandatory', 'optional' or 'default'.

what about the following suggestion? Was it discussed in Princeton?

**Comment by vcharpenay** [comment]
sorry, I missed the earlier resolution. The master branch now includes the changes. "Mandatory" column was replaced with "Assignment", which can be "optional", "mandatory" or "with default".

See e.g. https://w3c.github.io/wot-thing-description/#form.

**Comment by vcharpenay** [comment]
reviewed in the 12.04.2019 TD call.
