### ISSUE TITLE
security assertion missing

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#367]
At the moment there are only two security assertions. td-security-1 is for thing level and td-security-2 is for interaction level. We need td-security-3 which indicates it for forms level

**Comment by egekorkan** [comment]
@mmccool I think you assertion generation tool doesn't look for a third identical id but only for two?

**Comment by mmccool** [comment]
No, my tool intentionally merges multiple assertions if they are identical to save space.  So td-security-2 would list two contexts, Interactions and Forms.  They shod up as separate only because 1 is mandatory and 2 is not.   It may be that test results we may want to check each context separately, but I personally think it's ok to merge them... so the corresponding JSON Schema fragment for td-security-2 should look for "security" in both the Interaction and Forms contexts.

**Comment by egekorkan** [comment]
I see, 

> They shod up as separate only because 1 is mandatory and 2 is not

this was not clear to me.

**Comment by egekorkan** [comment]
On second consideration, wouldn't it be two features to support for an implementation? Especially from the consumer side, for a single form being able to inherit a security definition from the interaction level is a feature, in addition to inheriting it from the Thing level.

**Comment by mmccool** [comment]
This is now resolved since (a) we only have two levels (b) ids are now generated based on context, which makes them unique.  Closing.
