### ISSUE TITLE
Subscription and Cancellation response and request data schemas

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#398]
From Princeton Testfest discussions:

The [example](https://github.com/w3c/wot/blob/master/testfest/2019-02-princeton/inputs/Siemens/siemens-node-wot/eventTest-siemens.json) provided in testfest by Siemens. This showed a missing vocabulary we need on the response a client gets from a subscription or cancellation and how it should subscribe or unsubscribe to it.

To solve this, @mmccool has proposed to have an input and output schema for subscription and cancellation, similar to actions.

Please provide your opinion.

**Comment by ToruKawaguchi** [comment]
I agree to provide both input and output for subscribe event.
Besides, this example leads to further questions: 
- Can we use uri template when we want do unsubscibeevent by "DEL http://192.168.0.124:8080/Siemens-EventTest/events/unsubscribeevent/{subscriptionId}" ?
- Don't we need "op": "modifysubscription" by specifying subscriptionId, for example if we want to change threshold to generate "changeRoomTemplature" event from 1 degree Celsius to 5?
- What about "observeproperty"? In case if allow using similar mechanism for observeproperty, then similarly we  need mechanism to a) path webhook url b) retrieve subscriptionId at start of observing and c) path subscriptionId at end of observing.

**Comment by mlagally** [comment]
I agree that a response to the subscribe/unsubscribe operation is necessary.

If we add "modifySubscription", we are introducing significant complexity,
since you will have a variety of implementations with different constraints and features.

The point on "observe" is very valid: we have basically two event mechanisms,
with a different pattern to perform the subscription, where "observe" does not have
a mechanism to "un-observe".

**Comment by sebastiankb** [comment]
it seems that 'cancellation' and 'subscription' have the same functionality as 'Actions'. The question is if we just point to the Action class or remodel and define a new (super) class like 'Procedure' 

@vcharpenay can you make proposal?

**Comment by egekorkan** [comment]
I think redefining a new superclass would disturb a first-time reader a lot since Property, Action, Event separation is very clear as the different type of possible interactions. The added benefit would be also very small since at the moment no one in the group really use subscription and cancellation. Pointing to the Action class would be a dirty fix but at this state, it makes more sense.

**Comment by mmccool** [comment]
As we discussed in the meeting on Feb 15, if we add a new superclass it would be called something abstract like "Procedure", and then both Action, subscribe, and cancellation would refer to it.   Specifically, my understanding is that the "action" object in the TD would actually be a "Map of Procedure" (or maybe "Map of Action", with Action a subclass of Procedure) while the "subscription" and "cancellation" members of an Event object would point to *single* objects of the class Procedure.   A Procedure could also be used for Thing-level mechanisms related to realmultiple/writemultiple.   

I am in favor of adding this superclass to the information model, it is better than redundantly modelling the same structure in two (or three) places.   

I also suggested Procedure instead of some other possible alternatives: Method and Function.   The reason was that a Procedure acts like a procedure in RPC (Remote Procedure Call) systems, with inputs and outputs.  Functions imply "no side effects" which is not what we mean.  Method a bit esoteric and the object-oriented baggage may not be completely appropriate here.

**Comment by vcharpenay** [comment]
@mmccool's approach looks good to me. I would add to that that the cancellation refers to the subscription rather than the event itself. `cancellation` should thus be defined between a "subscription" object and a "cancellation" object.

Would you consider the following as valid?

 - a `Procedure` is defined by an input schema, an output schema and safe/idempotent flags
 - an `ActionAffordance` is both a `Procedure` definition and an `InteractionAffordance` (it is "a procedure with a form")
 - an `EventAffordance` is defined by a data schema and a `SubscriptionProcedure`
 - a `SubscriptionProcedure` is a `Procedure` with a `CancellationProcedure`; it is neither safe nor idempotent
 - a `CancellationProcedure` is a `Procedure`; it is idempotent but not safe

**Comment by vcharpenay** [comment]
The above statements would look like this when formalized:

![td-proposal](https://user-images.githubusercontent.com/6052970/53186241-ea480880-3600-11e9-8982-828043f138d8.png)

**Comment by sebastiankb** [comment]
this is an example TD instance based on the proposal of Victor 
```
"events": {
"ev1" : {
 "data" : {},
  "subscription" : 
     { 
       "cancellation": {"input": {}, "output":{}},
       "input": {}, 
       "output":{}
}}}
```

**Comment by sebastiankb** [comment]
uriVariables should be also possible in subscription and cancellation

**Comment by sebastiankb** [comment]
I prefer to have subscription, data and cancellation on the same level. I see the point in having cancellation nested in subscription (without subscription you don't have a cancellation), but for me it would make sense to provide only the declaration that is intended for the subscription only.

**Comment by mkovatsc** [comment]
In my opinion the proposal for Procedures and basically nested Actions only in Events goes way overboard and is in strong conflict with our goal of simplifying interfaces. And all that to force in a feature in which nobody was interested for the past 4 years.

> What about "observeproperty"? In case if allow using similar mechanism for observeproperty, then similarly we need mechanism to a) path webhook url b) retrieve subscriptionId at start of observing and c) path subscriptionId at end of observing.

I think this is easy: Observing Properties was introduced because a number of protocols support a relatively easy extension to do so and it could easily be added without blowing up the TD. I would limit it to those, with which we also already have enough experience. When Observing would involve such complex "procedures", we do not gain anything in blowing up the Property definition. It can simply be addressed by introducing a corresponding Event -- as it is based on a heavy-weight subscription mechanism anyway.

> Can we use uri template when we want do unsubscibeevent by "DEL http://192.168.0.124:8080/Siemens-EventTest/events/unsubscribeevent/{subscriptionId}" ?

Yes. In most cases we must, as the issue is rooted in exactly this: we need to read and store information from the subscription response and later put it into the cancellation request, quite often the URI.

> Don't we need "op": "modifysubscription" by specifying subscriptionId, for example if we want to change threshold to generate "changeRoomTemplature" event from 1 degree Celsius to 5?

I would drop this feature from the core TD functionality, as it is not very common across IoT platforms and protocols. Depending on how we solve the complex subscribe/unsubscribe, there might be a good place for such an extension.

> I agree that a response to the subscribe/unsubscribe operation is necessary.

Yes, we need that for the case above, where the client has to learn certain parameters such as subscription ID.

I think we discussed this issue already some time ago, probably in the Binding call... @mjkoster ? I agree that this calls for Action Affordances, but I really dislike the complex proposal with a new superclass and a new abstraction that is basically the same as an Action.

We could

* point to the necessary Actions in the `actions` list, which probably are even re-usable across all the Events defined by such a Thing. The Event only has to define some parameters that have to be passed to the Action input.
* Treat these complex Events like Actions that are in turn pausable, cancable, etc. -- i.e., have Action and maybe Properties themselves. This would also allow for the modifiable subscriptions of @ToruKawaguchi 
   * Originally, we have been expecting that these Actions would be hypermedia-driven, i.e., their output is something similar to a TD, an ActionDescription, that the client can understand
   * Here it looks like we have to do it like a TD for existing devices: have the hypermedia controls out-of-band of the device responses, in a description somewhere else, but where?
     * Keep the TD flat and basically reference as above?
     * Allow hierarchy in the TD and allow Affordances within Affordance -- hello @draggett :)
     * We need to solve the order of when Affordances become valid, e.g., cancel or modifying only after subscribing.

Overall a pretty complex matter for the last 5 min of the WG...

**Comment by sebastiankb** [comment]
in today's TD meeting we decided to leave it at it is. It will just explained that subscription and cancellation is quite open to be designed and a guideline is provided in the protocol binding document. 

In a future version of the TD may address this more in detail.

**Comment by sebastiankb** [comment]
done.
There is now this kind of [information provided](https://w3c.github.io/wot-thing-description/#event-serialization-json) + [T2T use case sample](https://w3c.github.io/wot-thing-description/#t2t-event-example-serialization).

Please review/comment

**Comment by egekorkan** [comment]
This seems to be fixed by not adding input/output to events but by giving a note as pointed out by @sebastiankb
