### ISSUE TITLE
rename event keywords subscription and cancellation

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#403]
The keywords "subscription" and "cancellation" are unsymmetrical.

We should consider calling them "subscribe" and "unsubscribe"

**Comment by sebastiankb** [comment]
would be ok for me. Websub or in JavaScript also uses the term subcsribe and unsubscibe.

**Comment by mkovatsc** [comment]
In English, there is the word "subscription", but not "unsubscription"; the word used and in dictionaries is "cancellation", because you cancel a subscription.

You changed from nouns to verbs, which does not fit the overall concept for terms.

I would say the resolution of this issue more depends on how https://github.com/w3c/wot-thing-description/issues/398 is solved.
