### ISSUE TITLE
op values are not explained

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#405]
From Princeton Testfest:
op values such as readproperty are not explained anywhere in the document. We cannot assume that everyone understands what readproperty or readmultipleproperties mean.

Need further clarification on where to put such information

**Comment by mkovatsc** [comment]
I can explain them in the Architecture document where forms and the InteractionAffordances are introduced.

A bigger problem appears to me how we want to organize this in general. Looking at the analogous link relation types, these are basically registered types (see https://tools.ietf.org/html/rfc8288#section-2.1).

I am not sure we can go directly the full way and create an IANA registry. We could put some text that we define an initial list in the document and only upgrade to a registry when we see the op types growing or others also start using them.

An alternative story would be to treat them like the relation extension types, which are full URIs. While JSON-LD had the feature of shortening URIs to terms, JSON-LD is no longer the primary mechanism in TD. Thus, I think the first option with initial list is easier. (@vcharpenay comments?)

**Comment by mmccool** [comment]
I think we should also have two implementation examples for all of these... otherwise we run the risk of leaving out some critical structure needed for actual implementation.   Or rather, if I was on the TAG reviewing this document, I would say that ;)

**Comment by egekorkan** [comment]
> I think we should also have two implementation examples for all of these

The new version of AssertionTester will do exactly that ;)

**Comment by mkovatsc** [comment]
The `op` field is NOT mandatory. However, next to the form context, it is the key field for selection by the client and can also decides about other field values such as the method. I would strongly argue that it is mandatory.

Furthermore, the presence of a certain operation type indicates what operations are available. I think we already understood this for writable Properties, but still have the `observable` flag.

I recommend to:
* make `op` mandatory
* remove `observable` from PropertyAffordance and make the indication through the presence of an `observeproperty` operation type (i.e., in the interaction model Properties are always observable and it depends on the binding how it is implemented)
* define default values depending on the context
   * Properties: `readproperty writeproperty`
      * an `"op": "readproperty"` would remove the writable operation
      * `"op": "readproperty writeproperty observeproperty"` would be needed to add observablity
   * Actions: `invokeaction`
   * Events: `subscribeevent`

**Comment by sebastiankb** [comment]
will be addressed in next TD web meeting.

**Comment by sebastiankb** [comment]
we addressed Matthias' proposal only shortly in today's TD meeting (please check the minutes https://www.w3.org/2019/03/01-wot-td-minutes.html).

I'm not sure if I see the advantage. In the dominating cases, we have properties that are readOnly or read- and writable and comes with a single resource. For me, op would be kind of duplicated since readOnly and writeOnly are mandatory terms:

```
"properties": {
        "status" : {
            "readOnly": false,
            "writeOnly": false,
            "observable": false,
            "type": "string",
            "forms": [{
                "href": "https://mylamp.example.com/status",
                "contentType": "application/json",
               "op":  ["readproperty", "writeproperty"]
            }]
        }
```

The same is true for actions and events.

**Comment by mkovatsc** [comment]
It seems to me, it is not clearly understood what is going on here:

* `readOnly` and `writeOnly` are part of the data schema and only have logical implication on what interactions make sense.
* `op` is part of the hypermedia control and identifies the choices a client has.

For me, the hypermedia control is the primary information, hence redundancy would be created by `readOnly` and `writeOnly`.

Also when you implement: You may check `observable` and if it is `true`, you go look for the `observeproperty` form, I guess. But then it turns out, there is no such form. What is now the primary reason that you cannot observe? You just try to observe with the form that does not have `observeproperty`? Where did the principle of the server presenting choices to the clients go, if you just do inference or guesswork at the client?

What if the content type is `image/jpeg` where the data schema does not apply? Is there still `readOnly` and `writeOnly`?

**Comment by mkovatsc** [comment]
> The same is true for actions and events.

Actions only have one op type, so the default value always applies.

For Events, how do you select `subscribeevent` and `unsubscribeevent` without `op`?

**Comment by mjkoster** [comment]
I think it makes more sense that the data schema describes the data and the form describes the operations. Hints about the available operations embedded in the schema only make sense for properties. We get away with Actions because there is currently only one op possible, Events require op for unsubscribe. So it seems less redundant and more consistent to make op mandatory and make schema hints optional or even remove them.

**Comment by takuki** [comment]
In TD call on 3/8, it was agreed that readOnly/writeOnly are simply hints and clients should not be forced to depend on that. Form/op is the main thing that client can depend on. Compatibility with JSON-Schema is still a good thing, so readOnly/writeOnly should be preserved since they do not hurt.

Another suggestion is to make readOnly/writeOnly optional with no default values.

**Comment by takuki** [comment]
I modified TD spec according to the resolution.
