### ISSUE TITLE
JSON Schema too strict on @context contents

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#447]
The JSON Schema in Annex A is too restrictive and rejects valid @context annotations.

An example is the JSON-LD serialization of Example1, which fails the http://plugfest.thingweb.io/playground/ validation with:

    ------- New Validation Started -------
    JSON validation... OK
    :) Tip: Without base, each href should be an absolute URL
    X JSON Schema validation... KO:
    > data['@context'][0] should be equal to one of the allowed values, data['@context'][1] should be string, data['@context'][1] should be equal to one of the allowed values, data['@context'] should contain a valid item, data['@context'] should be string, data['@context'] should be equal to one of the allowed values, data['@context'] should match exactly one schema in oneOf

The @context element however is perfectly valid:

    "@context": [
        "http://w3.org/ns/td",
        {
            "@base": "urn:dev:wot:com:example:servient:lamp/"
        }
    ],

@egekorkan : A deeper analysis of the problem and schema showed that the "contains" rule in the following snippet of the schema is too strict - removing the "contains" section resolves the issue.
Can you please take a look?

    "definitions": {
        "context": {
            "oneOf": [
                {
                    "type": "array",
                    "items": {
                        "anyOf": [
                            {
                                "$ref": "#/definitions/url"
                            },
                            {
                                "type": "object"
                            }
                        ]
                    },
      ------> "contains": {
                        "type": "string",
                        "enum": [
                            "http://www.w3.org/ns/td"
                        ]
                    }
                },
                {
                    "type": "string",
                    "enum": [
                        "http://www.w3.org/ns/td"
                    ]
                }
            ]

**Comment by sebastiankb** [comment]
@egekorkan takes care on it

**Comment by egekorkan** [comment]
After digging this issue, it is about using `www` or not in front of the context. At the current state, playground accepts only if you do use `www` which is not the case in the snippet above. My initial reflex was to allow both but if you don't use `www` JSON-LD parser cannot find the context and you get a JSON-LD validation error. Instead of removing `contains`, you can try changing it like the following which will display a JSON-LD error:
```
"contains": {
  "type": "string",
  "enum": [
    "http://www.w3.org/ns/td", "http://w3.org/ns/td"
  ]
}
```
This little issue seems to be a _little_ bigger than initially thought. What is the expected behavior in such cases? From what I know, accepting both should be avoided as pointed out by MDN as well: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Choosing_between_www_and_non-www_URLs

**Comment by sebastiankb** [comment]
For my understanding both variants should be possible. I know, there are some kind of guidelines that provider should not operate via different domains the same content. I think JSON-LD does not make any limitations on that, right?

**Comment by vcharpenay** [comment]
I tried and jsonld.js does find the right context file, actually. @egekorkan, what did you try?

It is not a matter of allowing non-www URIs but a matter of having `w3.org` redirect to `www.w3.org`. And luckily, the W3C properly configured its front-end server, so redirection works here and the context can be found at both URIs.

> From what I know, accepting both should be avoided as pointed out by MDN as well: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Choosing_between_www_and_non-www_URLs

That page says the contrary: "It is good advice to do this since you can't predict which URL users will type in their browser's URL bar".

Now, to the issue: normative text should only refer to the _canonical_ URI, i.e., to the www URI. It is then up to libraries and runtime implementations to be more permissive and to adapt to actual usage. The JSON Schema in Appendix of the TD spec should therefore also include `http://www.w3.org/ns/td` only, from my point of view. It is up to you, @egekorkan, to maybe have "warnings" on the Playground.

**Comment by egekorkan** [comment]
It now accepts both. I have realized that with JSON-LD playground the parsing happens on key presses and sometimes does parsing before I put the dot at the end of the www. 
#512 solves this

**Comment by sebastiankb** [comment]
solved by https://github.com/w3c/wot-thing-description/pull/512
