### ISSUE TITLE
[Editorial] links are rendered splitted in Firefox

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#469]
This might be related to the template used for the spec but the Mozilla Firefox (version 65.0.1) the links like [BCP47] are rendered in a weird way. See the screenshot at the attached link. This issue is NOT present at Google Chrome or Opera
![image](https://user-images.githubusercontent.com/20195407/53624440-9a6cd100-3c00-11e9-87c8-58747810edfc.png)

**Comment by k-toumura** [comment]
This is caused by warning of ReSpec ("Normative references in informative sections are not allowed").
ReSpec make all sections informative if there is no section which ID is `conformance`.

To fix this, add id to conformance section and remove some overlapping text (see [ReSpec Wiki](https://github.com/w3c/respec/wiki/conformance)).

Architecture document has same problem and [my PR](https://github.com/w3c/wot-architecture/pull/103) will fix it.

**Comment by egekorkan** [comment]
This issue doesn't seem to be completely fixed, see screenshot from chapter 6
![image](https://user-images.githubusercontent.com/20195407/54807794-a76c6580-4c7e-11e9-9580-2c3d0bcf78f6.png)

**Comment by k-toumura** [comment]
PR #476 and #491 for this issue, are accidentally reverted...
