### ISSUE TITLE
Clearification about 'Simple' and 'Full' TD Serialization

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#539]
To make the definition more clearer to the reader what is intended about 'simple' and 'full' TD serialization and interpretation we should spend 2 sub-sections for better explanation.

Maybe we should also rethink about renaming 'simple' to, e.g., 'short'.

Please comment.

**Comment by sebastiankb** [comment]
we should also think about to have @context mandatory also in the simple form.

**Comment by egekorkan** [comment]
I support any detailed explanation of these terms since they appear at the very first example.

> Maybe we should also rethink about renaming 'simple' to, e.g., 'short'.

I don't think this is a good idea. *Simple* comes from simplifying something, which we do by assuming the default values. Maybe using *simplified* is better to give the meaning that simple is obtained from full and vice versa. 
Also short gives an impression as if someones shortened by removing something from the end.

**Comment by jmcanterafonseca** [comment]
I agree with @egekorkan "simplified" is a better term. "Simplified TD" and "Full TD" seem to be good terms for me. 

also I fully agree that some content for explaining the difference would be great. Currently I'm a bit lost :( as well

**Comment by takuki** [comment]
I also agree "simplified" is a better term. 

My understanding is that valid TDs that are short of qualifying the full form all belong to this "simplfied" class of TD.

**Comment by takuki** [comment]
@ashimura made some additional points as part of March 29 TD teleconference [minutes](https://lists.w3.org/Archives/Member/member-wot-wg/2019Mar/0033.html).

**Comment by sebastiankb** [comment]
currently I'm on a IETF meeting and there is the proposal to rename "simple" in "compact" and remove JSON-LD 1.1 in the "full" tab, both variants are based on JSON-LD 1.1!

Regarding @context as mandatory term in the simple/simplified/compact form we should clarify the usage of our itended TD [media type](https://w3c.github.io/wot-thing-description/#media-type-section) vs. the [profile usage in JSON-LD](https://w3c.github.io/json-ld-syntax/#iana-considerations)

**Comment by jmcanterafonseca** [comment]
I'm a bit lost. Json-ld 1.1 is not a Rec, and probably it will not be soon,
so if WoT intends to transition to Rec how that issue is going to be
managed? similar issue is with Json Schema

my understanding was that the Thing Description could be expressed in
Json-ld but Json was going to be the only normative representation ...

wrt compact vs simplified, well, we need to think about the semantics,
simplified means that some details are omitted, i.e information is not the
same, whereas compact means that the information is just the same but in a
less verbose format ...

**Comment by sebastiankb** [comment]
The original itention of the TD is to have an own format that can be also be identified by the [media type](https://w3c.github.io/wot-thing-description/#media-type-section) `application/td+json`. The text also says:

>The media type application/td+json MUST be also associated with the JSON-LD context http://www.w3.org/ns/td. That means that this media type can also be used for contextual identification of the vocabulary within a (simplified) TD instance that may omit the @context name term. 

In addition to @context, other terms can be omitted, such as contentType, op, etc., which is equivalent to having the values present with their default values.

In the meantime I think about to have @context always in the simplified/compact representation since this solve two problems:

1. **Self-Contained**: Identification that a document is a TD instance (useful when there is no media type supported by an underlying protocol such as MQTT)
2. **Versioning**: The TD namespace will be also used for the identification which TD specification version is applied (e.g., TD 1.0 vs. TD 1.1 vs. TD 2.0 etc)

This solve also the issue or misunderstunding about JSON based vs. JSON-LD 1.1 based serializiation. 

The question is, should we keep the media type application/td+json? I would say yes, as this would avoid some processing costs in limited environments.

**Comment by takuki** [comment]
@sebastiankb , would keeping "application/td+json" really help limited environments?
I think highly resource-constrained devices probably cannot process TD anyway.

**Comment by sebastiankb** [comment]
Simple and Full is removed in the TD spec. There is now a new sub-section about [omitting default values](https://w3c.github.io/wot-thing-description/#omitting-default-values).

**Comment by sebastiankb** [comment]
result was presented in today's call.
