### ISSUE TITLE
Fix urn:dev: in examples

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#552]
The currently used `urn:dev:wot:...` style is not valid. We need to fix to `urn:dev:ops:32473-<string-name>-<number>`.

See https://tools.ietf.org/html/draft-ietf-core-dev-urn-03

**Comment by egekorkan** [comment]
After reading this draft, here is what I understood:
* We are not allowed to use urn:dev:wot since wot is not allowed, for our case we should use `ops` like you also pointed out.
* After ops we can use 32473 as an example organisation number (analogous to example.com)
* Then we are free to use any product name, like `Lamp`, and give a random serial number, like `1234`

This means that we can have id's like: `urn:dev:ops:32473-Refrigerator-5002`, urn:dev:ops:32473-Lamp-1234`

One aspect that bothers me is that the draft says `This memo describes a new Uniform Resource Name (URN) namespace for hardware device identifiers.`, however in TD Spec we say `Describes a physical and/or virtual Thing (may represent one or more physical and/or virtual Things) in the Web of Things context.`. So according to the draft, something with a `urn` is a physical device, in the TD spec, since `id` is a `urn` and is mandatory, TDs represent physical devices.

(I am not sure if what bothers is actually a problem)

**Comment by mkovatsc** [comment]
If that bothers you, just pick any other valid URI instead of the currently invalid ones ;)
However, I cannot follow your conclusions about applicability of dev URNs when you want to make a lamp example...

**Comment by egekorkan** [comment]
> If that bothers you, just pick any other valid URI instead of the currently invalid ones ;)

I think we will simply do that for now.

>  However, I cannot follow your conclusions about applicability of dev URNs when you want to make a lamp example...

What I wanted to say that, until this issue, I was assuming that the `id` term was used to give a unique id to the TD and not the physical Thing. After your issue, I have seen that the spec actually says that `id` is for the physical Thing, which conforms with the dev urn draft. However, the spec doesn't really say that a TD is bound to a physical device, there are multiple occasions where it says `physical or virtual entity`. So the problem would not be for the examples but for the general understanding of how TD is used.

**Comment by mkovatsc** [comment]
> I was assuming that the id term was used to give a unique id to the TD and not the physical Thing

This is a severe discrepancy. `id` is defined for the Thing, not the TD. There can be many different TD representations for the same Thing (e.g., different authorization level of the TD reader, or a basic version on the device and an enriched version with more metadata in the cloud). `id` would be the identifier to correlate these.

> physical or virtual entity

Virtual entity is defined as the composition of one or more Thing. So there is always a physical root, which could be a room or place, which is still physical. It is about *Things* afterall.

And if there is a case where dev URNs really do not apply, do not use them. There is no mandate to use dev URN, they are just a useful URIs for identification and we use them in examples.

**Comment by egekorkan** [comment]
> And if there is a case where dev URNs really do not apply, do not use them. There is no mandate to use dev URN, they are just a useful URIs for identification and we use them in examples.

I think this is good point since I had assumed that we use only dev URNs. We should then put some non dev URN URIs examples?

**Comment by egekorkan** [comment]
I have proposed a fix in #592

**Comment by sebastiankb** [comment]
thanks

**Comment by egekorkan** [comment]
> This is a severe discrepancy. id is defined for the Thing, not the TD. There can be many different TD representations for the same Thing (e.g., different authorization level of the TD reader, or a basic version on the device and an enriched version with more metadata in the cloud). id would be the identifier to correlate these. 

I actually really liked this note and I have tried to find something similar in Thing Description and Architecture document but haven't managed to do to so. I think putting such an explanation would strengthen why `id` is a mandatory term.
