### ISSUE TITLE
5.4.7 CertSecurityScheme - Pre-shared key identity

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#553]
5.4.7 is for Certificates, but description in table says Pre-shared key identity.

**Comment by mmccool** [comment]
Well... actually, the table description is for the "identity" field, saying it is for the "Pre-shared Key Identity".    This field is used in multiple schemes, including both PSK and certs.    However, we might want a description (useful for all places where "identity" is used) that sounds less like a mistake.  Maybe simply "Pre-shared identifier" since in the case of public keys it is the identifier that is preshared, not the key...

**Comment by mmccool** [comment]
See PR https://github.com/w3c/wot-thing-description/pull/589 for a new definition.

**Comment by mkovatsc** [comment]
The PSK identity is used to indicate which PSK to use. I do not see this reflected by the cryptic new description. It sounds even like the identity would hold the credentials for gaining access...

**Comment by mkovatsc** [comment]
@mmccool could you improve the text?

> Identifier validating access by providing information unique to the resource.

Maybe:

Unique name referring to a particular secret for gaining access.

**Comment by mkovatsc** [comment]
Note it is for both Classes having `identity`.

**Comment by mmccool** [comment]
I updated the definition in PR https://github.com/w3c/wot-thing-description/pull/655.   It is now
"Identifier providing information unique to the resource which can be used for selection or confirmation."
I wanted to avoid the word "access" since it is not actually a credential, just a "selector" (to pick from several keysin PSK) or a "confirmer" (for example, when you get a cert from a website, it is the base URL you got the cert from, signed inside the cert, so you can confirm the cert is valid).
