### ISSUE TITLE
Serialization assertions in Section 5

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#615]
Section 5.3.1.1 contains the following assertions, which partially conflict with serialization assertions in Section 6. Furthermore, the description for the `@context` term does not really match what we do:

> JSON-LD keyword to define short-hand names called terms that are used throughout a TD document.

We use it to define a specific context file, include other namespaces that must have a prefix, and to set the default language...

> The mandatory context definition of the string "https://www.w3.org/2019/wot/td/v1" MUST be the first item in the @context array. The mandatory context definition MAY be followed by one or more context definitions as strings or objects, and/or a default language definition as an object.

Misses the string-only type. Does not fit the `@context` term description in the table.

> As suggested in JSON-LD [json-ld] specification, if a context definition is a string, it SHOULD be a dereferenceable URL. Likewise, if a context definition is an object, it SHOULD be a map of namespaces, in which keys are namespace prefixes. Each optional namespace specified in the @context array of a Thing MUST be bound to an unique prefix.

Why is this here when there is a Context Extension section?

> In the @context array, the optional default language that is used throughout a TD document is defined within an object as a member with a key @language whose value MUST be a string representing a [BCP47] language code. 

Needs text on the script subtag, see #598

**Comment by mmccool** [comment]
OK, I see we do talk about '@language' here.   However, I think in order to deal with the details of this we need to add a "Default Language" section to the Context Extension section.   So I will move this assertion to that section in my PR addressing this issue.

**Comment by mmccool** [comment]
Ack, never mind, I see in PR https://github.com/w3c/wot-thing-description/pull/610 you took out the assertions from section 6.2.1.   OK, in that case, I will add the text direction stuff to section 5.3.1.1.

**Comment by mkovatsc** [comment]
We can discuss where it should go. The main point is, that we need to coordinate this, as at the moment, we mixed model with serialization assertions.

We could put all of this in "6.2.10 title(s) and description(s)" -- maybe even rename it to "Human-readable Metadata" and make it 6.2.2, directly after "Thing Root Object", to have a clear section for i18n implications.

**Comment by mkovatsc** [comment]
See also review of #620

**Comment by mmccool** [comment]
In my language text-direction PR () I dealt with some of this.   I left certain assertions in the Thing section (rules for inferencing text direction from the default language), added some assertions to MultiLanguage, and moved some assertions specifically having to do with serialization to Section 6 (the assertion I added that strings should be processed separately and that protocol negotiation may be used to determine the default language).   However, I don't think text direction is a serialization concern.   Specifically, text direction does not change the order of bytes in the JSON file.  It changes how the string is *interpreted* when it is displayed.   So you need the direction and language information associated with the string somehow when it is stored in a database.   Because of that, IMO language and text direction is part of the information model.

**Comment by mmccool** [comment]
I now also have a separate PR (well, a PR on a branch used for another PR) to deal with the annoying special case of the default language for "name" and "support" potentially having to be different than that for "title" and "description".   See notes under https://github.com/w3c/wot-thing-description/pull/620

**Comment by mkovatsc** [comment]
See comment in #630 -- please avoid this complexity.

In general, the split between Section 5 and 6 assertions looks good now.

**Comment by mkovatsc** [comment]
#620 merged, issue addressed.
