### ISSUE TITLE
Modify list of formats in token SecurityScheme to allow for extensions

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#618]
There is a `format` term for two security schemes, which has a default value. That `format` is, however, different from the DataSchema format.

In DataSchema, `format` must be optional.

**Comment by mkovatsc** [comment]
We might want to consider to rename `format` in the two security schemes.
Also we should consider including CWT: https://tools.ietf.org/html/rfc8392

**Comment by mkovatsc** [comment]
I would recommend to rename to `token`, so there is no conflict with JSON Schema's `format`.

Also, we could fix the description:
> Specifies *the* format of *the* security authentication information (one of jwt, jwe, or jws).

**Comment by jmcanterafonseca** [comment]
could it be `tokenFormat`

**Comment by vcharpenay** [comment]
> In DataSchema, format must be optional.

This has just been fixed. You may want to rename the issue to mention it's a security topic.

**Comment by mkovatsc** [comment]
But it is fixed anyway, no?
Do we need to decide between tokenFormat and token? I prefer shorter.

**Comment by jmcanterafonseca** [comment]
token could be misleading, we are referring to the token format not to the token itself

**Comment by mkovatsc** [comment]
Also true... :)

**Comment by mmccool** [comment]
We have several other terms in SecurityScheme that overlap with other terms elsewhere.   In general these terms are defined contextually, eg the terms used in SecurityScheme override those used outside.  There are several other places (not only in SecurityScheme) where terms and their defaults are defined contextually, so if we worry about this here, should we also change all other terms that are defined contextually?  I would rather not change this at this point, since if it is changed we would also have to update tests, etc.   Note that we have already dealt with defining contextual validation/testing at this point so it's a non-issue from that point of view.

**Comment by mmccool** [comment]
In general, at this late date, I would lean towards "if it ain't broke, don't fix it".

**Comment by mmccool** [comment]
Also, "token" is taken (it is the URL of the token server in OAuth).

**Comment by mmccool** [comment]
A final consideration is that "format" is consistent with OpenAPI.  However, we already break consistency in several other ways, for example, by using "token" instead of "tokenURL" since I wanted to avoid "URL".   Still...

**Comment by mkovatsc** [comment]
Considering CWT is becoming more popular, I would remove the default values for token format. We can then leave it as "format" as well.

**Comment by mmccool** [comment]
The list of allowed values for "format" has the same issues as "scheme", in that it does not allow for extensions if we say "one of".   At the same time, we should specify certain terms for known formats, so that people don't use different spellings to mean the same thing.   My recommendation here is that we remove the "one of" typing (at least, to allow extensions) and make a list of acceptable format definitions in another document we can easily update (for example, the Best Practices document, indirectly referenced from the WoT Security and Privacy Considerations doc).

If we do want to give a list in the doc, it should probably be in a separate sentence after the table.  Unless there is a standard we can reference; are there IANA names for these?   I will check... and will try to make a PR to address this this afternoon (therefore marking this as WIP).

**Comment by mmccool** [comment]
I also renamed this issue since we resolved not to change the name but do need to clarify the default values.  I looked it up an apparently there is an "application/cwt" mediaType registered for CWT: https://www.iana.org/assignments/media-types/application/cwt.   One option here would be to say appropriate mediaTypes can be used to identify the format of the token, although we might want to be more restrictive (eg text/plain is not an acceptable token format).   I think I will just use a list of short names and cite the IANA media types for each, and say that extensions MAY define their own formats.

**Comment by mmccool** [comment]
See PR https://github.com/w3c/wot-thing-description/pull/655.   This just adds "cwt" to the current list of allowed values without restructuring.   This actually needs a lot more work; in particular, I should add normative references to the specs for JWT, CWT, etc.   I'll mark the PR as WIP and see how much I can improve it before we have to call it.

**Comment by mmccool** [comment]
See PR https://github.com/w3c/wot-thing-description/pull/655

**Comment by mmccool** [comment]
I also just made the list of formats and algorithms extensible by using "e.g." rather than "one of", and added an explicit assertion that extension is permissible.

**Comment by mkovatsc** [comment]
Added review(s)
