### ISSUE TITLE
Specification of @type

### ISSUE THREAD

**Issue by vcharpenay** [w3c/wot-thing-description#698]
The [TD information model](https://www.w3.org/TR/wot-thing-description/#overview) includes an `@type` for the classes `Thing`, `InteractionPattern`, `DataSchema` `SecurityScheme` only.  However, [Section 7.1](https://www.w3.org/TR/wot-thing-description/#semantic-annotations) does not refer to specific classes in its explainer on how to use `@type`.

In particular, annotations for the class `Form` may prove useful, e.g. with sub-classes of [`saref:Command`](http://ontology.tno.nl/saref/saref_Command.html) or schema.org's [`schema:Action`](https://schema.org/docs/actions.html).

**Comment by vcharpenay** [comment]
One solution would be to remove `@type` from all class definitions in Section 5. Another solution is to add `@type` only to `Form`  (and maybe `ExpectedResponse`?)

I would favor the former solution. It is never obvious when designing a knowledge base what objects should carry type information.

**Comment by mkovatsc** [comment]
Since we define an information model that can also be used without JSON-LD, I think it is good to list `@type` in the same manner as other fields, in particular where we encourage to use it (Thing itself, affordances, data items).

Technically, any class may have additional fields from TD Context Extensions, which would include `@type`. 

For this TD version, we cannot change the normative parts anymore, which includes the Class definition tables. We should, however, add some more explanation to the non-normative section 7, in particular clearly stating that every class may have an `@type` field.

**Comment by mkovatsc** [comment]
We now have an updated Example 28.
Also see https://github.com/w3c/wot-thing-description/issues/769
