### ISSUE TITLE
Specify the expected type of JSON TD structures

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#7]
The current [Thing Description](https://w3c.github.io/wot-thing-description/) is rather vague w.r.t. the expected type of given information tuples.

For example it is not super clear whether @type, @context, and others are meant to be a string, an array of strings, or both (e.g., `"@context":["http://w3c.github.io/wot/w3c-wot-td-context.jsonld"]` vs `"@context":"http://w3c.github.io/wot/w3c-wot-td-context.jsonld"`). For interoperability it would be good to have a clear statement.

Also, when it comes to implementation simplicity it would be good to specify "one" type compared to several choices by allowing to much flexibility.

Any thoughts/opinions?

**Comment by draggett** [comment]
The current draft reads like an introduction to a serialisation of interaction models, rather than as a specification for a serialisation and programming language independent interaction models. In other words, it is not fit for purpose.

Compare for example my [formalisation of interaction models as Linked Data](https://github.com/w3c/wot/blob/master/proposals/dsr-td/td-draft-spec-dsr.md).  That defines the core set of data types, an extension mechanism for application defined data types, and the interaction model in terms of properties, actions and events.

It splits off the formal specification of links from the interaction model to semantic models. as well as metadata for security, access control, privacy, binding templates etc. This makes senses since we are less well advanced in our understanding of the requirements and potential solutions.

**Comment by takuki** [comment]
I agree with @danielpeintner  to specify the type in a manner that allows to minimize code footprint.  By doing so, it makes comparing two TDs easier for equality without requiring canonicalization.

**Comment by danielpeintner** [comment]
FYI: @mjkoster mentioned during the last TD call that OCF explicitly requires that certain values are to be represented as arrays (even if an instance has only a single value), see https://openconnectivity.org/draftspecs/OCF_Core_Specification_v1.0.0.pdf

**Comment by takuki** [comment]
On the current practices document side, I made suggested changes accordingly to make it always an array.
https://github.com/w3c/wot/pull/321

**Comment by sebastiankb** [comment]
I think, the common agreement is to follow the array structure for that kind of terms. I will close this issue.
