### ISSUE TITLE
[At-Risk] Implementations of OAuth2SecurityScheme needed

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#730]
The OAuth2SecurityScheme is currently at risk.
- 2 full implementation (with all sub-features, including the various flows) are needed

**Comment by mmccool** [comment]
@mmccool to create a PR that limits support to the code flow.   We have a code flow implementation from Panasonic, both a producer and a consumer, and also a simulator and real device.  @ToruKawaguchi  to work on this.

**Comment by yamagile** [comment]
@mmccool , I created the [PR](w3c/wot#819) on this issue. It makes some assertions passed like below:

---

pass: 0->2

* td-arrays_scopes
* td-security-oauth2-code-flow
* td-vocab-authorization--OAuth2SecurityScheme
* td-vocab-flow--OAuth2SecurityScheme
* td-vocab-in--APIKeySecurityScheme
* td-vocab-name--APIKeySecurityScheme
* td-vocab-refresh--OAuth2SecurityScheme
* td-vocab-scheme--SecurityScheme_apikey
* td-vocab-scheme--SecurityScheme_oauth2
* td-vocab-scopes--Form
* td-vocab-scopes--OAuth2SecurityScheme
* td-vocab-token--OAuth2SecurityScheme
* td-vocab-authorization--PoPSecurityScheme (This may be a bug of the assertion tester because I have no change for PoPSecurityScheme.)

---

pass: 1->2

* td-default-flow

---

pass: 0->0

* td-security-oauth2-implicit-flow
* td-security-oauth2-password-client-flow
    * **note**: There is only code flow implementation from Panasonic.

**Comment by mkovatsc** [comment]
We have implementations for OAuth 2 code flow.
Ideally, we only drop the unimplemented sub-features, but keep the security scheme `oauth2` for code flow.

**Comment by sebastiankb** [comment]
@mkovatsc 
> Ideally, we only drop the unimplemented sub-features

What does it mean? Do we have to remove some terms from the https://w3c.github.io/wot-thing-description/#oauth2securityscheme ?

**Comment by mkovatsc** [comment]
We have no positive implementation report for the implicit, password, and client flows. Hence, to my understanding, the corresponding assertions and Vocabulary Terms need to be removed:

* For the implicit flow authorization MUST be included.
* For the password and client flows token MUST be included.
* `string (one of implicit, password, client, or code)` -- in the Type row for the `flow` field of OAuth2SecurityScheme

**Comment by takuki** [comment]
The flow field currently has a default value of "implicit".
Since "implicit" (which was at risk) goes away and "code" is now the only possible value, this default value needs to be replaced with "code". (section 5.3.3.11)

**Comment by mlagally** [comment]
We support the code flow in the IOT-CS.
I have created a corresponding TD at: https://github.com/w3c/wot/pull/829

**Comment by mkovatsc** [comment]
> We support the code flow in the IOT-CS.

The TD is for client flow, so I guess that is meant. We still would need a second implementation to keep it.

> this default value needs to be replaced with "code"

I think a good lesson learned was that picking a default value for the flow is not a good idea. This is further confirmed by Oracle providing client flow instead of code. We should drop the default value and make `flow` mandatory.

**Comment by mlagally** [comment]
@mkovatsc You're right of course - we support the client flow.

**Comment by mlagally** [comment]
@sebastiankb: Siemens uses the client credentials grant in their Mindsphere product:
https://developer.mindsphere.io/apis/core-oauthauthorizationserver/api-oauthauthorizationserver-api-swagger-3-1-0.html

Do you think the Oauth2 client grant flow could be supported by a sample TD from Siemens?

**Comment by benfrancis** [comment]
FWIW Mozilla's WebThings Gateway implementation now provides security & securityDefinitions metadata using the oauth2 security scheme (since https://github.com/mozilla-iot/gateway/issues/1951).

This may not fulfil your testing requirements though because despite some further convergence recently the Thing Descriptions still don't validate with the thingweb validator, and the security metadata isn't really useable due to the issues discussed in https://github.com/w3c/wot-thing-description/issues/757 (the Thing Description is authenticated).

**Comment by mmccool** [comment]
The "PR Needed" label is for a PR to make flow mandatory and remove the default value.   Even if we do such a PR, this issue can't technically be closed until we have OAuth implementations for all flows.  We can, however, decide to remove flows for which we have an inadequate number of implementations when we go to PR and can then mark this issue with the "Defer to next TD version" label.

**Comment by mmccool** [comment]
Re-reading the above I see that both Panasonic and Siemens have implementations for the "code" flow.   So OAuth2 itself will not be at risk.  It seems Oracle has an implementation for the "client" flow, but I don't know if we have a second one; so that flow may be at risk.   However, I still think making "flow" mandatory and removing the default is a good idea... I am working on a PR for that now.

**Comment by mmccool** [comment]
It would be good to know what "flow" Mozilla uses.   If both Oracle and Mozilla use the "client" flow, and we can get the Mozilla TDs to validate, then we might be able to remove one more flow from the at-risk category...

**Comment by sebastiankb** [comment]
@mmccool are there some news regarding this issue?

**Comment by sebastiankb** [comment]
we have enough oath2 implementations, however, not all flows features were supported. This will be addressed in the next version.

**Comment by mmccool** [comment]
given that this issue was left-over from the TD 1.0 release, I propose closing it.

**Comment by sebastiankb** [comment]
ok also from my side. Going to close
