### ISSUE TITLE
Start on experimental JSON Thing Description serialization (cont.)

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#76]
this is the continuation of the PR [#363](https://github.com/w3c/wot/pull/363) of the wot repository and its discussion.

**Comment by draggett** [comment]
I might as well offer some suggestions. I have consistently proposed the use of simple JSON that appeals to web developers since the start of the WoT IG back in 2015.  I have shown that this can be used with a flexible set of data types and can be mapped to RDF using a simple algorithm together with linked contexts that map names to RDF URLs. It scales nicely to allow for named application defined data types, compound data, arbitrary metadata, streams and so forth. The proposal is described in detail at:

 * https://github.com/w3c/wot/tree/master/proposals/dsr-td

There are lots of examples online at:

* https://www.w3.org/WoT/demos/td2ttl/
* https://www.w3.org/WoT/demos/td2ttl/oic.html
* https://www.w3.org/WoT/demos/td2ttl/m2m.html

These use JavaScript libraries to translate the JSON to RDF and to generate a graphical representation using the JavaScript port of GraphViz running in a service worker.

Much of the focus in the IoT is on the protocols at the network edge. I think that W3C is better positioned to focus on enabling open markets of services running on application platforms on the Internet.  For this we only need to deal with a small set of Web protocols including HTTP and WebSockets. The myriad IoT communications technologies and protocols can be accessed via gateways that also act as application platforms. This greatly simplifies the need for communications metadata as part of thing descriptions. I have shown that this works in practice with a NodeJS implementation of an application platform, together with JavaScript libraries for use in Web pages, where applications provide an HTML based user interface over the integrated HTTP server.

The proposal from Mozilla and EVRYTHNG is broadly speaking a subset of my proposal. The differences mainly relate to different ideas about what's needed for communication metadata.

I look forward to the interaction patterns and use cases that I think Carsten volunteered to provide as I am confident that these will help to explicate the details of the assumptions for the thing interaction models, and the corresponding metadata. In general, I believe that the WoT IG's failure to work on an extensive suite of use cases has held us back when it comes to convincing companies of the value of the Web of Things and the benefits from becoming actively involved in the W3C standardisation work.

**Comment by benfrancis** [comment]
> Much of the focus in the IoT is on the protocols at the network edge. I think that W3C is better positioned to focus on enabling open markets of services running on application platforms on the Internet. For this we only need to deal with a small set of Web protocols including HTTP and WebSockets. The myriad IoT communications technologies and protocols can be accessed via gateways that also act as application platforms. On such gateways, applications that expose things can use platform libraries to deal with the IoT technologies in a way that is hidden from applications that act as consumers of things. This greatly simplifies the need for communications metadata as part of thing descriptions.

+1

I also agree that a documented set of intended use cases could help frame this discussion.

**Comment by domguinard** [comment]
>I also agree that a documented set of intended use cases could help frame this discussion.
From the discussions with the team in the past few TDs calls it indeed seems like the use cases are key. My take is that with the Mozilla-EVRYTHNG-Ambrosus proposal (http://w3c.github.io/wot/proposals/json-td/) just like the Web Thing Model proposal of 2015 (https://www.w3.org/Submission/wot-model/), we are focusing on simple use cases. In particular looking at the consumer IoT, vs the industrial IoT that others are looking at in this WG.

This is certainly a key way to profile the proposal: a simple(r) thing description for simple use cases. It perhaps won't serve the purpose of industrial machines on a factory floor but will serve very well a vast number of smart home and consumer IoT use cases. Similar models have been working successfully for years by the likes of Google, Apple and EVRYTHNG (and now Mozilla) on millions of smart home devices.

**Comment by sebastiankb** [comment]
non active issue anymore. Latest TD assumption has a simplified form and can be defined idiomatic JSON.
