### ISSUE TITLE
Dead links in the implementation report

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#775]
In the implementation report there are the following links that results with 404 when clicked:
* http://www.w3.org/TR/ at line 183
* http://www.w3.org/TR/2019/PR-xxx/disp.html at line 210

I am fixing the first one but no idea where to direct the second one

**Comment by mmccool** [comment]
OK, but be aware you need to edit testing/inputs/templates/report.html, not testing/reports.html.   The latter is generated by the "npm run assertions" script and any changes will be overwritten.   I also thought Matthias had made some of these changes already.   It would help if you said what text goes with the above links.

**Comment by egekorkan** [comment]
Fixed first one in #776 , any idea where the second one should point to?

**Comment by mkovatsc** [comment]
Second one, we only have when doing the PR transition.

@ashimura could you please clarify how exactly we get this? I assume we send the PR transition request and then will be informed about this PR handle. However, the report is part of the transition request, no? So chicken-egg...

**Comment by mkovatsc** [comment]
I fixed the remaining links (actually I removed the base URI complication all together, since relatively pointing to index.html on github.io does not make much sense):

https://w3c.github.io/wot-thing-description/testing/report.html

I also removed the mentioning of Security Best Practices.

@mmccool, @ashimura, could you please check if the [out of scope](https://w3c.github.io/wot-thing-description/testing/report.html#out_of_scope) statement makes sense? The previous security/protocol statement was not very enlightening anyway to me...

**Comment by mkovatsc** [comment]
As discussed in the chairs call:
* Out-of-scope can stay that way
* http://www.w3.org/TR/2019/PR-xxx/disp.html can point to the GitHub Issue tracker; I will create a corresponding label

**Comment by mkovatsc** [comment]
Done.
