### ISSUE TITLE
Move MQTT (and CoAP) example to Protocol Binding Templates document

### ISSUE THREAD

**Issue by takuki** [w3c/wot-thing-description#786]
In TD call on 6/28, it was suggested to move MQTT (and also CoAP) examples to Protocol Binding Templates document.

**Comment by sebastiankb** [comment]
I would stick to my above opinion and would recommend closing this issue.

**Comment by sebastiankb** [comment]
we should check if the examples are aligned with the vocabulary as provided in the binding document. 
@egekorkan will take care of it

**Comment by egekorkan** [comment]
Comments regarding the examples.

MQTT:
- the event name is `lightSensor` is quite funny, I would suggest renaming it to brightness and also adapting the comment accordingly.
- It would be nice to add the `"mqv:controlPacketValue": "SUBSCRIBE" to the form

CoAP:
- Except the event form, everything looks good. For the `subprotocol` we use `"cov:feature":"Observe" in the bindings spec [here](https://pr-preview.s3.amazonaws.com/w3c/wot-binding-templates/pull/82.html#coap-vocabulary). I am not very satisfied with this way but the subprotocol is also weird since with a single request it is possible to observe a resource so there is no other protocol semantics really involved.

**Comment by sebastiankb** [comment]
>the event name is lightSensor is quite funny, I would suggest renaming it to brightness and also adapting the comment accordingly.

yes, you are right. I changed this in the pr #862 

>It would be nice to add the `"mqv:controlPacketValue": "SUBSCRIBE" to the form
I would expect as a default assumption for events. So it can be skipped, right?

>Except the event form, everything looks good. For the subprotocol we use `"cov:feature":"Observe" in the bindings spec here. 

I had a quick chat with @ektrah: subprotocol is a concept of the TD and its intention is to indicate the subprotocol via a used main protocol. So, its absolute ok to use subprotocol here.

**Comment by sebastiankb** [comment]
PR was merged.
