### ISSUE TITLE
Improve Explainer with User-Oriented Use Cases

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#805]
As requested during TAG review, improve the explainer with end-user oriented use cases and requirements.

**Comment by takuki** [comment]
The below figure is from IIC [IICF](https://www.iiconsortium.org/IICF.htm) (Connectivity Framework).

From the end user's point of view, a newly purchased IoT device is not very likely to interoperate with other devices unless all the devices are using the same ecosystem because of this connectivity challenge.

One way to describe end-user benefit is that WoT introduces a single metadata framework (TD) to cover  diverse ecosystems uniformly so that a newly purchased IoT device is more likely to interoperate with other devices from other ecosystems.

![IIC_PUB_G5_V1 01_PB_20180228](https://user-images.githubusercontent.com/12631135/63982277-c9acaf80-ca76-11e9-86ee-56793a64d7d6.png)

**Comment by sebastiankb** [comment]
@mmccool what is the status?

**Comment by sebastiankb** [comment]
this issue will be addressed for the v1.1

**Comment by sebastiankb** [comment]
TD1.1 has a [new improved explainer](https://github.com/w3c/wot-thing-description/blob/main/explainer/Explainer11.md).
