### ISSUE TITLE
Implementation report uses the words client and server

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#815]
There are multiple assertions with ids starting with server and client (mainly in the manual validation section) in the [implementation report](https://w3c.github.io/wot-thing-description/testing/report.html#manual_validation_results) even though these words are actually never used.
Small but still, there is also [this paragraph](https://w3c.github.io/wot-thing-description/#sec-security-consideration-TD-tampering) doing the same mistake.

**Comment by sebastiankb** [comment]
at least we should change this in the spec. @mmccool can you do a PR?

**Comment by mmccool** [comment]
I can fix the wording in the implementation report easily.   Fixing the ids though is a PITA since we would have to coordinate the updates in the AssertionTester as well as in the TD document itself (although these changes will not be visible in the rendering).    I have marked this as "PR needed" but suggest that TWO PRs are needed: one that fixes the wording (I can do this one...) and another that fixes the IDs (I would nominate Ege to do this, so he can coordinate with an update to the AssertionTester).

**Comment by mmccool** [comment]
Another and simpler resolution to this would be to define the terms "client" and "server" in the implementation report as "network roles".   Actually, the IR ALREADY includes these definitions in section 6:

"Each implementation represents a working system that either exposes or consumes at least one WoT Thing Description. Implementations that expose a Thing Description act as a network server with an interface as described in the Thing Description it exposes. Implementations that consume a Thing Description act as a network client and issue network requests consistent with the target Thing Description. In some cases a given implementation may be used for multiple Things and a single Thing may also act as both client and server on multiple interfaces."

It would be really awkward to remove these at this point so I suggest we don't.

**Comment by sebastiankb** [comment]
In the TD spec there is this paragraph

>This ensures that the Consumer and the **server** are both sure of the identity of the other party to the communication. This is also necessary in order to deliver TDs only to authorized users. 

'server' should be Producer, right?

**Comment by egekorkan** [comment]
I always tend to think of MQTT where the exposer and consumers are both MQTT clients. The only server-like entity is the broker.

**Comment by sebastiankb** [comment]
What does it mean, shall we keep the text?

**Comment by mmccool** [comment]
I think what I should do is add some clarifying text that regardless of what the protocol does, the "client" is the Consumer and the "server" is the Thing described by the Thing Description.   I already have some definitions in the text, but the one for "server" is not quite right anyways because it talks about the "device exposing at Thing Description" which is only true for self-describing Things.  So it needs some cleanup.

I would be willing to fix the text if someone else (Ege?) does the PR to clean up all the ids and also cleans up the test cases.   I would suggest client->consumer and server->thing.   The latter should NOT be "producer" because (a) we have not defined it (b) the producer of a TD may not be the same entity that responds to the interactions defined in that TD.

**Comment by mmccool** [comment]
I can add some wording changes to PR https://github.com/w3c/wot-thing-description/pull/823.
I think for practical reasons we should keep "client" and "server" (we really really don't want to have to change all the IDs and break the tooling at this particular point in time) but be careful about how we use them and make it clear that we are using them in the specific meanings defined in the IR document.

**Comment by sebastiankb** [comment]
issue was solved by PR #823.
