### ISSUE TITLE
(Minor) CR2 Release Candidate comments

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#833]
Please find below some very minor comments for the CR2 Release Candidate.

Note: There are no blocking issues. I just found some minor bugs I struggled over while re-reading the document.

## 1. Introduction

`securityDefinition` is highlighted as code but it should be either `securityDefinitions`
or code highlighting should be removed. There is no singular term `securityDefinition`.

## 5.1 Overview

Fig 1. states that `security` is [0..1] and `securityDefinitions` [1..*]

In 5.3.1.1 in the column "assignement" both are marked as mandatory?

## 5.3.3.6 BearerSecurityScheme

Two dots in first para "extensions.."

## 5.3.3.10 PoPSecurityScheme

Same two dots in first para "extensions.."

## 9.1 Context Dereferencing Privacy Risk

In first para we speak about 
"Deferencing the" (shouldn't it be "Derefencing the")
and
"by such deferences" (shouldn't it be "by such derefences")
?

## 9.4 Globally Unique Identifier Privacy Risk

"have a a very low" --> "have a very low"

## E.1 Changes from First Candidate Recommendation

"caused both froms to" --> "caused both forms to"

**Comment by sebastiankb** [comment]
Thanks for the comment. All points can be addressed before the PR transition. Regarding the bug in Figure 1 (`security` should be mandatory), I have already fixed it for CR2.

**Comment by sebastiankb** [comment]
@danielpeintner provides a PR and checks with @mmccool about the section 9.1

**Comment by danielpeintner** [comment]
I created a PR for the remaining issues.
see https://github.com/w3c/wot-thing-description/pull/838

Note: no "npm run render" called and hence no update to index.html (do not have linux handy)

**Comment by mmccool** [comment]
5.1 security is mandatory at the top Thing level, but optional at levels below that.  So the confusion is probably due to the fact that we DO want it optional at the Form level.  securityDefinitions are currently mandatory since you have to have a definition to use it in security (which is mandatory...).  But in a future revision, if we allow the use of “inline” SecurityScheme objects in security, then securityDefinitions should be made optional.

As for “dereferencing” the point is that it is the *action* of getting the payload pointed at by the URL that is the problem.  If a URL was a pointer, we would dereference the pointer to get the thing pointed at.  Simply processing a URL as a reference, for example using it as a unique name for a concept without fetching the thing referenced, does not pose a security risk.

I suppose we COULD change the term to “Fetching” or something to be clearer.  I personally think Dereferencing is clear enough.  I think “Referencing” is not clear, since it does not clearly include the idea of fetching the referenced content.

**Comment by mmccool** [comment]
Oh, I see the dereferencing thing is just a typo.  Never mind, yes, please fix those.  Should be “dereferences”.

**Comment by takuki** [comment]
With PR #838, all points were addressed.

**Comment by mjkoster** [comment]
Sorry, I meant to make this note after last week's discussion.

The point I was trying to make is that "dereferencing" is the act of taking a reference, or pointer, and obtaining the referent, or object, that is pointed to by the reference. 

I haven't seen the word "dereference" used as a noun to describe the object that is pointed to by a reference. I believe the most correct word would be "referent", and the plural would be "referents".

IOW, a reference points to a referent, and dereferencing returns the referent
reference -> referent 

I recommend changing the term "dereferences" to "referents" in the sentences where we are referring to the noun.

**Comment by danielpeintner** [comment]
> I recommend changing the term "dereferences" to "referents" in the sentences where we are referring to the noun.

@mmccool ?

**Comment by sebastiankb** [comment]
@mmccool will rename "dereferences" to "fetch" and provide a PR

**Comment by sebastiankb** [comment]
PR was merged.
