### ISSUE TITLE
min and max vs. minimum and maximum

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-thing-description#84]
In the [JSON-TD proposal](https://w3c.github.io/wot/proposals/json-td/index.html), [values](https://w3c.github.io/wot/proposals/json-td/index.html#value-object) associated with properties, actions and events can have `min` and `max` properties to define the minimum and maximum possible values of a number.

[JSON Schema](http://json-schema.org/examples.html) uses the terms `minimum` and `maximum`. Do we agree on using `minimum` and `maximum`?

**Comment by sebastiankb** [comment]
> JSON Schema uses the terms minimum and maximum. Do we agree on using minimum and maximum?

Yes :-)

**Comment by mkovatsc** [comment]
Yes. I think we even agree on using JSON Schema for defining types. The only catch is that we want to exploit JSON-LD processing and Linked Data reasoning, and hence took the JSON Schema vocabulary and modeled it in Linked Data as well. This results in a slightly different syntax than what JSON Schema defines.

Reasons are that we want to include the data model in queries and reasoning. If we use the JSON Schema syntax, we would have a break of paradigms within the TD and basically would need to different parsers...

**Comment by handrews** [comment]
@mkovatsc if you're not going to use the JSON Schema syntax, it would be preferable to not call it JSON Schema.  That's caused a lot of headaches for OpenAPI (although we/JSON Schema are working with them to converge).  It turns out that when you tell people you are using JSON Schema they do expect to be able to write JSON Schema.

I haven't been able to keep on top of what's going on here, although I'd be happy to respond to specific JSON Schema concerns.  It's not immediately obvious to me why `minimum` and `maximum` can't be used.

**Comment by mkovatsc** [comment]
@handrews Thanks for the insight! How does OpenAPI call it now?

There is nothing about can't be used -- Mozilla just used `min` and `max` in their proposal although they intended to use the JSON Schema terms, which are the long ones. They are fixing it now.

**Comment by handrews** [comment]
@mkovatsc Oh I'm glad to hear the Mozilla thing was just a naming mixup (FWIW, I've accidentally used "min" and "max" when writing schemas myself).

OpenAPI has a "Schema Object", which is based on a specific JSON Schema draft but documents various restrictions and extensions (which led to an amusing debate about referring to it as a "superset-subset" or perhaps a "sideset" in last week's OpenAPI technical steering call :-) and one outright incompatibility (having to do with how `null` is supported).

This has led to several problems:

* It's almost, but not quite JSON Schema, so many people go along writing JSON Schema and get surprised when they hit one of the differences
* A number of OpenAPI users have written converters between JSON Schema and OpenAPI's Schema Object, as they want to use regular JSON Schemas for their API payloads elsewhere
* Tool vendors can't just use one of the many JSON Schema implementations out-of-the-box.  They either have to re-implement the roughly 80% that OpenAPI supports, or have to do some sort of conversion / post-processing to try to offload most of the work to a library and then patch up the results

A further problem is that now that they have the Schema Object, moving to full compatibility is disruptive to existing implementors.  But the incompatibility is a barrier to new implementations.

To be clear, OpenAPI had good reasons for coming up with the Schema Object.  JSON Schema was still largely a moribund project when they had to make a call on it.

Some of their restrictions/extensions are driven by code generation use cases, and we're trying to address that by coming up with an official vocabulary to support those use cases instead of them needing just pick a behavior (e.g. what is the relationship between `allOf` and OOP inheritance?  They're not really designed to be related, but code generation for OO languages really needs to be able to to recognize such things).

I haven't forgotten the TD interest in integration with JSON-LD and also CBOR, it's just that I'm the only person who regularly has substantial time to work on JSON Schema spec so it's slow going.  I'd be happy to discuss the road map here or in a call if that would be helpful, though.  The immediate focus is making JSON Schema more modular and extensible instead of being purely designed for validation but shoehorned into other use cases.

I definitely understand not being able to support JSON Schema as-is if it does not work with JSON-LD the way you need, but I hope we can fix that and support your use cases going forward.

**Comment by sebastiankb** [comment]
I will close this issue:
- W3C JSONLD-TD and JSON-TD proposal will rely on the JSON Schema terms such as maximum and minimum
- latest W3C JSONLD-TD spec clarifies that the terms of JSON Schema are used.

**Comment by benfrancis** [comment]
Note: I have an open pull request for JSON-TD which I just rebased so should be ready to land https://github.com/w3c/wot/pull/385
