### ISSUE TITLE
Can semantic markup be optional?

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-thing-description#86]
Is there a way to make semantic markup optional? (e.g. like Open Graph metadata in HTML)?

How much can be simplified by defining a default implied semantic context for a plain JSON serialisation? (Which could be denoted by a special MIME type like application/json+td)

**Comment by benfrancis** [comment]
The JSON-TD proposal shows a potential plain JSON serialisation which assumes a default implied context which defines built-in members like name, description, properties, actions and events.

Optional semantic annotations can then be added to a Thing Description to denote that it uses an externally defined schema.

E.g. an externally defined top level web thing type:

```
{
  "@context": "http://iot.schema.org",
  "@type": "Toaster"
}
```

And/or perhaps an externally defined type of property or "capability":

```
{
  "@context": "http://iot.schema.org",
  "@type": "Thermostat",
  "properties": {
    "temperature": {
      "@type": "Temperature",
      "description": "The current temperature in celcius"
    }
  }
}
```

**Comment by draggett** [comment]
I indeed believe that semantic markup can be made optional.  In one approach, the thing may itself be declared as having a named semantic type (e.g. "Thermostat" in your example). If the context declares a mapping for this name to a URI, that URI may be dereferenced to obtain further information. If there is no such mapping defined, the name can be translated as an RDF string literal.

A similar approach can be used for JSON object property names that are interpreted as metadata predicates. These are normally mapped via the context chain to RDF URIs. If the developer forgot to define a predicate, or deliberately chose not to,  an RDF blank node is generated for the predicate, along with a triple with the blank node as the subject, td:name for the predicate, and a string literal for the triple's object with the metadata's predicate name. 

If developer's fail to provide a mapping for type names, this should be an error as the application platform won't know how to handle that type.   In my use case study, I found it convenient to allow applications to define their own named names in terms of other types. This aids human comprehension of thing descriptions, and allows a type that is used multiple times in a thing description to be defined once rather than duplicated in place for each usage.

**Comment by mkovatsc** [comment]
> Is there a way to make semantic markup optional?

Yes, this is the target. The idea is that all `@...` markup from JSON-LD can be omitted and all required syntactic information is still in place by relying on the standardized TD vocabulary only.

Note that this requires the [already proposed step](https://rawgit.com/w3c/wot-thing-description/master/proposals/simplified-json-ld/index.html#converging-json-json-ld-proposal) from `interaction` to `properties`, `actions`, `events` entry points (so that the `Property`, `Action`, `Event` annotations in `@type` become obsolete).

**Comment by sebastiankb** [comment]
A question which just came up is if it make sense to keep the _@context_ key always mandatory, e.g., for identification the underlying TD version. Just lets assume assume there will be a TD 1.1 version in couple of years.  I think, the _@context_  can be quite helpful for differentiation.

**Comment by mkovatsc** [comment]
When we go for a TD serialization that is valid without semantic markup, I would strongly expect an proper media type such as `application/wot-td+json`. Ignoring the LD version issue, it would tell the receiver what context to apply.

If we go down the path of preprocessing (https://github.com/w3c/wot-thing-description/issues/90), we would have a TD serialization that is agnostic of the JSON-LD version (at least 1.0 and 1.1). Implementations could choose to either process by applying the initial TD preprocessing rules plus JSON-LD 1.0 processing or, later after 1.1 is released and we released an update of the TD spec, updated (and hopefully less) preprocessing rules plus JSON-LD 1.1 processing. (Note that preprocessing rules should be clear, formal, and limited!)

If we want to stick to pure JSON-LD processing, we will need full JSON-LD parsers in all devices or two conventional parsers (one for 1.0 and one for 1.1 or one for 1.0 and one converter from 1.1 to 1.0) in constrained devices. Does not feel good and no support for defaults anyway :(

**Comment by draggett** [comment]
The approach I propose us considering maps predicates with unknown URLs to blank nodes, along with a triple that associates these nodes with the name used in the JSON input.  This allows applications to process the RDF graph generated from the JSON even when the context declarations are missing or incomplete. Applications would also be able to interpret the JSON thing description directly, and to have built-in knowledge of common names for semantic terms in popular domains like smart homes.

**Comment by benfrancis** [comment]
@mkovatsc wrote:
> Yes, this is the target. The idea is that all @... markup from JSON-LD can be omitted (or ignored) and all required syntactic information is still in place by relying on the standardized TD vocabulary only.

Great, agreed.

> Note that this requires the already proposed step from interaction to properties, actions, events entry points (so that the Property, Action, Event annotations in @type become obsolete).

Also agreed.

> When we go for a TD serialization that is valid without semantic markup, I would strongly expect a proper media type such as application/wot-td+json. Ignoring the LD version issue, it would tell the receiver what context to apply.

Also agreed. We can bikeshed over the name. I'd suggest simply `application/td+json`.

**Comment by mkovatsc** [comment]
Semantic markup is now completely optional with the Simplified TD. Closing.
