### ISSUE TITLE
TD ontology minor suggestions

### ISSUE THREAD

**Issue by gatemezing** [w3c/wot-thing-description#909]
In the [td.ttl](https://github.com/w3c/wot-thing-description/blob/master/ontology/td.ttl) file, will it be possible to use:

1. `<https://w3.org/2019/wot/td> a owl:Ontology .` --> using the URI instead of the namespace URI?

1. Remove one of the dcterms/dc in the prefixes header.
1. Use `dcterms` <http://purl.org/dc/terms> in favor of <http://purl.org/dc/elements/1.1/.
1. Add also triples for`dcterms:issued` and `dcterms:modified` to track the different issued and modified dates?

Thanks for this great work. Hopefully, we might start to have multilingual labels/comments very soon :)

**Comment by sebastiankb** [comment]
@ethieblin what do you think about this?

**Comment by Murloc6** [comment]
@ethieblin and I agree on these four propositions.

We checked on other ontologies (like SOSA, PROV-O, etc.) and the ontology URI is the same as the namespace. This is not a limitation since from the HTTP protocol it is supposed to serve the same resource. But we agree that using the proper URI looks cleaner.

Let's discuss how to implement these features during our next meeting.
