### ISSUE TITLE
Rename "Thing Template" to "Thing Model"

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#930]
We are seeing the term "Thing Template" being used by people for various things. 
We had these different interpretations in various conversations over the last months.
A recent example is the presentation from Cristiano, who has a "template" in the sense of a file with placeholders.
We should consider straightening the terminology by renaming "thing template"  to a different name, i.e. a name that is not yet used for other purposes.

A proposed name is "Thing Model" with the definition we already agreed in the Architecture group for Thing Template. This change implies changing a few occurences in architecture and TD.

**Comment by takuki** [comment]
In TD spec, it is called _Thing Description Templates_.
Because it is a description of Thing Model, I think we can call it "Thing Model Description".

**Comment by mmccool** [comment]
I like the suggestion.  I would propose simply using "Thing Model" to keep acronyms etc. simpler (it also makes our acronym space less cluttered since we already have problems with TD, TDD, TDT, etc.).  I think the term is good because it says what it IS, as opposed the mechanism used to implement it.

**Comment by sebastiankb** [comment]
From today's TD call:

- there seems a consensus to do the renaming to "Thing Model"
- if we going to rename the term "Thing Description Template" to "Thing Model" we should add a note about the renaming + it is the same meaning where TDT was introduced in TD 1.0
- we should also check with @mlagally since he introduced the term "template"

**Comment by sebastiankb** [comment]
the latest draft we use the new Term Thing Model. Close this issue
