### ISSUE TITLE
Thing Description versioning and Scripting API

### ISSUE THREAD

**Issue by relu91** [w3c/wot-thing-description#932]
As briefly described in https://github.com/w3c/wot-scripting-api/issues/225, currently, the scripting API document is related to the Thing Description specification. For example, if we decide to drop the `read/writeMultipleProperties` operation the API spec is affected. Therefore, the need to state something like the following: 

> This API spec is compliant to Thing Description version X.X

However, it is not clear which is the identifier of the TD version. Different options that I found:
- W3C document versioning: for example https://www.w3.org/TR/2018/WD-wot-thing-description-20180405/ 
- Context version (ontology version?):  https://www.w3.org/2019/wot/td/v1

Any opinions about which is the most appropriate link to use in this case?

**Comment by egekorkan** [comment]
So firstly, the published W3C should be considered: https://www.w3.org/TR/2020/REC-wot-thing-description-20200409/

One interesting aspect to think of is the correction of the errors. It is more likely that the TD spec has more error fixes or explanations that are more up to date since it is created from the ontology but with additions that are not covered by the ontology file. Not sure if this is highly relevant though.

**Comment by sebastiankb** [comment]
In my view the latest API should follow the latest version of the TD. I think, it makes sense that the API should also have a API version tag that corresponds to the TD version like WoT API 1.1 follows WoT TD 1.1.

**Comment by sebastiankb** [comment]
based on today's TD call we should check other standards like JS API, HTML, XML Schema, ...

I think we should also ask the JSON-LD team about this topic. This can be topic for our joint meeting during TPAC.

**Comment by sebastiankb** [comment]
I think, we have to clarify two points today:

- TD 1.1 version identifier  
- content type
