### ISSUE TITLE
We need an OAuth2 example for TD 1.1

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#948]
for better understanding how the OAuth2 security scheme is working a good example would be good

**Comment by relu91** [comment]
We have [Example 17](https://w3c.github.io/wot-thing-description/#example-17), do we need one for each flow?

**Comment by egekorkan** [comment]
It would be good since they differ quite a bit but it might be also possible to pack them into one example :)

**Comment by sebastiankb** [comment]
>We have Example 17, do we need one for each flow?

Example 17 is now Example 18 https://w3c.github.io/wot-thing-description/#example-18

**Comment by mmccool** [comment]
Discussed in security call Nov 29, 2021:
- Only one flow really makes sense for general use in IoT, and that is the client flow
- The current example uses the "code" flow, which is not really appropriate
- Adding examples for all the flows would not be especially useful, since they are anyway very similar.  The example is really trying to demonstrate how to use scopes, which are the same in all flows
- Could just change example to use the "client" flow (and remove the "authorization" endpoint, it is not used in the client flow).

Consensus (including Cristiano): Update PR to only have one example, for "client", and leave it at that.
