### ISSUE TITLE
We need extension ontology to include implicit and password flows in OAuth2

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#949]
For the usage of OAuth2 with implicit and password flows there need a standard ontology to be identified

**Comment by mmccool** [comment]
Discussed in security call Nov 29, 2021
- The removal of the implicit and password flows actually broke backward compatibility with TD1.0.  So if we are going for strict compatibility, we should put them back.
- However: consumers that can understand both TD1.0 and TD1.1 will be able to distinguish them by their context URL, and will not be troubled.   Consumer that only understand TD1.0 won't be bothered by a feature that is non-existent.  So in practice this is not really a problem.
- For the TD spec, the short-term problem is having a fixed URL for the extension.  This should be decided soon and should be ideally "under" the URL for the TD1.1 context (whatever it is).  E.g. if the base URL for the TD1.1 context is "https://X" then the extension should be something like "https://X/deprecated-oauth2-flows".
- The current text just says an extension must be used, it does not define a standard extension.  This is technically fine, but it might be nicer if there WAS a standard ontology.  If we do want one, then in addition to the URL (which should be given in the TD spec) we need an ontology file.  The ontology file can be created by resurrecting the old ontologies for these flows.
- In general this is a corner use case for brownfield devices.  Neither flow is very good for IoT, and old devices probably did not use OAuth2 anyhow.  So it would be very rare.
Consensus: an extension ontology is a nice-to-have but is not essential.  So we can leave the current text as is, but time permitting, if we can define at least an extension URL in time for the review it would be good.  Note though that we also then have to define test cases for these flows (probably), which would be a little annoying, since they are obsolete...

**Comment by egekorkan** [comment]
> The removal of the implicit and password flows actually broke backward compatibility with TD1.0. So if we are going for strict compatibility, we should put them back.

They are not in TD 1.0 though?

**Comment by mmccool** [comment]
So I went back and looked at what we actually said (and we discussed this in the security call on Dec 6 as well):
- The TD 1.0 document only explicitly mentions "code" (and this is all we tested, as I recall)
- It does use "string" for the flow and gives "code" as an *example*: "e.g. code", so implies others can be used
- It cites and RFC, RFC8252, which at least says that implicit is NOT RECOMMENDED
- So... I think for TD1.1 we can take the stance that we are *clarifying* what is allowed and what is not
- Bottom line: current TD 1.1 draft does not remove the "code" flow, so is not in conflict with TD1.0 document.  It does not support implicit, but this was discouraged by RFC8252 so we are justified in leaving out explicit built-in support for it.  TD1.0 unfortunately does not have "client" but we agreed we can *add* flows and maintain compatibility (although older TD1.0 processors won't understand it, but it will be handled in practice by the HTTP protocol negotiation).  So... I think we are ok.  I don't think we want or need a normative ontology for implicit and password (if we did do it, we would have to test it, too).  Even if we just define a URL it opens a can of worms.  Since it would only be useful for brownfield devices that can't be updated, we can wait and see if a use case comes up, and if so, publish an (informative) W3C Note.  This is however a low-probability event.

Conclusion: leave the current text alone, and don't define an ontology for implicit and password.  Nothing to do here (except maybe delete an ed note if there is one) and this issue can be closed.

**Comment by relu91** [comment]
> Conclusion: leave the current text alone, and don't define an ontology for implicit and password. Nothing to do here (except maybe delete an ed note if there is one) and this issue can be closed.

+1

**Comment by mmccool** [comment]
We can close this issue, but in general for the next charter we should discuss how to publish ontologies, especially if we want to move non-structural security schemes to extension ontologies generally.  We could have a separate "registry" document.  See [W3C Process Document - Registry Track](https://www.w3.org/2021/Process-20211102/#registries).  A registry is a kind of special Note.   Probably should state our intention to host this in our new charter...

**Comment by relu91** [comment]
> See [W3C Process Document - Registry Track](https://www.w3.org/2021/Process-20211102/#registries). A registry is a kind of special Note. Probably should state our intention to host this in our new charter...

I think there are a lot of similarities with the Protocol binding template spec.

**Comment by mmccool** [comment]
Issue has been resolved (or really not an issue) so propose closing it.  However, we might still want to create ontology files for other OAuth2 flows, but this should be done as part of our general security/bindings reorg.

Marking as Propose Closing.
