### ISSUE TITLE
URL shortname convention for TD 1.1

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#990]
For the TD 1.1 FPWD release we need a decision about the new URL. Here some ideas:

1. https://www.w3.org/TR/wot-thing-description11/
2. https://www.w3.org/TR/wot-thing-description1.1/
3. https://www.w3.org/TR/wot-thing-description-1.1/

For the JSON-LD context file I would suggest to use a temporary / wip  context URL again. In the past we used: https://www.w3.org/ns/td

Any feedback is welcome.

**Comment by mmccool** [comment]
See also https://www.w3.org/2005/05/tr-versions

**Comment by egekorkan** [comment]
Not a strong opinion but here is my opinion:
1. 11 really looks like eleven. Also, if later on we want to have version 1.1.1, it would be 111 which makes it even more ambiguous.

I like having dots for versioning since we can easily follow semantic versioning with it but it _feels_ weird to see it in the URL like that. I think it however looks ok when we have `https://www.w3.org/TR/wot-thing-description/1.1/` or `https://www.w3.org/TR/wot-thing-description/v1.1/`. This might be also easier when we want to redirect `https://www.w3.org/TR/wot-thing-description` to the latest version

**Comment by danielpeintner** [comment]
FYI: I checked what *others* do (in other areas).

On NPM for example they use the original URL for the latest version
`https://www.npmjs.com/package/@node-wot/td-tools/`

If someone want a specific version you add it like  "v/0.7.2"
`https://www.npmjs.com/package/@node-wot/td-tools/v/0.7.2`

Not sure though if updating the existing content breaks anything..

**Comment by sebastiankb** [comment]
there was a w3c proposal to use the pattern as for JSON-LD 1.1 

I will close this issue
